Agregar mi perfil
undefined-academy/semana-1 pull request #1
Opened 2023-03-03 04:18 UTC by aleepsy

### ¿Cómo fue mi proceso?

Sencillo, ya he tenido la oportunidad de trabajar con Git y GitHub y poseo un nivel básico de conocimiento.
Adicional utilice el editor de _Codespaces_ y no cloné mi repositorio en local, me parece una forma más sencilla y el entorno en la nube es fácil de utilizar.

2023-03-20 01:03 UTC, Juanmiyo0696 requested changes

2023-03-20 01:03 UTC, Juanmiyo0696 commented on github-profiles/aleepsy-4362.md
> +
Hola como estas? recuerda poner tus comandos y tus alias a tu archivo md como si fuera tu perfil de git hub y continua con los pasos de la semana 1... exitos.

2023-03-26 20:42 UTC, glrodasz commented
@aleepsy Dejanos saber si piensas aplicar el feedback para mantener el PR abierto.

2023-03-27 23:46 UTC, aleepsy commented
Gracias por los comentarios. en breve aplico las correcciones! @glrodasz

2023-03-28 02:57 UTC, aleepsy reviewed
Done!

2023-03-28 06:57 UTC, merged