Datos de Felipe Quant
undefined-academy/semana-1 pull request #101
Opened 2023-03-05 18:25 UTC by fjquants

**Inicio del ejercicio**

Los primeros pasos los realicé sin complicacion alguna

**Desarrollo**

- Clone el repositorio
- Cree el archivo nuevo (me ayudé con el VS Code)
- Al intentar hacer push no me funcionó al inico y solicité ayuda y logré finalizar el ejercicio (al parecer no realicé correctamente el clonado del repositorio mediante SSH)

2023-03-07 14:17 UTC, fjquants commented
Investigue un poco para hacer la tabla

2023-03-09 14:58 UTC, jesab3l requested changes

2023-03-09 14:58 UTC, jesab3l commented on fjquant-2458/index.html
> +        </style>
Solo falta colocar esto en el archivo style.css

2023-03-09 18:31 UTC, fjquants commented on fjquant-2458/index.html
> +        </style>
Muchas gracias por tus observaciones

2023-03-09 18:33 UTC, fjquants commented on fjquant-2458/index.html
> +        </style>
Ya realicé el cambio recomendado

2023-03-09 19:59 UTC, fjquants commented on fjquant-2458/index.html
> +        </style>
Listo, no se había salvado apropiadamente el archivo.

2023-03-09 20:06 UTC, jesab3l approved these changes
👍 Todo bien!

2023-03-09 20:25 UTC, MauBedoya approved these changes
nombres, archivos y contenidos parecen correctos 👍

2023-03-09 20:25 UTC, MauBedoya commented on fjquant-2458/README.md
> +https://github.com/fjquants
como detalle, también podrías usar: 
`[Mi perfil de Github](https://github.com/fjquants)` 

para que se pueda ver de esta manera: 
[Mi perfil de Github](https://github.com/fjquants)

2023-03-09 20:25 UTC, MauBedoya commented on fjquant-2458/style.css
> +}
sería bueno revisar los paddings y margins de la parte superior del body y del primer h1 para acercar un poco el contenido a la parte superior de la página, aunque esto quizá es un poco a gustos

2023-03-09 22:05 UTC, fjquants commented on fjquant-2458/README.md
> +https://github.com/fjquants
Gracias por tus observaciones, lo voy a realizar

2023-03-14 09:41 UTC, merged