Second Task - Undefined Academy
undefined-academy/semana-1 pull request #105
Opened 2023-03-05 19:21 UTC by DanRev

## Second Exercise.

_This pull request contains the second exercise_. The **Process** to do this exercise was:

1. Make a fork of [Semana - 1](https://github.com/undefined-academy/semana-1) repository.
1. Clone the forked repository.
1. Create a new branch _dev_ and switch to it
1. Create a new file at **Semana-1/github-profiles/** with the name of my discord tag **IRatten#5681**
1. Add a new line in this file with a link to my github profile and save the file.
1. Next, I execute commands add, commit and push to _dev_ branch
1. Then, I go to github and create pull request, with this resume.

2023-03-09 14:17 UTC, Alexis033 approved these changes
Veo todo muy bien.

2023-03-09 19:37 UTC, MauBedoya requested changes
según veo al revisar el user y tag del perfil de Discord desde el que solicitaste la revision, me parece que el nombre de la carpeta que contiene tus archivos debería ser `IRatten-5791`.

2023-03-09 19:37 UTC, MauBedoya commented on github-profiles/IRatten-5681/style.css
> +body{
podrías jugar con el color del background del body y/o el color de la fuente para aumentar la comodidad al leer el contenido.

2023-03-09 23:57 UTC, DanRev commented on github-profiles/IRatten-5681/README.md
> +Github Profile - https://github.com/DanRev
Ya quedaron los cambios.
Muchas gracias 😀

2023-03-09 23:57 UTC, DanRev commented on github-profiles/IRatten-5681/style.css
> +body{
Ya quedaron los cambios.
Muchas gracias 😀

2023-03-10 01:48 UTC, MauBedoya approved these changes
ya está corregido 👍

2023-03-20 22:44 UTC, merged