Primer commit del fork GabrielObregon#7536
undefined-academy/semana-1 pull request #109
Opened 2023-03-05 19:47 UTC by gabobregon89

# Que desafío
## Miedo, pánico o ambos?? jajaja
Estuvo muy bueno el ejercicio y necesite ayude de discord y google para poder completarlo.

2023-03-09 19:25 UTC, Mfassi96 reviewed
Hola, creo que te falta agregar una tabla con los comandos alias que utilizas

2023-03-09 20:01 UTC, Legnaleugim requested changes
Revisado. Tienes todos los ejercicios pero debes hacer correcciones.

2023-03-09 20:01 UTC, Legnaleugim commented on github-profiles/GabrielObregon-7536/main.css
> +p {
Hay estilos que no estás usando y el color rojo para el texto no es muy agradable al a vista.

2023-03-10 03:40 UTC, gabobregon89 commented on github-profiles/GabrielObregon-7536/main.css
> +p {
Gracias por todos los comentarios, ya le aplique mas onda.

2023-03-10 04:16 UTC, Legnaleugim requested changes
Todo muy bien. Solo falta borrar el archivo GabrielObregon-md7536.md ya que no es requerido

2023-03-10 15:47 UTC, nobody-redhawk approved these changes
# Recomendaciones

1. Detallar paso a paso las actividades requeridas en los ejercicios de todas las clases de la semana-1
1. Eliminar el archivo `GabrielObregon-7536.md` (esta informacion ya está en el archivo README.md)
2. Hacer deploying con vercel y poner el link en la descripcion para ver los resultados de la pagina del perfil.

2023-03-11 17:35 UTC, Legnaleugim commented on github-profiles/GabrielObregon-7536.md
> +# Hola soy Gabriel Obregon
Recuerda que al borrar un archivo de un repositorio local de git, debes añadir ese cambio a la fase de staging antes de hacer el commit. Cuando borras un archivo debes revisar git status y debe de salir algo como `"Changes not staged for commit"`, y los archivos que has modificado. Haces `git add <archivo borrado>` o `git add .` y luego puedes hacer commit y push. Otra forma es usar `git rm <archivo>` que borra el archivo del repositorio local y de una vez pasa ese cambio a la staging area para hacer commit y push. También si se te complica menos puedes borrarlo desde github.

2023-03-14 01:21 UTC, gabobregon89 commented on github-profiles/GabrielObregon-7536.md
> +# Hola soy Gabriel Obregon
Gracias por los consejos, ahi ya pude eliminar ese archivo que estaba de mas.

2023-03-14 01:44 UTC, Legnaleugim approved these changes

2023-03-14 09:39 UTC, merged