Mi primer pull request
undefined-academy/semana-1 pull request #115
Opened 2023-03-05 23:58 UTC by Matipela

Me costó un poco, tuve que investigar bastante y mirar las pull request de mis compañeros para entender lo que tenía que hacer, voy a contar un poco lo que hice y los errores que tuve.

1. Hice el **fork** del repositorio Semana-1 de Undefined Academy.
2. **Cloné** el repositorio en una carpeta dentro de home (mi primer error fue clonarlo como **HTTPS**, ya que luego te pide un usuario y contraseña de GitHub en la terminal pero ingresando los míos no me dejaba seguir, después vi en la desripción de la pull request de una compañera que hay que **clonar** como **SSH**)
3. Una vez clonado entre al archivo **semana-1**, luego a --github-profiles** y allí cree un archivo markdown con el comando '*echo "Algo" > Matilayo-0663.md*', mas adelante también leyendo lo que hicieron mis compañeros aprendí que el archivo markdown lo podia crear con el comando *'touch Matilayo-0663.md'*.
4. Abrí el **archivo Markdown** con **VS Code** usando el comando *'code Matilayo-0663.md'*
5. Aquí copié el link de mi **perfil de GitHub**
6. Guardé los cambios
7. Hice *'git add Matilayo-0663.md'* para agregar el arcgivo al staging, luego *'git commit -m "Mi primer commit"'* para "*commitear*" el archivo y finalmente *'git push'* para subir el archivo a mi repositorio
8. Finalmente hice la pull request desde Github.

*Nota: La verdad es que me costó bastante y no terminé de entender lo que hice, pero como no quería atrasarme más fui siguiendo los pasos que hicieron mis compañeros, ahora me voy a mirar algunos tutoriales y leer documentación de git y github para entender un poco mas.*

2023-03-12 01:48 UTC, monnsalgado requested changes

2023-03-12 01:48 UTC, monnsalgado commented on github-profiles/Matilayo-0663/index.html
> +    <h2>🍰 30 years old</h2>
si ambos son h2, podrías meterlos en la misma etiqueta y si quieres que estén separados, poner una etiqueta `<br>` para salto de línea, la pones después del "from argentina"

2023-03-12 01:48 UTC, monnsalgado commented on github-profiles/Matilayo-0663/index.html
> +</body>
que cool que te hayas atrevido a hacerlo en inglés, practicar es la clave para mejorar

2023-03-12 01:48 UTC, monnsalgado commented on github-profiles/Matilayo-0663/styles.css
> +
yo cambiaría el header hasta arriba del css, pero solo por orden visual

2023-03-12 01:48 UTC, monnsalgado commented on github-profiles/Matilayo-0663/index.html
> +</body>
te falta el ejercicio de la clase 1 sobre _markdown_ solamente :)

2023-03-12 03:51 UTC, nobody-redhawk requested changes
Te falta el contenido del archivo README.md

2023-03-13 23:03 UTC, Matipela commented on github-profiles/Matilayo-0663/styles.css
> +
Muchas gracias por el feedback, ya hice los cambios sugeridos 😄

2023-03-14 00:02 UTC, Matipela commented
> Te falta el contenido del archivo README.md


Listo @nobody-redhawk , ya lo agregué, muchas gracias.

2023-03-14 14:47 UTC, nobody-redhawk approved these changes

2023-03-14 18:15 UTC, joaquinesteban approved these changes
Quedo todo Listo!!

2023-03-22 20:27 UTC, merged