Mi perfil
undefined-academy/semana-1 pull request #117
Opened 2023-03-06 00:19 UTC by cramdal

## PASOS PARA COMPLETAR LA PRACTICA

1. Hacer el fork del repositorio usando la interfaz visual de github
2. Clonar el repositorio generado durante el proceso anterior
3. Agregue mi archivo MarkDown
4. Genere un commit al repositorio origen
5. Mediante la interfaz visual de GitHub genere el Pull Request

2023-03-09 10:37 UTC, DevOld112 commented
Me parece excelente el trabajo realizado

2023-03-10 00:35 UTC, manuelmannuel approved these changes
Buen trabajo, sigue mejorando

2023-03-16 00:10 UTC, cramdal commented
> Hola Dalia, me parece bien el trabajo hecho, solo como comentario, acomodar la tabla del markdown como lo comentó en la clase el maestro, Saludos.

Hola, he realizado las correcciones que me indicaste, serias tan amable de volver a revisar, por favor, de antemano gracias, saludos.

2023-03-28 23:31 UTC, dfm555 requested changes

2023-03-28 23:31 UTC, dfm555 commented on .vite/deps_temp/package.json
Elimina esta carpeta

2023-03-29 00:10 UTC, cramdal commented on .vite/deps_temp/package.json
carpeta eliminada

2023-03-29 17:38 UTC, dfm555 approved these changes

2023-03-29 17:38 UTC, merged