Haciendo pull request de mi perfil
undefined-academy/semana-1 pull request #122
Opened 2023-03-06 01:45 UTC by jgarcia-alt

## ⚙ Proceso para hacer fork

Primero investigue como hacer un fork🔍. Para ello tenia que hacer click sobre un boton para hacer una copia del repositorio y vincularlo con mi perfil 🖱.

## ⚙ Agregar archivo y hacer commit

Lo siguiente fue clonar el fork de forma local 🖥. Haciendo click sobre el boton verde copie el enlace y lo puse en la terminal junto con el comando para clonar.
```
git clone git@github.com:jgarcia-alt/semana-1.git
```
Despues sigue hacer pull request para hacer cambios en el fork Para ello ejecute los siguientes comandos en la terminal💻:
```
git init
git add .
git commit -m "Agregando perfil de Jonatan Garcia"
git push -u origin
```
##⚙ Por ultimo logre hacer un pull request en github.

2023-03-22 01:51 UTC, Gaston095 requested changes

2023-03-22 01:51 UTC, Gaston095 commented on github-profiles/JonatanGarcia-2522.md
> +|Comando|Descripción|
Hola!! Estaria bueno que alinies la tabla para visualizarla mejor!

2023-03-22 01:51 UTC, Gaston095 commented on JonatanGarcia#2522/index.html
> +    <title>Mi perfil</title>
Podrias agregar tambien la etiqueta meta con la codificacion utf-8, ya que el sitio esta en español asi se visualizan bien los acentos.

2023-03-22 01:51 UTC, Gaston095 commented on JonatanGarcia#2522/index.html
> + Estoy interesado en el desarrollo web y sus tecnologias, actualmente me encuentro estudiando en <i>FreeCodecamp</i> y <i>Undefined Academy</i> ✍.</p>
Estoy viendo la etiqueta de cierre de parrafo /p pero no veo la de apertura, solo en el primer parrafo ..

2023-03-22 01:51 UTC, Gaston095 commented on JonatanGarcia#2522/index.html
> +<img src="https://undefined.academy/assets/images/image02.jpg?v=88a0b070">
Es buena practica agregar el atributo alt a las etiquetas img para indicar de que es la imagen

2023-03-22 01:51 UTC, Gaston095 commented on JonatanGarcia#2522/index.html
>  <table>
Creo que estas abriendo dos veces la etiqueta table y la cierras una sola ves

2023-03-22 02:11 UTC, julietalazzaro requested changes

2023-03-22 02:11 UTC, julietalazzaro commented on JonatanGarcia#2522/README.md
> +|Comando|Descripción|
Puedes alinear el contenido de la tabla para que sea mas legible el mardown puro

2023-03-22 02:11 UTC, julietalazzaro commented on JonatanGarcia#2522/index.html
> +<head>
Esta faltando aqui la apertura de la etiqueta HMTL

2023-03-22 02:11 UTC, MariaSolArroyo requested changes
El nombre de la carpeta deberia ser un guión y no el simbolo # para que a futuro no tengas problema.

2023-03-22 02:11 UTC, MariaSolArroyo commented on JonatanGarcia#2522/index.html
>  <table>
creo que hizo dos tablas , creo que esta bien.

2023-03-23 02:06 UTC, MariaSolArroyo approved these changes

2023-07-18 20:54 UTC, glrodasz approved these changes

2023-07-18 21:00 UTC, merged