Finalizando tarea de Fork
undefined-academy/semana-1 pull request #128
Opened 2023-03-06 02:41 UTC by NicoRomero3210

## Primer Fork Bootcamp
1. Primero tuve que crear un fork a partir del repo undefined-academy/semana-1, esto permitio que yo tenga una copia de este repo en mi cuenta y asi obtuve permisos de escrituray pude crear el nuevo archivo con mi nobre de usario de Discord y subirlo a la copia del repo en mi cuenta
2. Luego tuve que solicitar este pull request para que mis cambios entren al repo de origen

2023-03-19 21:50 UTC, veacosta13 reviewed
Buenas! Esta muy bueno tu trabajo, te deje un comentario donde podrias alinear la tabla para dejarlo aun mejor de lo que esta

2023-03-19 21:50 UTC, veacosta13 commented on github-profiles/nicoromero0907-6873.md
> +|**rm**| *Permite borarr un archivo o directorio del directorio de trabajo actual, para borrar un directorio que contiene otros directorios y/o carpetas se debe usar una flag especial para que borre
Podrías alinear esta tabla

2023-03-19 21:51 UTC, NicoRomero3210 commented on github-profiles/nicoromero0907-6873.md
> +|**rm**| *Permite borarr un archivo o directorio del directorio de trabajo actual, para borrar un directorio que contiene otros directorios y/o carpetas se debe usar una flag especial para que borre
Muchas Gracias por la correcion! Super, en el proximo commit arreglo este detalle

2023-03-20 20:08 UTC, MauBedoya requested changes
Parece que se te coló una carpeta `_site` con otras versiones de tu trabajo verdad? 🤔

2023-03-20 20:08 UTC, MauBedoya commented on _site/github-profiles/nicoromero0907-6873/_site/index.html
> +    <a href="https://github.com/NicoRomero3210">
tal vez se puede agregar un `target="_blank"` aquí

2023-03-21 01:42 UTC, julietalazzaro requested changes
Buenas! El sitio muy bien, tendrias que dejar solo una carpeta dentro de github-profiles. Si la otra es generada por algun plugin para servir tu sitio en las pruebas podrias agregarla en el gitignore

2023-03-21 01:42 UTC, julietalazzaro commented on _site/github-profiles/nicoromero0907-6873/README/index.html
Creo que esta carpeta esta de mas, solo deberia quedar la que esta dentro de github-profiles con tu nombre

2023-03-21 01:42 UTC, julietalazzaro commented on github-profiles/nicoromero0907-6873/index.html
> +<html>
Podrias agregar en la etiqueta html el lenguaje del sitio

2023-03-21 01:48 UTC, NicoRomero3210 commented on _site/github-profiles/nicoromero0907-6873/_site/index.html
> +    <a href="https://github.com/NicoRomero3210">
Si, tenes razon, asi abro el github en otra pestaña, lo cambio en el proximo commit, gracias por la sugerencia!

2023-03-21 01:49 UTC, NicoRomero3210 commented on _site/github-profiles/nicoromero0907-6873/README/index.html
tenes razon, si, la creo uno de los paquetes que uso para levantar el sitio, la borro en el proximo comit y la agrego al .gitignore asi ya no molesta mas, gracias por la corrrecion!

2023-03-21 02:41 UTC, julietalazzaro approved these changes
Excelente Nico!

2023-03-21 18:40 UTC, JoeOsG approved these changes
### ¡Bien!

2023-08-14 02:00 UTC, closed without merging