Create Oziel-3111
undefined-academy/semana-1 pull request #137
Opened 2023-03-06 05:03 UTC by Oziel07

##Ejercicio Fork, commit & Pull request, algo nuevo para mi y listo paras seguir aprendiendo,

2023-03-10 04:27 UTC, Oziel07 commented
Se agrega mi profile html.
1. Se crea los archivos HTML en base dek profile Markdown.
2. Add, commit, y push.

2023-03-11 12:14 UTC, VALNTNO requested changes
Todo está muy bueno y prolijo, faltan algunos pequeños retoques

2023-03-11 12:14 UTC, VALNTNO commented on Oziel-3111/about.html
> +<html lang="en">
Veo que en todas las páginas el   `<html lang="en">` está en inglés(en) cuando el contenido de tu website esto en español (esto perjudica mucho al posicionamiento SEO)

2023-03-11 12:14 UTC, VALNTNO commented on Oziel-3111/index.html
> +    <p4>defenderme en este mundo de la programación.</p4>
Otra cosa a resaltar es que las etiquetas `<p1> <p2> <p3> <p4>` etc no existen, solo se usa `<p>`, cuando usas esas etiquetas, lo que pasa es que estás creando tus propias etiquetas .

2023-03-11 23:15 UTC, Oziel07 commented
Se agrega la mejora de mi página HTML - CSS (Diseño web en 4 minutos).
- Agregan imágenes.
- Mejora de letra.
- Mejora diseño.

2023-03-13 18:28 UTC, Oziel07 commented on Oziel-3111/about.html
> +<html lang="en">
Ya las modifique, gracias.

2023-08-13 02:00 UTC, closed without merging