Add Leonardo Pintor profile
undefined-academy/semana-1 pull request #14
Opened 2023-03-03 15:41 UTC by pintor32

# Solución
Para resolver este ejercicio se siguieron estos pasos:
- Se hizo fork del reporitorio original al mio.
- Se clonó el proyecto del repositorio remoto a mi computador.
- Se creó el archivo .md con el nombre de usuario en discord y se agrego la descripcion del GitHub.
- Se hizo el commit y se realiza el pull request.

2023-03-09 03:34 UTC, Alexis033 commented on github-profiles/Leonardo Pintor-6833/README.md
> +
You are missing the part of the tables with the commands and aliases.

2023-03-09 03:42 UTC, Alexis033 requested changes
You are missing the part of the tables with the commands and aliases in the README.md.

2023-03-09 03:42 UTC, Alexis033 commented on github-profiles/Leonardo Pintor-6833/README.md
> +
You are missing the part of the tables with the commands and aliases.

2023-03-09 18:16 UTC, Alexis033 approved these changes

2023-03-13 23:58 UTC, Matipela approved these changes

2023-03-14 00:38 UTC, Romero-Agustina reviewed
Leonado me pareció muy prolijo tu md, incluso el estilo de tu html es muy limpio, anímate a experimentar con colores en css! te felicito por tu amplia experiencia saludos y éxitos en el bootcamp

2023-03-14 00:38 UTC, Romero-Agustina commented on github-profiles/Leonardo Pintor-6833/README.md
> +https://github.com/pintor32
Una manera más correcta de agregar un link en markdown sería **[palabra que quieres que aparezca resaltada](link a tu perfil). Permitiría que funcione como link realmente.
```suggestion
[Click to visit Leonardo Pintor's github profile](https://github.com/pintor32)```

2023-03-14 14:52 UTC, pintor32 commented
> Leonado me pareció muy prolijo tu md, incluso el estilo de tu html es muy limpio, anímate a experimentar con colores en css! te felicito por tu amplia experiencia saludos y éxitos en el bootcamp

Muchas gracias por tus comentarios y sugerencias, los tendré en cuenta

2023-03-14 21:02 UTC, dfm555 approved these changes
Buen trabajo

2023-03-14 21:04 UTC, merged