Proceso
undefined-academy/semana-1 pull request #15
Opened 2023-03-03 15:54 UTC by Nicoov

Fue relativamente fácil gracias a la información entregada en el curso.

2023-03-09 13:47 UTC, lucianogarriga reviewed
En líneas generales Nico ha cumplido con los requisitos establecidos por Guillermo. Sólo unos detalles mínimos en cuando redacción y estructura visual del archivo markdown.

2023-03-09 13:47 UTC, lucianogarriga commented on github-profiles/NicoovLamperouge-893/NicoovLamperouge#893.md5
> +Front end Jr
I recommend to put "frontend web developer Jr". Frontend it's a single word. And then, it is recommended to put a complete description, to know that it is web development.

2023-03-09 13:47 UTC, lucianogarriga commented on github-profiles/NicoovLamperouge-893/NicoovLamperouge#893.md5
> +### 5 comandos de la terminal
Recomendaría que un archivo sea todo en inglés, o todo en español.

2023-03-09 13:47 UTC, lucianogarriga commented on github-profiles/NicoovLamperouge-893/NicoovLamperouge#893.md5
> +| Comando |     Descripción  |
Recomendaría alinear la tabla.

2023-03-09 17:39 UTC, Nicoov commented on github-profiles/NicoovLamperouge-893/NicoovLamperouge#893.md5
> +### 5 comandos de la terminal
La verdad no lo había tomado en cuenta. Gracias luciano!

2023-03-09 18:46 UTC, lucianogarriga commented on github-profiles/NicoovLamperouge-893/NicoovLamperouge#893.md5
> +### 5 comandos de la terminal
De nada Nico!! Muy buen trabajo!

2023-03-16 16:59 UTC, DevOld112 requested changes
Nicoo que tal?

Me ha gustado los colores que has escogido para tu proyecto y el css en general esta bien.

Te sugiero algunos cambios en el HTML, le has hecho un ojo al desarrollo web en 4 minutos de Jeremy Thomas? Igual aqui te dejo el enlace:

El cambio que si veo necesario es que seas un poco mas ordenado en tu codigo HTML, sobre todo en el  apartado de Tablas, por que mejor no lo haces de esta manera?

```
<h2>Tecnologias</h2>

    <table class="container-table">
        <thead>
            <tr>
                <th>Tecnologias</th>
                <th>Nivel</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>HTML</td>
                <td>Intermedio</td>
            </tr>
            <tr>
                <td>CSS</td>
                <td>Intermedio</td>
            </tr>
            <tr>
                <td>JavaScript</td>
                <td>Intermedio</td>
            </tr>
            <tr>
                <td>React</td>
                <td>Intermedio</td>
            </tr>
        </tbody>
    </table>
```

Lo hace mucho mas fácil de leer y no ocupas tanta linea de código. Podrías intentar lo mismo con la otra tabla.

Ojo: estos cambios no afectan visualmente como se vera tu pagina, se va a ver exactamente igual, lo que hará esto es que al revisarlo se vea todo mas ordenado 

Me comentas, sigue asi!

2023-03-17 12:46 UTC, ManuCastrillonM commented on github-profiles/Nicoov
Igual con este archivo

2023-03-17 16:23 UTC, Nicoov commented
¡Hola! Lamento la demora en responder, acabo de ver sus comentario y hecho los cambios. Muchas gracias por las recomendaciones 😀

2023-03-17 16:38 UTC, DevOld112 approved these changes
Excelente Nicoo! Ahora si.

2023-03-20 23:51 UTC, camilasilvab approved these changes

2023-03-25 17:23 UTC, merged