ejercicio 2
undefined-academy/semana-1 pull request #150
Opened 2023-03-06 17:11 UTC by Andrssnsdc

✅ Hice un **fork** del repositorio original
✅ Lo **clone** en local
✅ Agregue un archivo markdown con el link mi perfil de Github 
✅ Hice el **commit** 
✅ Al final hice un **Pull Request**

2023-03-21 14:53 UTC, MauBedoya requested changes
Vas por buen camino, te deje algunos comentarios que tal vez te sirvan, y revisa el tema de esos dos archivos que parece que se colaron, podrías borrarlos de tu carpeta y hacer `commit` otra vez si no son necesarios.

2023-03-21 14:53 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/README.md
> +# https://github.com/Andrssnsdc
también puedes usar:
`[Mi perfil de GitHub](https://github.com/Andrssnsdc)`
Para que te quede así:
[Mi perfil de GitHub](https://github.com/Andrssnsdc)

2023-03-21 14:53 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/README.md
> +__________________________________________
aquí querías usar una línea horizontal que de una separación verdad?, si es así, también lo puedes hacer usando solo 3 guiones así:
`---`
de modo que queda más "limpio" el Markdown.

En caso de que tu intención fuera darle un subrayado al título, no es muy necesario en **GitHub** ya que por defecto se pone una pequeña línea debajo de los títulos que pongas con `#`

2023-03-21 14:53 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/README.md
> +*********************************
el anterior comentario también aplica aquí, solo que, **por lo que tengo entendido** no se usan `***` si no los guiones de siempre `---`

2023-03-21 14:53 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/header.jpg:Zone.Identifier
me parece que este archivo no deberían estar aquí 👀

2023-03-21 14:53 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/logo.png:Zone.Identifier
Este tampoco 👀

2023-03-21 15:43 UTC, Andrssnsdc commented on github-profiles/andrssnsdc-4799/header.jpg:Zone.Identifier
hola Mau muchas gracias por tus observaciones y comentarios si estos archivos son necesarios por que hacen parte del diseño del html

2023-03-21 16:14 UTC, MauBedoya commented on github-profiles/andrssnsdc-4799/header.jpg:Zone.Identifier
por lo que veo utilizas el archivo `header.jpg` en tu CSS pero no encuentro donde están los que tiene la terminación `.jpg:Zone.Identifier`, probaste a quitar estos últimos por un momento de la carpeta y ver si tus imágenes cargan normalmente?

2023-03-22 14:06 UTC, Andrssnsdc commented on github-profiles/andrssnsdc-4799/header.jpg:Zone.Identifier
los otros estan directamente en el html si al quitarlos no cargan las imagenes

2023-03-28 15:43 UTC, Alexisdc5 approved these changes
con las sugerencias recibidas quedaria correcto el trabajo, Buena suerte

2023-03-30 21:58 UTC, merged