Ejercicio
undefined-academy/semana-1 pull request #159
Opened 2023-03-06 19:56 UTC by MartinRodrigoVargas

# Como hacer un Fork y crear un Pull Request

## Pasos
1. Entramos a la URL *https://github.com/undefined-academy/semana-1/* y creamos un **Fork** del repositorio.
2. Clonamos nuestro nuevo repositorio forked a través de la **terminal** utilizando el comando:
```bash
git clone git@github.com:MartinRodrigoVargas/semana-1.git
```
3. Entramos a la carpeta y subcarpeta clonadas con el comando:
```bash
cd Code/semana-1/github-profiles/
```
4. Creamos una nueva rama y la nombramos con el comando:
```bash
git checkout -b "Ejercicio"
```
5. Crearemos un archivo .md que se llamara como nuestro nombre de usuario de **Discord**. 
Su contenido será el mismo que el de nuestro archivo README.md (Ejercicio de la clase-1) y también colocaremos un link a nuestro perfil de GitHub.
6. Realizaremos nuestro commit utilizando los comandos:
```bash
git add --all
``` 
 seguido de
```bash
git commit -m "Ejercicio-2"
```
7.  Para realizar el Pull Request crearemos nuestra rama local (Ejercicios) en el repositorio remoto, escribiendo lo siguiente
```bash
git push origin "Ejercicio"
```
8. Volvemos a nuestro repositorio forked dentro de GitHub y cambiaremos la rama **main** por la rama **Ejercicio**. Hacemos click en **Contribute**, el cual nos ofrecera la opcion de abrir un **pull request**.
9. Aqui deberiamos de escribir un resumen de los cambios realizados, pero en esta ocasion hemos colocado la TAREA 😂

2023-03-09 20:47 UTC, MauBedoya requested changes

2023-03-09 20:47 UTC, MauBedoya commented on github-profiles/MartinVargas-6047/README.md
> +https://github.com/MartinRodrigoVargas
como detalle, también podrías usar: 
`[Github personal profile](https://github.com/MartinRodrigoVargas)` 

para que se pueda ver de esta manera: 
[Github personal profile](https://github.com/MartinRodrigoVargas)

2023-03-09 20:51 UTC, MauBedoya requested changes
Me parece que el archivo html debe contener lo que pusimos en el archivo `README.md` de nuestro perfil, los pasos de como se realizaron las prácticas eran para el comentario del Pull Request.

2023-03-09 21:50 UTC, MartinRodrigoVargas commented on github-profiles/MartinVargas-6047/README.md
> +https://github.com/MartinRodrigoVargas
Gracias por el feedback MauBedoya, acabo de implementar los cambios en el markdown.

2023-03-09 22:15 UTC, MauBedoya approved these changes
me parece que está completo 👍

2023-03-17 16:04 UTC, Alexis033 approved these changes
Buen trabajo, veo todo lo que se pidió.

2023-03-28 15:49 UTC, merged