GitHub profile in .md file
undefined-academy/semana-1 pull request #16
Opened 2023-03-03 15:58 UTC by lucianogarriga

# Ejercicio Clase 2: "Git, Control de Versiones"

Me resultó muy útil realizar este ejercicio, ya que puse en práctica conocimientos anteriores, tras haberlos aprendido en cursos previos de *desarrollo web frontend*.

Lo más importante, es que aprendí conceptos nuevos como hacer **"fork"** de un repositorio, y hacer **"pull requests"**. 

No se me dificultó mucho, ya que Guillermo brindó unos _links_ extras con guías para aprender cómo realizar estas acciones a través del controlador de versiones.

# El proceso para resolver este ejercicio fue el siguiente:

1. Hacer un fork del repositorio `https://github.com/undefined-academy/semana-1`.
2. Clonar mi repositorio `forked` en mi carpeta **HOME**.
3. Agregar un archivo markdown de mi [perfil de GitHub](https://github.com/lucianogarriga) , dentro de la carpeta `github-profiles`. Asimismo, el nombre del archivo debe ser mi usuario de Discord + el tag numérico.
4. Incluir en el archivo .md un link que los pueda llevar a mi  [perfil de GitHub](https://github.com/lucianogarriga).
5.  Hacer un commit del archivo.
6.  Ir al repositorio del paso `1.` y crear mi primer `pull request`.
7. Realizar una descripción de mi `pull request` sobre mi proceso de resolver el ejercicio dentro de este archivo **markdown**.

2023-03-09 14:30 UTC, alexcaicedo commented
Hola Luciano! Buen trabajo hasta el momento. 👍 

Solo recuerda poner el archivo README.md con una descripción de tu perfil dentro de la carpeta que lleva tu nombre de usuario y código Discord.

Feliz dia!

2023-03-09 20:36 UTC, r4vc31 requested changes
La estructura de carpetas no es correcta, la carpeta con su nombre de usuario debe estar dentro del directorio github-profiles/

2023-03-10 00:31 UTC, lucianogarriga commented
Gracias por tu review Ronald! No me había quedado claro esa cuestión de organizar la carpeta con mi nombre dentro de github-profiles. Acabo de modificarlo!

2023-03-12 21:31 UTC, Maurofavre approved these changes
Muy buen trabajo Luciano. Cumple con todo los requisitos. A seguir por este camino .

2023-03-15 01:00 UTC, oconsl approved these changes
### Review:

- Me encantó tu trabajo, se ve ordenado y con buenas practicas.
- Muy bien con el html semántico.

2023-03-15 02:04 UTC, adjsvar approved these changes
Tu PR muy bueno Luciano, las cosas que encontre eran minimas, hiciste un excelente trabajo amigo.

2023-03-15 02:52 UTC, lucianogarriga commented on github-profiles/lucianogarriga-1264/index.html
> +    <nav>
Excelentes tips Adrian! Estoy configurando la pagina desde el repo local y los cambios suman bastante, muchas gracias!! En breve los subo al remoto!

2023-03-15 02:54 UTC, lucianogarriga commented on github-profiles/lucianogarriga-1264/main.css
> +  border-radius: 10px;
Un espectáculo ese detalle Adrián, no había considerado ese "delay" al dejar el border-radius en el :hover. Gracias por tomarte el tiempo en darme tu feedback! La verdad es muy valioso

2023-03-20 14:04 UTC, merged