Romeo_Zulu-8290
undefined-academy/semana-1 pull request #160
Opened 2023-03-06 20:12 UTC by Romeo-Zulu

# Pasos de la Actividad:

1. Se realizo un Fork del repositorio git@github.com:undefined-academy/semana-1.git
2.  Se clono dicho repositorio.
3.  Se creo un archivo en la carpeta github-profiles llamado Romeo_Zulu-8290.md (usuario Discord).
4.  Se creo un link al profile personal de github en archivo .md y se realizo commit.
5.  Se realizo un pull request al repositorio de git@github.com:undefined-academy/semana-1.git

***
Att. **Jorge Ariet**.

2023-03-09 16:19 UTC, dfm555 requested changes

2023-03-09 16:19 UTC, dfm555 commented on github-profiles/Romeo_Zulu-8290/main.css
> +    font-family: "Roboto", "Helvetica", "Arial", sans-serif;
Tienes varias etiquetas body en el archivo, entiendo que quieras practicar el comportamiento de cascada, pero revisa que propiedades tienes repetidas, ejemplo:
` font-family`
 
 y las reemplazas en el body que tienes en la parte superior, para tener más consistencia

2023-03-09 16:56 UTC, Romeo-Zulu commented on github-profiles/Romeo_Zulu-8290/main.css
> +}
ok, gracias por las sugerencias! seran corregidas de inmediato!

2023-03-09 17:45 UTC, Romeo-Zulu commented on github-profiles/Romeo_Zulu-8290/main.css
> +}
Se realizaron las correcciones sugeridas. 
En espera de nuevos Feedback.
Gracias.

2023-03-09 23:49 UTC, IDKJesBen commented on github-profiles/Romeo_Zulu-8290/main.css
> +}
Excelente! Sigue así!

2023-03-10 14:59 UTC, dfm555 requested changes

2023-03-10 14:59 UTC, dfm555 commented on github-profiles/Romeo_Zulu-8290/main.css
> +}
@Romeo-Zulu por qué eliminaste esta línea?
`@import 'https://fonts.googleapis.com/css?family=Roboto:300,400,500';`

2023-03-10 17:24 UTC, Romeo-Zulu commented
Se agrego la linea @import faltante. Gracias <a href="https://github.com/dfm555">dfm555</a>

2023-03-10 19:18 UTC, dfm555 approved these changes

2023-03-13 16:10 UTC, IDKJesBen approved these changes

2023-03-13 16:17 UTC, merged