add Profile YilmerG
undefined-academy/semana-1 pull request #17
Opened 2023-03-03 16:06 UTC by yrguativa

Hola comunidad, el proceso que realice:

1. Actualice mi perfil ya que lo tenia pero estaba desactualizado.
2. Las tareas de la semana y los ejercicios de investigación esta en otro repositorio pero se puede ver [aquí](https://github.com/yrguativa/BootCamp-Undefined-Academy/blob/main/Class.md).
3. Realice un Fork y agregué un archivo con el nombre de Discord.
4. Realice el Pull Request.

Gracias por su ayuda.

2023-03-09 20:59 UTC, olezdev commented
Hola, el punto 2 lo realizaría en este mismo pr, para no tenerlo en otro repositorio y se puedan ver los commit de cada clase.

2023-03-09 21:01 UTC, olezdev reviewed
Hola, el punto 2 que comentas en la descripción del pull request lo realizaría en este mismo pr, para no tenerlo en otro repositorio y se puedan ver los commits de cada clase.

2023-03-14 02:45 UTC, yrguativa commented
Ya agregué el punto 2 en el archivo .md

2023-03-26 20:43 UTC, glrodasz requested changes

2023-03-26 20:43 UTC, glrodasz commented on github-profiles/YilmerG-4850.md
Este archivo no debe ir.

2023-03-26 20:43 UTC, glrodasz commented on YilmerG-4850/README.md
Esta carpeta debe ir adentro de **github-profiles**

2023-03-29 15:28 UTC, merged