First Pull Request
undefined-academy/semana-1 pull request #172
Opened 2023-03-06 21:46 UTC by Wannmi

# Proceso para resolver el ejercicio 🚧

1. Realice una _búsqueda_ sobre el *comando* `fork`.
2. Hice el **fork** del repositorio.
3. Cree un _directorio_ para almacenar el *Proyecto*.
4. **Clone** el repositorio forkeado.
5. _Moví y renombre_ el archivo con extension ".md" de la primer clase.
6. Hice la modificación al archivo ".md".
7. Realice un _commit_ para luego realizar el _push_.
8. Realice una _búsqueda_ sobre el **Pull Request**.
9. _Este paso seria futuro_. Le di al botón *`Create pull request`* 😂

# Experiencia ☕

* Cuando realice la búsqueda del comando `fork` y lo comprendí, creo haber tenido una **primera impresión** de a donde apunta el _ejercicio_ de esta clase, lo cual me dio un **impulso extra** para hacerlo. 🦾
* Tuve _dificultades_ con los directorios al mover el archivo, creo que es solo cuestión de juntar mas **experiencia** con la _consola_ ⏏

2023-03-12 00:28 UTC, ernzxr requested changes
En general vi todo bien, con cambios menores por retocar. 

HTML se utiliza principalmente para estructurar contenido y CSS para estilizar elementos, mi opinion es que se podria agregar mas codigo CSS, mas que nada como practica.

2023-03-12 00:28 UTC, ernzxr commented on github-profiles/DameAsado-6873/README.md
> +|--------|:------------------------:|-----------------------------------:|
Buenas!, la tabla esta muy bien formateada. Se podria mejorar quitando los **:** y reemplazandolos por espacios.

2023-03-12 00:28 UTC, ernzxr commented on github-profiles/DameAsado-6873/README.md
> +Busca las carpetas que contengan una palabra:
Sugerencia:

Te invito a probar agregar los alias en una tabla, es un buen ejercicio para probar las funciones del markdown y que ademas va a quedar muy bueno en html con el ejercicio de css ;)

2023-03-12 00:28 UTC, ernzxr commented on github-profiles/DameAsado-6873/css/main.css
> +}
Otra sugerencia!

Te invito a darle mas formato a la tabla, podes empezar por agregar el codigo `border-collapse`, eso te va a hacer una sola linea para los bordes, a partir de ahi podes probar darle algun color al encabezado de la tabla por ejemplo, y jugar con css, es un buen elemento para explorar.

2023-03-12 00:28 UTC, ernzxr commented on github-profiles/DameAsado-6873/index.html
> +        🌱 Me gustan las plantas. <br>
Es opcional creo yo, puede confirmar algun mentor, pero se podria cambiar el tag <br> para modificar los espacios por codigo en css, como por ejemplo el padding.

2023-03-12 18:49 UTC, Wannmi commented on github-profiles/DameAsado-6873/README.md
> +Busca las carpetas que contengan una palabra:
En principio había puesto los alias en formato de tabla pero tenia inconveniente con el carácter | del primer alias, ya que me lo tomaba como una columna cortándome el código. Se te ocurre algún método para solucionar esto? Probé varias cosas y no me funcionaron.

2023-03-12 23:36 UTC, ernzxr commented on github-profiles/DameAsado-6873/README.md
> +Busca las carpetas que contengan una palabra:
Utilizando `\` se soluciona el problema , te dejo el articulo donde lo encontre:
[https://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html](https://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html)

2023-03-14 17:56 UTC, Wannmi commented on github-profiles/DameAsado-6873/README.md
> +|--------|:------------------------:|-----------------------------------:|
Uso los : para centrar el contenido de la columna. Cuando reemplazo por espacio, en el preview de VSC no me lo muestra centrado.

2023-03-16 23:53 UTC, ernzxr approved these changes

2023-03-17 18:31 UTC, dfm555 commented on github-profiles/DameAsado-6873/index.html
> +        🌱 Me gustan las plantas. <br>
@ernzxr esos espacios son por la identation que agrega el vscode

2023-03-17 21:27 UTC, Wannmi commented on github-profiles/DameAsado-6873/index.html
> +        🌱 Me gustan las plantas. <br>
Siendo honesto, en este caso no entiendo a que se refieren. Me podrían explicar un poco mas?

2023-03-21 04:09 UTC, Wannmi commented
Guille, acá tengo el problema con el .vscode @glrodasz

2023-03-21 04:18 UTC, glrodasz commented
@dfm555 Le podemos ayudar a @Wannmi para que en este PR se agregué el `.vscode` al gitignore y se remueva del repo?

2023-03-21 14:40 UTC, dfm555 approved these changes
Buen trabajo

2023-03-21 14:40 UTC, merged