Use of MD
undefined-academy/semana-1 pull request #177
Opened 2023-03-06 22:58 UTC by JoeOsG

2023-03-06 23:02 UTC, JoeOsG commented
# PR for bootcamp

Here the steps I followed
- Clone the repository semana1
- Created markdown file wiith my user name
- Edited the file with my github profile
- Saved file
- Created fork of the repository
- Pushed the changes
- Created PR

2023-03-15 20:42 UTC, dfm555 requested changes

2023-03-15 20:42 UTC, dfm555 commented on .vite/deps_temp/package.json
Elimina este folder.

Manten esta configuración en tu  repositorio local

2023-03-15 20:48 UTC, JoeOsG commented on .vite/deps_temp/package.json
Gracias Fernando, listo.

2023-03-15 20:52 UTC, dfm555 requested changes

2023-03-15 20:52 UTC, dfm555 commented on .gitignore
Resuelve los conflictos

el .gitignore del fork ya tiene 

.vite

2023-03-15 21:01 UTC, JoeOsG commented on .gitignore
Lo resolví listo, aquí directamente en GitHub.

2023-03-15 21:10 UTC, dfm555 requested changes

2023-03-15 21:10 UTC, dfm555 commented on .gitignore
@JoeOsG 

la línea debería quedar

.vite/

2023-03-15 21:14 UTC, dfm555 requested changes

2023-03-15 21:14 UTC, dfm555 commented on github-profiles/JoeOs-8843/index.css
> +header {
Agrupo las propiedades en una sola etiqueta header

Tienes dos

2023-03-15 21:20 UTC, dfm555 approved these changes
Buen trabajo 🦾

2023-03-21 16:52 UTC, dfm555 requested changes
@JoeOsG resuelve los conflictos por favor

2023-03-21 17:43 UTC, dfm555 approved these changes

2023-03-21 17:55 UTC, lllariogonzalez approved these changes
:octocat:

2023-03-21 17:59 UTC, merged