Bringing Nanpipe's profile info
undefined-academy/semana-1 pull request #193
Opened 2023-03-07 01:36 UTC by nanpipe

To be completely honest, I pushed it from VSCode before I read that I had to do a Pull Request which I'm doing right now but I have no idea if it is going to succeed.

As for steps, literally just followed a screenshot I took to the homework, though I didn't follow it so well since I ended up Pushing rather than Pulling

2023-03-07 02:31 UTC, nanpipe commented
Pulling again?

2023-03-07 03:46 UTC, nanpipe commented
Idk... finding out if I have to push or pull...

2023-03-10 04:09 UTC, nobody-redhawk requested changes
# Tareas que falta realizar

1. Crear un archivo css en su defecto `styles.css` en la carpeta `IngFelipeSolarte-34**`  para estilizar el articho `index.html` de tu perfil siguiendo el tutorial de ["Diseño Web en 4 minutos"](https://jgthms.com/web-design-in-4-minutes) de Jeremy Thomas.
2. Finalmente hacer `commit` y `push.`
3. Éxitos...

2023-03-10 04:10 UTC, nanpipe commented
> # Tareas que falta realizar
> 1. Crear un archivo css en su defecto `styles.css` en la carpeta `IngFelipeSolarte-34**`  para estilizar el articho `index.html` de tu perfil siguiendo el tutorial de ["Diseño Web en 4 minutos"](https://jgthms.com/web-design-in-4-minutes) de Jeremy Thomas.
> 2. Finalmente hacer `commit` y `push.`
> 3. Éxitos...

2023-03-10 04:14 UTC, nanpipe commented
> # Tareas que falta realizar
> 1. Crear un archivo css en su defecto `styles.css` en la carpeta `IngFelipeSolarte-34**`  para estilizar el articho `index.html` de tu perfil siguiendo el tutorial de ["Diseño Web en 4 minutos"](https://jgthms.com/web-design-in-4-minutes) de Jeremy Thomas.
> 2. Finalmente hacer `commit` y `push.`
> 3. Éxitos...

Muchas gracias, trabajaré en ello.

2023-03-11 15:32 UTC, nobody-redhawk approved these changes
Está todo lo requerido en las actividades de los ejercicios.

2023-03-21 02:27 UTC, jesab3l approved these changes
Se ve que esta todo bien y con los ejercicios concluidos

2023-03-21 02:39 UTC, giovanyosorio approved these changes

2023-03-22 13:02 UTC, merged