Ejercicio Clase 2 - Fede.GC#5692
undefined-academy/semana-1 pull request #195
Opened 2023-03-07 02:00 UTC by fedegomezc

1. Realicé fork del repositorio undefined-academy/semana-1
2. En la terminal de Ubuntu me ubiqué en mi carpeta Home y cloné el repositorio.
3. En la terminal cambié el directorio a la carpeta github-profiles del repositorio y cree un archivo llamado Fede.GC-5692
4. Abrí el archivo en VS Code y pegué el contenido de mi perfil de Github.
5. Realicé commit y push de los cambios.
6. Busqué como se hace un Pull Request, ya que no sabía.
7. Creé una nueva rama y luego en mi repo busqué para hacer pull request.

2023-03-09 18:09 UTC, leviusr reviewed
hola amigo, feliz día, me pase por acá y me fije que a tu readme.md le falta colocar los alias, agrégalos saludos.

2023-03-09 18:41 UTC, aabrazo requested changes

2023-03-09 18:41 UTC, aabrazo commented on github-profiles/Fede.GC-5692/README.MD
> +----------------------------------------------
Faltaría añadir una tabla en con al menos 5 comandos de la Terminal que hayas aprendido, de forma que tenga nombre del comando y descripción en columnas separadas y una sección con al menos 2 comandos alias que te parezcan útiles incluyendo columna de descripción.

2023-03-09 20:11 UTC, fedegomezc commented
> hola amigo, feliz día, me pase por acá y me fije que a tu readme.md le falta colocar los alias, agrégalos saludos.

>Hola. gracias. Ahí lo agregué!

2023-03-09 20:12 UTC, fedegomezc commented on github-profiles/Fede.GC-5692/README.MD
> +----------------------------------------------
Gracias. Ahí agregué ambos. Saludos!

2023-03-09 20:13 UTC, aabrazo approved these changes
Genial, buen trabajo!

2023-03-10 00:28 UTC, leviusr approved these changes
Genial, gracias por agregar los cambios, dejo mi Approve, saludos

2023-03-14 09:52 UTC, merged