Adding my profile  README
undefined-academy/semana-1 pull request #200
Opened 2023-03-07 02:30 UTC by darioernesto-roca

Creating the pull request for my GitHub profile README

2023-03-23 16:07 UTC, dfm555 requested changes
@darioernesto-roca 

Revisa el readme del repositorio de la [semana 1 ](https://github.com/undefined-academy/semana-1), tienes los ejercicios incompletos.

Revisa tu estructura de carpetas todos tus archivos deben ir dentro de github-profiles/

2023-03-23 16:07 UTC, dfm555 commented on Dario Ernesto Roca-7375/index.html
> +    <style>
Mueve estos estilos a un archivo aparte

2023-03-23 17:28 UTC, darioernesto-roca commented on Dario Ernesto Roca-7375/index.html
> +    <style>
Hola Fernando, realicé ajustes en archivo markdown agregándole las tablas con los comandos y cambiándole algunas etiquetas. Tambiés pasé el código CSS a un archivo aparte. Muchas gracias por tu revisión

2023-03-26 23:52 UTC, taliixer approved these changes
Me gusta tu estructura en la hoja de vida, Great Job

2023-03-26 23:54 UTC, taliixer commented
Para las próximas semanas te recomiendo llevar un registro de tu proceso, cada que hagas un commit pon un comentario donde hagas una breve explicación de lo que hiciste en ese commit y si tuviste algún desafío como lo solucionaste

2023-03-27 16:33 UTC, merged