Ejercicio 2 📚
undefined-academy/semana-1 pull request #206
Opened 2023-03-07 03:04 UTC by Cristhian-Medina

## Pasos

[x] Crear un fork del repositorio “undefined-academy/semana-1”.

[x] Clonar nuestro repositorio al PC usando la terminal.
[x] Crear una nueva branch y nombrarla “ejercicio”.
[x] Ingresar a la ruta ./semana-1/github-profiles/ .
[x] Crear un archivo con el nombre de usuario de Discord y la extensión .md.
[x] Agregar algo de información al archivo.
[x] Agregar los cambios al stage de git.
[x] Hacer un commit con el mensaje “Ejercicio 2”.
[x] Hacer un push al repositorio remoto en github.
[x] Hacer un PR al repositorio original “undefined-academy/semana-1”.

2023-03-09 20:27 UTC, yulsdev requested changes
El nombre de la carpeta deberia ser: CristianMedina-7460 como se indica en la nota de pie del paso 2 del ejercicio 2. Y esta carpeta tiene que estar dentro de la carpeta github-profiles 

La carpeta tiene que estar dentro de la carpeta

2023-03-09 20:27 UTC, yulsdev commented on CristhianMedina#7460/README.md
> +# Soy Cristhian Medina
El texto/contenido (ojo estoy diciendo texto), debe ser similar al archivo index.html. Ya que según el ejercicio 3, el archivo index.html esta basado en el archivo Markdown de nuestro perfil.

2023-03-20 00:57 UTC, Cristhian-Medina commented on CristhianMedina#7460/README.md
> +# Soy Cristhian Medina
Modifique la información porque era muy simple tener solo mis redes sociales de contacto en el archivo, así que le agregue más contenido para que se vea mejor la presentación.

2023-03-23 12:24 UTC, yulsdev requested changes
Todo Ok, pero veo que te falta el Ejercicio 1 Semana 1,  te sugiero que lo  incluyas en el archivo README.md, para que se tenga constancia de que hiciste el Ejercicio

2023-03-23 22:06 UTC, JoeOsG approved these changes
### Bien.

2023-03-24 13:06 UTC, yulsdev commented
Como te dije anteriormente, te falta el ejercicio 1 semana 1. Si lo hiciste aparte en otro repositorio, puedes mandarme el enlace para revisarlo y  tener constancia de que lo realizaste.

2023-03-26 15:18 UTC, yulsdev requested changes
Todo Ok, solo ese detalle de la alineacion de las tablas.

2023-03-26 15:18 UTC, yulsdev commented on github-profiles/CristhianMedina-7460/README.md
> +| Comando               | Descripción |
Es recomendable tener las  tablas alineadas (columnas) en el documento fuente Markdown. Aunque no se note al ser visualizado, el documento fuente  tambien debe verse ordenado.

2023-03-29 01:21 UTC, Cristhian-Medina reviewed
All ready

2023-03-29 02:10 UTC, yulsdev approved these changes
Todo Ok, felicidades

2023-04-05 14:08 UTC, merged