mi perfil markdown
undefined-academy/semana-1 pull request #214
Opened 2023-03-07 04:37 UTC by MelisaSG

## Todo verde 🌱

#### Markdown parece sencillo pero hay cosas que no encontré como hacer, como dejar varios renglones entre párrafo y párrafo.

#### Y GitHub, si bien lo entiendo superficialmente, cuando lo quiero razonar el concepto se me escapa. Mas que nada la parte _colaborativa_.

#### Tuve una demora para subir el proyecto porque clone mi repositorio con el url https, lo que hizo que me pidiera una clave que no tenia. Busque ayuda en el discord y lei a una chica que le habia pasado lo mismo y lo soluciono cambiando el URL del repositorio a traves de la terminal. 

#### Y lo intenté, realmente lo intenté. Pero la terminal me pedia ciertos comandos extras para poder editar la url y no logré dar con la tecla correcta, incluso buscando información en internet. Decidí borrar todo y arrancar  de nuevo. Mi objetivo es tratar de tener mas paciencia para dar con una solucion real la próxima vez que me pase algo similar 😓

2023-03-09 09:18 UTC, aitorias requested changes
El README del perfil muy sencillito pero bien ordenado y estructurado! 😃

2023-03-09 09:18 UTC, aitorias commented on MelisaSG-5167/README.md
> +| man cp  | imprime una manual |
Sugerencia: Puedes añadir comillas simples ( `ejemplo`) para que aparezca 'modo código' y quede más lindo! 😄

2023-03-11 01:57 UTC, MelisaSG commented on MelisaSG-5167/README.md
> +| man cp  | imprime una manual |
Gracias por el comentario y la sugerencia 😄😄

2023-03-12 04:07 UTC, ernzxr requested changes
Hola!

En general vi todo muy bien, se puede mejorar el indentado del `index.html` para que este mas prolijo.

Estarian faltando las tablas del `README.md` en el `index.html`!

2023-03-12 04:07 UTC, ernzxr commented on MelisaSG-5167/README.md
> +```
Hola!

Te sugiero agregar los alias a una tabla, es una buena practica para usar mas funcionabilidades del markdown.

Otra cosa, esto me paso a mi tambien, las triple ` se deben utilizar para cuando se quieran escribir mas de 1 linea de codigo, si te fijas en la preview de tu markdown, vas a notar que hay como espacios alrededor del codigo, eso es porque la comilla invertida esta tomando como codigo los espacios de linea.

2023-03-12 04:07 UTC, ernzxr commented on MelisaSG-5167/index.html
> +
Agregate las tablas del markdown, asi les das estilo con CSS.

2023-03-20 22:42 UTC, MelisaSG commented on MelisaSG-5167/README.md
> +```
hola! gracias por pasarte por aca. Realice las correcciones sugeridas.

2023-03-20 23:24 UTC, aitorias approved these changes

2023-03-20 23:27 UTC, aitorias commented on MelisaSG-5167/index.html
Están geniales tanto la fuente como los colores que utilizaste! 😄 

Únicamente añadiría el contenido de las actividades del curso que tienes como Markdown en el archivo `README.md` a etiquetas en HTML en `index.html`, justo de bajo de tu sección de 'cursos'.

2023-03-20 23:32 UTC, aitorias commented on MelisaSG-5167/style.css
Cómo humilde consejo para optimizar tu archivo css, únicamente intentaría no repetir líneas de código y en lugar de usar ids específicas de los elementos, las añadiría en **clases**, es decir:

En lugar de repetir atributos y valores haciendo uso de los identificadores, crearía clases genéricas que comparten los elementos:

```css
.mx-auto {
    margin: 0 auto;
}

.max-w-50em {
    max-width: 50em;
}
```

Y añadiría dichas clases a los elementos en el html:

```html
<div id="presentacion" class="mx-auto max-w-50em">[...]
```

Mejor utilizar clases que identificadores en css, son más reusables y te permiten ahorrar líneas de código y, por lo tanto, que el archivo contenga menos kB y mejor tiempo de carga! 😋  Que normalmente los archivos css contienen más líneas de código repetidas y son mucho más tediosos de leer.

2023-03-20 23:34 UTC, aitorias requested changes
Solamente te faltaría adaptar el contenido realizado en clase del `README.md` a etiquetas HTML en el `index.html`. Por lo demás genial! Te puse esto mismo como comentario y una pequeña sugerencia para el css. Pero muy lindo! 😋

2023-04-25 19:34 UTC, closed without merging