Perfil de GitHub
undefined-academy/semana-1 pull request #216
Opened 2023-03-07 05:25 UTC by Alexisdc5

### Hola
* El Proceso para resolver este ejercicio resulto en principio complicado 🤔, pero realizando una **revisión de los videos** pude lograr terminarlo.🤗

2023-03-15 01:12 UTC, oconsl requested changes
### Muy buen trabajo! 

- Hay un par de recomendaciones y cambios menores que te indiqué. 
- Como recomendación extra es que explique un poco más detallado los pasos para hacer una PR.

2023-03-15 01:12 UTC, oconsl commented on github-profiles/alexis87-6482.md
Deberías borrar este archivo de tu repositorio local, así cuando hagas push la PR se actualice y este archivo ya no se suba aquí.

2023-03-15 01:12 UTC, oconsl commented on github-profiles/alexis87-6482/README.md
> +https://github.com/Alexisdc5
Podes utilizar markdown para poner un link: 

1. Colocas el nombre del link entre corchetes [ ]
2. Colocas la URL dentro de parensis a la izquierda de los corchetes ( )

> Ejemplo: [ir a google](https://www.google.com)

2023-03-15 01:12 UTC, oconsl commented on github-profiles/alexis87-6482/img prog.jpg:Zone.Identifier
Este archivo lo podrías eliminar de tu repositorio local.

2023-03-15 01:12 UTC, oconsl commented on github-profiles/alexis87-6482/main.css
> +.alias li {
Te recomiendo para mantener un orden claro, poner los selectores por clase de CSS luego de todos los selectores por etiqueta. En el caso de tu CSS podrías poner estos estilos al final del archivo.

2023-03-16 21:26 UTC, Alexisdc5 commented on github-profiles/alexis87-6482/main.css
> +.alias li {
Muchas gracias por la revisión, ya realice los cambios sugeridos.

2023-03-18 00:00 UTC, oconsl approved these changes
Todo se ve bien ahora. 😊

2023-03-20 19:32 UTC, Vene15 approved these changes
Buen trabajo, ya te sugirieron algunas cosas y ya realizaste los cambios!! Todo se ve bien ahora!

2023-08-12 01:57 UTC, closed without merging