Mi perfil de Github
undefined-academy/semana-1 pull request #222
Opened 2023-03-07 07:25 UTC by Ssam55

## Se logró

### Me costó trabajo la parte de VS Code, originalmente quería hacerlo todo en la terminal e iba a crear una nueva carpeta que se llamara github-profiles, hasta que me dí cuenta de que ya existía esa carpeta al haber hecho el fork.

### Me gustó usar VS Code, facilita mucho el tema, no sabía muy bien cómo iba a abrir el archivo desde la terminal para editar, pero buee....

:)

2023-03-15 04:17 UTC, OrcaCl requested changes

2023-03-15 04:17 UTC, OrcaCl commented on github-profiles/SamGH-6759/index.html
> +Hola, soy Sam González 👋
Hola Sam.
Acá tienes un error. La información fuera de tags que escribas en <head>no se van a visualizar en la página. Sólo se ve lo que está dentro de <body>.
Además, el link debes usarlo con el tag correcto. Ejemplo <a href="link">Texto del link</a>

2023-03-15 04:17 UTC, OrcaCl commented on github-profiles/SamGH-6759/index.html
> +    <h5>Algunos comandos interesantes que he aprendido son:
Las etiquetas H, de H1 a H6 son para títulos. Enunciados cortos que representan lo que se va a hablar después usando párrafos. A menos que sea una decisión decorativa, te sugiero usar un sólo título y seguir la explicación usando párrafos.

2023-03-15 04:17 UTC, OrcaCl commented on github-profiles/SamGH-6759/index.html
> +    |whoami|Devuelve el usuario actual| </h5>
Si bien es cierto que en Markdown puedes usar etiquetas HTML, en HTML el markdown solo no funciona.
Guillermo no habló de tablas, pero puedes leer el siguiente link para aprender tablas facilito:  [HTML Tables](https://www.w3schools.com/html/html_tables.asp)

2023-03-15 04:17 UTC, OrcaCl commented on github-profiles/SamGH-6759/index.html
> +    |alias rm="trash"|Mandar a papelera archivos|</h6>
Acá lo mismo. Debes usar una tabla para mostrar esta info.
Puedes leer el siguiente link para aprender tablas facilito:  [HTML Tables](https://www.w3schools.com/html/html_tables.asp)

2023-03-15 04:17 UTC, OrcaCl commented on github-profiles/SamGH-6759/index.html
> +    <h9>Y muera el mal gobierno! 😜</h9>
No existen H7, H8 y H9.
Usa mejor `<p>Este es un campo de texto</p>`

2023-03-27 07:17 UTC, Ssam55 commented on github-profiles/SamGH-6759/index.html
> +Hola, soy Sam González 👋
Ok, correcto!! :)

2023-03-27 07:17 UTC, Ssam55 commented on github-profiles/SamGH-6759/index.html
> +    |whoami|Devuelve el usuario actual| </h5>
Ok, lo checo! Gracias

2023-03-27 07:17 UTC, Ssam55 commented on github-profiles/SamGH-6759/index.html
> +    <h9>Y muera el mal gobierno! 😜</h9>
Ok!!

2023-03-27 08:26 UTC, Ssam55 commented on github-profiles/SamGH-6759/index.html
> +    |whoami|Devuelve el usuario actual| </h5>
Aquí el link de las actualizaciones

https://github.com/Ssam55/semana-1/commit/e03d19490d8b03f4869e715fecf6d786b716a5c0

2023-03-27 19:51 UTC, Ssam55 commented on github-profiles/SamGH-6759/index.html
> +<html lang="estoy">
Así lo marcó en la terminal vsc, pero se visualiza bien, pero lo sustituyo

2023-07-18 20:42 UTC, closed without merging