Mi primer commit
undefined-academy/semana-1 pull request #226
Opened 2023-03-07 13:06 UTC by brunom033

## Proceso de Fork y Pull request
Me pareció un ejercicio bastante **interesante** ya que refleja muy bien la colaboración en proyectos.

**Muchas gracias** Guille por el bootcamp.
Saludos.

2023-03-15 21:55 UTC, dfm555 requested changes

2023-03-15 21:55 UTC, dfm555 commented on github-profiles/Bruno33-5772/main.css
> +/* header a {
@brunom033 eliminar este código comentado.

2023-03-15 23:52 UTC, brunom033 commented on github-profiles/Bruno33-5772/main.css
> +/* header a {
Listo, gracias!

2023-03-15 23:54 UTC, dfm555 approved these changes
Buen trabajo

2023-03-21 13:23 UTC, Andrssnsdc approved these changes
Hola Bruno su ejercicio esta muy bien mi unica sugerencia seria que alinee la tabla en su markdown para que sea mas legible viendo el codigo

2023-03-21 16:42 UTC, merged