Primer commit semana1
undefined-academy/semana-1 pull request #227
Opened 2023-03-07 13:16 UTC by DenisseMonster

1. creo fork
2. creacion carpeta con nombre de usuario Discord
3. hacer perfil html y guardar los archivos en las carpetas solicitadas

2023-03-16 21:59 UTC, marcospenalosa requested changes
Es necesario mover archivos dentro de la carpeta del usuario.

2023-03-16 21:59 UTC, marcospenalosa commented on denisse-9285.md
El archivo *.**md** tiene que estar dentro de la carpeta de tu usuario (denisse-9285) no puede estar fuera.

2023-03-26 21:02 UTC, glrodasz requested changes

2023-03-26 21:02 UTC, glrodasz commented on denisse-9285/github.Identifier
Eliminemos este archivo.

2023-04-03 10:27 UTC, DenisseMonster commented
Ya hice las modificaciones solicitadas, gracias gente <3

2023-04-03 19:38 UTC, merged