Agregando mi archivo de markdown de GitHub
undefined-academy/semana-1 pull request #23
Opened 2023-03-03 18:11 UTC by pablotiny

# Proceso

1. Cree mi cuenta de GitHub.
2. Genere mi repositorio especial.
3. Crear una carpeta en mi computadora en la que agregue un readme y coloque mi curriculum vitae y las tablas.
4. Agregue el remoto de mi repositorio remoto.
5. Agregue el readme al Staging Area.
6. Realice el commit y el push.
7. Hice un fork del repositorio de la semana 1.
8. Clone en mi PC y agregue el archivo Markdown a la carpeta github-profiles.
9. Agregue los cambios al Staging Area y efectúe el commit.
10. Ejecute el push al repositorio remoto.
11. Por último realicé el pull request.

2023-03-15 05:19 UTC, oabm77 requested changes
Falta crear la parte de creación del perfil usando HTML  y CSS

2023-03-15 05:19 UTC, oabm77 commented on github-profiles/williampa-6490.md
> +Tecnico en Mecanica y Electricista.
podías haber ampliado un poco más la información de tu perfil.
También usar otras herramientas markdown como las viñetas o los enlaces

2023-03-26 20:48 UTC, glrodasz requested changes

2023-03-26 20:48 UTC, glrodasz commented on github-profiles/williampa-6490.md
Esto debe ir dentro de una carpeta con tu nombre de Discord.

2023-04-02 19:53 UTC, closed without merging