Commit perfil GitHub
undefined-academy/semana-1 pull request #233
Opened 2023-03-07 15:24 UTC by KUK15

Proceso para hacer un Pull request

2023-03-09 23:56 UTC, JoseCamilo84 requested changes

2023-03-09 23:56 UTC, JoseCamilo84 commented on github-profiles/KUK15-3817/style.css
> +@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
Hola Xavier que tal... los import siempre van al principio del archivo, como buena práctica

2023-03-09 23:56 UTC, JoseCamilo84 commented on github-profiles/KUK15-3817/style.css
> +body {
Esto no se debería hacer, es decir repetir una etiqueta varias veces

2023-03-09 23:56 UTC, JoseCamilo84 commented on github-profiles/KUK15-3817/index.html
> +<html lang="Es">
lang="es" en minúscula, como buena práctica

2023-03-10 15:35 UTC, KUK15 commented on github-profiles/KUK15-3817/style.css
> +@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
Gracias por tus comentarios. He modificado el style.css para dejarlo en buena practica.

2023-03-10 17:36 UTC, nobody-redhawk approved these changes
# Recomendaciones 
1. Detallar paso a paso las actividades propuestas en los ejercicios de las clases de la semana 1.
1. Eliminar el archivo `KUK15-3817.md` de la carpeta `github-profiles`
2. Hacer deploying con vercel o Github pages y poner el link en la descripcion para ver el resultado de la página del perfil mas facilmente.
3. Por lo demás, todo ok. Éxitos!

2023-03-16 20:41 UTC, KUK15 commented
Me faltaría comentar los detalles de los ejercicios.

2023-03-19 03:55 UTC, JoseCamilo84 approved these changes

2023-08-11 01:58 UTC, closed without merging