Pull request: commit github profile
undefined-academy/semana-1 pull request #239
Opened 2023-03-07 16:58 UTC by CardonaEA

# Exercise 2
## 1. Fork repository
### Steps
- go to: **_https://github.com/undefined-academy/semana-1_** repository
- In the top-right corner of the page, click Fork.
- Select an owner (if applicable) and a name for the forked repository (name cab be the same.
- You can add a description of your fork.
- Click **Create fork**

## 2. Cloning a forked repository to a local directory
### Steps
- Open the forked repository
- Avobe the list os files, click **Code**
- Copy the SSH link of the repository
- Open Terminal
- Select the location where you want to clone the repository.
    - In my case:
        ```bash
        cd ~/bootcamp
        ```
- Type:
    ```bash
    git clone "SSH LINK YOU COPIED"
    ```
- Press enter

## 3. Markdown file and Github profile
### Steps I followed:
- Opened Terminal
- Created the .md in github-profiles as follows;
    ```bash
    cd ~/bootcamp/semana-1/github-profiles 
    echo "" > andresce-5981.md
    code andresce-5981.md
    ```
- Edited the file "andresce-5981.md" in VS Code
- Saved changes

## 3. Commit
### Steps I followed in VS Code:

```bash
cd ~/bootcamp/semana-1/
git remote -v # to check remote linking
git status
git add github-profiles/andresce-5981.md
git status
git commit -m "commit github profile"
# optional git log
git push
```

## 3. Pull Request
### Steps
- Go to the forked repository
- Click **Contribute (Pull request)**
- Click **Open Pull request**
- Insert title and description
- Create Pull Request

2023-03-10 19:22 UTC, yulsdev requested changes
Todo Ok, solo corrige las tablas del markdown y ya podras continuar con el ejercicio 4

2023-03-10 19:22 UTC, yulsdev commented on github-profiles/andresce-5981/README.md
> +|Syntax|Description|
Se recomienda alinear las lineas de las tablas, aunque no se note al visualizarlas. Es aconsejable tener bien formateado el documento.

2023-03-11 16:12 UTC, yulsdev requested changes
Por favor haz las correcciones en el archivo README.md, que te sugeri anteiormente.

2023-03-11 16:12 UTC, yulsdev commented on github-profiles/andresce-5981/index.html
> +                <th style="background-color: rgb(181, 181, 221)">Syntax</th>
Los estilos tienen que estar en el archivo style.css, no es recomendable definir estilos dentro del archivo .html si ya estas usando un archivo aparte para definirlos.

2023-03-11 16:38 UTC, CardonaEA commented on github-profiles/andresce-5981/README.md
> +|Syntax|Description|
Hola,
Ya hice los cambios.
Gracias!

2023-03-11 16:45 UTC, CardonaEA commented on github-profiles/andresce-5981/index.html
> +                <th style="background-color: rgb(181, 181, 221)">Syntax</th>
El único estilo que coloque en el html fue para colocar un background a los encabezados de la tabla,
ya que utilice th también para resaltar toda primera columna.

Creo que se podría usar strong en la la primera columna o agrupaciones en el CSS.

Tienes alguna recomendación?

2023-03-11 17:43 UTC, CardonaEA commented on github-profiles/andresce-5981/index.html
> +                <th style="background-color: rgb(181, 181, 221)">Syntax</th>
Ya todos los estilos están el el archivo CSS

2023-03-11 18:53 UTC, yulsdev requested changes
Esta bien la correccion, pero la observacion era tambien para la 2da tabla. Perdon que no lo puse directamente en el documento, pero pense que quedaba sobre entendido que tenian que corregirse las 2 tablas.

2023-03-11 18:57 UTC, yulsdev approved these changes
Parece que mientras revisaba corregiste la 2da tabla.
Bueno ahora esta todo OK, felicidades.

2023-03-12 13:26 UTC, mukatyz approved these changes
Everything is ok, great job

2023-03-14 09:42 UTC, merged