Mi perfil de GitHub
undefined-academy/semana-1 pull request #248
Opened 2023-03-07 20:37 UTC by marisolSv22

2023-03-09 16:56 UTC, pintor32 reviewed
Good job Marisol, the exercises are as requested

2023-03-09 16:57 UTC, pintor32 approved these changes

2023-03-14 20:58 UTC, dfm555 requested changes

2023-03-14 20:58 UTC, dfm555 commented on github-profiles/MarisolSalazarV-6177/main.css
> +body{
@marisolSv22 agrupa todos los estilos del body en una sola etiqueta.

Tal vez estabas probando que los estilos en cascada funcionaran.

2023-03-14 21:20 UTC, dfm555 approved these changes
Buen trabajo 💪

2023-03-14 21:20 UTC, merged

2023-03-14 21:27 UTC, adjsvar approved these changes

2023-03-14 21:27 UTC, adjsvar commented on github-profiles/MarisolSalazarV-6177/index.html
> +    <h3>This is the five commands</h3>
Hola Marisol, espero estes bien, veo que has hecho muy buen trabajo, te doy un dato si me permites, no es 100% necesario que construyas la tabla pero te dejo como hacerla si necesitas:

```
<table> //para delimitar la tabla
  <tr> //para crear las filas
    <th> //delimita los encabezados de la tabla (th va por table heading creo)
      Comandos
    </th>
  </tr>
  <tr> //Creo otra fila para los datos
    <td>dato 1</td> //La info va dentro de los td (table data)
  </tr>
  <tr> //Creo otra fila para los datos
    <td>dato 2</td> //La info va dentro de los td (table data)
  </tr>
</table>
```