[SEMANA-1] - Added .MD file to GitHub profile folder
undefined-academy/semana-1 pull request #25
Opened 2023-03-03 18:58 UTC by k4dm3l

Fork project. Added small profile description file using markdown and also added link to GitHub profile

2023-03-10 03:27 UTC, fedegomezc requested changes
Hola Camilo, cómo va? Esta todo muy bien. 
La única observación es que la carpeta 'camilo-acevedo-9421' tiene que ir dentro de 'github-profiles'. Es decir  **semana1/github-profiles/camilo-acevedo-9421**

2023-03-10 03:30 UTC, fedegomezc commented on camilo-acevedo-9421/index.html
> +      >
Esta parte no entendí bien si solo introdujiste el código para practicar darle estilos con CSS o tiene otra función?

2023-03-10 04:58 UTC, nobody-redhawk commented on camilo-acevedo-9421/index.html
> +      >
Es para mostrar un bloque de código como un ejemplo: 
El Elemento HTML <pre> (o Texto HTML Preformateado) representa texto preformateado. El texto en este elemento típicamente se muestra en una fuente fija, no proporcional, exactamente como es mostrado en el archivo. Los espacios dentro de este elemento también son mostrados como están escritos.

2023-03-10 05:01 UTC, nobody-redhawk approved these changes
Está todo OK.

2023-03-13 21:20 UTC, k4dm3l commented
Hola @fedegomezc, gracias por tu comentario, revisare y ajustaré según tus recomendaciones, gracias por la revision

2023-03-13 21:21 UTC, k4dm3l commented
Gracias @nobody-redhawk 👍

2023-03-13 21:23 UTC, k4dm3l commented
@fedegomezc PR up to date, podrías revisar nuevamente? Gracias!

2023-03-13 22:52 UTC, fedegomezc approved these changes
Esta perfecto. Ahi doy mi approve. Éxitos!

2023-03-14 09:44 UTC, merged