Mi perfil de GitHub
undefined-academy/semana-1 pull request #250
Opened 2023-03-07 21:02 UTC by warsant

TODO: Proceso de como creamos este PR

2023-03-21 11:33 UTC, warsant commented
@glrodasz no tengo revisiones de mi Pull, gracias

2023-03-21 15:01 UTC, glrodasz commented on README.md
Este archivo no debe ser eliminado, hace parte del repositorio original.

2023-03-21 15:01 UTC, glrodasz commented on .README.md
Este archivo no debería existir y no debería tampoco iniciar con punto, pues Linux lo trataría como archivo oculto.

2023-03-21 15:02 UTC, glrodasz commented on Santana-5450.txt
Este archivo tampoco debería existir y tiene la extensión incorrecta, debería ser `.md`

2023-03-21 15:02 UTC, glrodasz commented on github-profiles/Santana-5450.md
Cómo este archivo se movió a `README.md` tampoco debería existir.

2023-03-21 15:03 UTC, glrodasz commented on github-profiles/Santana-5450/README.md
Sería ideal que cumpliera con los criterios del ejercicio, que es agregar la table en markdown con los. comandos de la terminal y la lista de alias. Puedes revisar cómo lo han solucionado otros compañeros.

2023-03-21 15:04 UTC, glrodasz commented on github-profiles/Santana-5450/index.html
Buen trabajo con este archivo! es totalmente opcional, pero se puede añadir las recomendaciones indicadas en el archivo de markdown, como tabla de comandos de la terminal y alias preferidos.

2023-03-21 19:33 UTC, warsant commented on README.md
Tomado en cuenta

2023-03-21 19:33 UTC, warsant commented on Santana-5450.txt
Archivo eliminado del repo

2023-03-22 19:30 UTC, warsant reviewed
Realizados los cambios señalados por el revisor @glrodasz  Guillermo Rodas

2023-03-22 19:30 UTC, warsant commented on github-profiles/Santana-5450.md
Listo Guille eliminado

2023-03-23 04:08 UTC, glrodasz requested changes
Solo hace falta no eliminar el README de la raiz! te recomiendo que hagas sync de los cambios con el repositorio original, pero el resto está super!

2023-03-23 04:08 UTC, glrodasz commented on README.md
El archivo sigue como eliminado: NO debe ser eliminado.

2023-08-10 02:21 UTC, closed without merging