Mi perfil de github
undefined-academy/semana-1 pull request #253
Opened 2023-03-07 21:53 UTC by JeronimoCortez

1.Realice el mi breve descripción con markdown
2.Hice el fork del repositorio de undefined academy
3.Hice el push a mi repositorio forkeado
4.Cree el pull request

2023-03-08 22:23 UTC, JeronimoCortez commented
1.Creacion index html
2.Creacion carpeta nombre de github
3.Renombrar readme
4. Añadir los archivos a mi repositorio remoto
5. Hacer un commit
6. Hacer un push
7. Hacer pull request

2023-03-13 22:39 UTC, JeronimoCortez commented
Añadi los estilos de css con los pasos de Jeremy Tomas

2023-03-21 21:55 UTC, JoeOsG approved these changes
### Bien.

2023-03-21 22:08 UTC, julietalazzaro requested changes
Hola Jero , cambiar el nombre de la carpeta al de tu usuario de discord, con el id separado con un guion. El sitio esta muy bien!

2023-03-22 02:07 UTC, julietalazzaro commented
Buenas, faltaria eliminar la carpeta vieja para que no se suban las dos

2023-04-25 06:55 UTC, delospp requested changes

2023-04-25 06:55 UTC, delospp commented on github-profiles/jeroocortez-4788/README.md
Los Alias deberian estar en una sección así:

```bash
Comandos alias que me parezcan utiles
1. Alias1
2. Alias2
```

Realiza los cambios para darte el approved

2023-08-10 02:21 UTC, closed without merging