manuel pryda 7878
undefined-academy/semana-1 pull request #26
Opened 2023-03-03 19:20 UTC by manuelpryda

Siguiendo sus pasos no me ha parecido complicado, la parte dónde más problemas he tenido ha sido a la hora de hacer el commit, que despues se me olvidaba hacer push y por eso no tenia la opción de hacer el pull request.

2023-03-09 16:04 UTC, manuelpryda commented
Hemos añadido CSS

2023-03-22 07:27 UTC, delospp requested changes

2023-03-22 07:27 UTC, delospp commented on github-profiles/ManuelPryda-7878/README.md
> +
Porfa agrega los alias que tienes en el archivo manuelpryda7878.md dentro de este archivo, lo ideal era que el archivo lo hubieras renombrado a README.md y lo movieras según las indicaciones del ejercicio de la clase 03

2023-03-26 20:48 UTC, glrodasz requested changes

2023-03-26 20:48 UTC, glrodasz commented on github-profiles/manuelpryda 7878.md
Este archivo no debe ir.

2023-03-27 22:53 UTC, delospp commented on github-profiles/ManuelPryda-7878/README.md
> +
@glrodasz Aqui faltan los alias y queda con el approved tuyo y el mio, cierto?

2023-03-28 07:47 UTC, delospp approved these changes
Gracias por subir los cambios si puedes pasarte por mi PR y hacer la revision te agradezco 

https://github.com/undefined-academy/semana-1/pull/87

2023-03-28 08:51 UTC, merged