mi perfil de github - camilol1021-1734
undefined-academy/semana-1 pull request #264
Opened 2023-03-07 23:36 UTC by camilol1021

1. primero que todo fui al repositorio de github alli hice el fork y luego en la consola clone el repositorio, me guie con videos de yt
2. luego de haberlo clonado entre a ellos en el cd y pues abri el visual studio code
3. alli cree un archico con mi nombre de discord con el numeral , luego de ello puse todo lo de mardown y lo guerde
4. alli le di a add . y luego de eso procedi a hacer el commit y el pull y asi subieron los cambios a este repositorio, ahora por ultimo me encuentro desarrollando el el pull reques en github y subiendo todo

2023-03-08 18:19 UTC, camilol1021 commented
Ejercico html solucionado

2023-03-15 23:34 UTC, truquinio approved these changes

2023-03-15 23:34 UTC, truquinio commented on camilol-1734/README.md
> +# https://github.com/camilol1021
Meramente estético, capaz quisiste que quedara así, yo pondría el link en nivel  ## o ### para que el título sea como lo que más resalte. Igualmente te quedó muy bien.

Buena jornada

2023-03-27 19:14 UTC, dfm555 requested changes
@camilol1021 La estructura de carpetas no es correcta.

Mueve tu carpeta camilol-1734/ dentro de github-profiles/ y tu archivo camilol-1734.md dentro de camilol-1734/

2023-03-28 15:15 UTC, dfm555 requested changes

2023-03-28 15:15 UTC, dfm555 commented on README.md
Elimina este archivo

2023-03-28 15:15 UTC, dfm555 commented on github-profiles/README.md
elimina este archivo

2023-03-28 16:16 UTC, closed without merging