clase 03-semana1
undefined-academy/semana-1 pull request #268
Opened 2023-03-08 00:34 UTC by santiago01est

de markdown a html

2023-03-10 02:22 UTC, yulsdev requested changes
Correcciones adicionales a realizar:
- El directorio/carpeta `santiagoEstrada-6564` tiene que estar ***dentro*** de la carpeta/directorio `github-profiles`
- Te falta el archivo `index.html` dentro de la carpeta `santiagoEstrada-6564` segun lo que se pide en el ejercicio 3.
- No entiendo que es **intro_a_html** tienes que borrarlo o explicar en el commit para que sirve.

2023-03-10 02:22 UTC, yulsdev commented on santiagoEstrada-6564/.vite/deps_temp/package.json
> +{"type":"module"}
Te recomiendo  usar .gitignore para evitar subir archivos no relacionados con los ejercicios

2023-03-10 02:22 UTC, yulsdev commented on santiagoEstrada-6564/README.md
> +| Comando | Descripción |
Te sugiero alinear las tablas, aunque no se note al visualizarlo, es preferible que el documento se encuentre ordenado.

2023-03-10 02:22 UTC, yulsdev commented on github-profiles/santiagoEstrada-6564.md
> +# Hello, I'm Santiago Estrada 👋
Este archivo tienes que borrarlo, ya que en el ejercicio 3 se pide renombrarlo a README.md no tendria que estar.

2023-03-11 18:35 UTC, santiago01est commented
semana01 html index

2023-03-11 19:20 UTC, yulsdev requested changes

2023-03-11 19:20 UTC, yulsdev commented on github-profiles/santiagoEstrada-6564/index.html
> +    <a href="https://github.com/santiago01est">Mi perfil de github</a>
Te falta cerrar el `<body>` y el `<html>`. No se si es un error de Github, pero no veo las etiquetas de cierre.

2023-03-11 19:20 UTC, yulsdev commented on github-profiles/santiagoEstrada-6564/index.html
> +    <title>Mi perfil de MarkDown a HTML</title>
Es recomendable poner la etiqueta meta, para que el documento se visualice correctamente con los acentos y las ñ. O sea te falta `<meta charset="UTF-8">` entre las etiquetas `<head> </head>`

2023-03-12 17:24 UTC, yulsdev commented
Hola, que paso con el archivo `README.md` que estaba **dentro** de la carpeta /santiagoEstrada-6564 ?. Me lo muestra en color `gris` y dice que fue renombrado sin cambios. No puedo ver el contenido de ese archivo

2023-03-12 19:52 UTC, pablo-alex commented
Hola Santiago, aparte de los comentarios anteriores, ten cuidado con no hacer modificaciones del README que esta el root directory del repo.

![image](https://user-images.githubusercontent.com/42077537/224569540-2efe49ab-c7d0-4353-adc7-e207fd118068.png)

Me sale que los has eliminado, eso archivo no tendriamos que tocar. Por lo demas esta correcto!

2023-03-12 23:19 UTC, pablo-alex requested changes
El Readme original del repo no debe tocarse o despues se presentaran conflictos al momento de mergear

2023-08-09 02:12 UTC, closed without merging