PR - bR# 3929
undefined-academy/semana-1 pull request #269
Opened 2023-03-08 00:42 UTC by bEERRE96

Me costo un poco, ya que es la primera vez que uso Git / GitHub , pero nada que no se pueda resolver intentando y reviendo la clase

2023-03-09 20:02 UTC, MauBedoya approved these changes
no parece haber problemas con los nombres ni con las ubicaciones de los archivos 👍

2023-03-09 20:02 UTC, MauBedoya commented on github-profiles/bR-3929/style.css
> +table{
un detalle, quizá estaría bueno ponerle un background blanco a la tabla, y veo que puedes usar  la propiedad  `border-collapse: collapse;` para que el color del background no se desborde de las líneas de la tabla.

2023-03-10 17:05 UTC, nobody-redhawk requested changes

2023-03-10 17:05 UTC, nobody-redhawk commented on github-profiles/bR-3929/index.html
> +    <link rel="stylesheet" href="/github-profiles/bR-3929/style.css">
modificar la ruta del archivo css:  
```
    <link rel="stylesheet" href="style.css">
```

2023-03-15 03:11 UTC, nobody-redhawk approved these changes

2023-03-20 22:44 UTC, merged