This is the Leidy's second week homework
undefined-academy/semana-1 pull request #271
Opened 2023-03-08 00:51 UTC by LeidyGil

# Proceso acerca de como resolver este ejercicio

## *Primer momento*: 
Investigar que es un **Fork** en Git: Este es tener una copia del repositorio en mención en my repositorio y hacer cambios sin afectar el repositorio principal

## *Segundo momento*:
- Recordar como clonar el repositorio en mi local
- Abrir la terminal y navegar hasta el home (en este punto me fuí hasta la raíz del sistema e intenté clonar el repo allá y el sistema no me dejo :) )
- Luego de haber clonado exitosamente el repositorio listar los elementos que habian allí
- Navegar hasta la carpeta de perfiles y posicionarme dentro de esa carpeta
- Crear el archivo con Touch command con mi usuario de perfil de Discord
- Abrir el archivo en el visual code con Code . command
- Colocar allí en link de mi perfil y el texto de mi Overview en Markdown

## *Tercer momento*:
- Recordé que uno no ha e commit solo porque sí, hay que lanzar otros comandos: Utilice primero git add . para agregar mi archivo al staging area e iba revisando con git status
- Luego hice commit con el comando git commit -m ""
- Fuí a al repositorio original a hacer el Pull request y al seleccionar las ramas para comparar no habia nada (no entendía que me faltaba)
- Seleccione el fork de mi cuenta en el repositorio original y no habia nada aún; allí hice un alto y empece a pensar en el proceso y lógicamente como sería o como debía verlo allí hasta que recordé que me faltaba hacer el Push para poderlo ver reflejado en mi repositorio remoto
- Hice push con el command git push origin man
- Al hacer esto y seleccionar el **fork** en el repo original, ya me aparecía que tenia un commit para este proyecto y la opción para crear el Pull request.

2023-03-10 03:49 UTC, LeidyGil commented
# Adding the exercise for the class 3

## Yo tuve que investigar un poco acerca de como mover el archivo .md a una carpeta con una diferente jerarquia, intente varios comandos hasta que en uno le elimine la extensión al archivo y quedo oculto, me toco irlo a buscar desde la ventana de carpetas, colocarle la extensiòn e intentar el proceso de nuevo con el comando correcto.

## Ahora sé como manejar el mv renombrando archivos y moviendo a una carpeta al mismo tiempo.

2023-03-29 11:03 UTC, Lmendev requested changes
Dejé solo un comentario, por lo demás excelente trabajo 👍

2023-03-29 11:03 UTC, Lmendev commented on Leidy-5944/index.html
> +            <ol>Commands</ol>
La etiqueta de cierre `</ol>` debería estar al final para contener los `<li></li>` y Commands podría ser un `h3` en este caso
```html
<h3>Commands</h3>
<ol>
  <li>ls: List of content</li>
  <li>pwd: Print current working directory</li>
  <li>cd: Change current directory</li>
  <li>cp-r : Copy - recursive</li>
</ol>
```


[Example link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol)

2023-03-29 23:16 UTC, 4ngelo12 approved these changes
Faltaría agregar algunos alias luego de los comandos de la terminal pero por el momento te quedo muy bien la página

2023-03-30 01:38 UTC, LeidyGil commented
Muchas gracias por el comentario. Adicionado!

2023-03-30 21:06 UTC, Lmendev approved these changes
💎

2023-08-08 02:11 UTC, closed without merging