Ejercicio 2: Perfil GitHub y Readme en markdown
undefined-academy/semana-1 pull request #278
Opened 2023-03-08 02:58 UTC by OrcaCl

Hola.

Acá va mi ejercicio 2. Tuve un pequeño delay porque la había terminado ayer pero no encontraba el botón de pull-request. En el chat de discord alguien me dijo que se hacía y pude terminar el encargo 2. Es muy fácil de hacer una vez que entiendes la lógica detrás del procedimiento.

Atte.

OrcaCL -> El Caffa

2023-03-10 19:11 UTC, yulsdev requested changes
Estas son mis otras observaciones/recomendaciones:
- El ejercicio 1 no esta bien identificado, seria mejor que borres los archivos y dejar solo el archivo Markdown con lo que  se pidió en el ejercicio 1
- No pongas cosas que no se pidieron en los ejercicios, ya que dificulta la revisión.

2023-03-10 19:11 UTC, yulsdev commented on github-profiles/caffa-4633/README.md
> +Más adelante subiré un link a mi CV completo, pero por el momento dejaré este archivo hasta aquí.
Desde aqui tienes que corregir el archivo y dejarlo solo con tu CV resumido.

2023-03-10 19:11 UTC, yulsdev commented on github-profiles/caffa-4633/README.md
> +### Ejercicio 2
Esto se queda, pero como te puse arriba. Estas poniendo contenido que no se pidio.

2023-03-11 13:35 UTC, yulsdev requested changes
Te recomiendo otra vez, no poner contenido adicional. Limitate a lo que se pide en los ejercicios

2023-03-11 13:35 UTC, yulsdev commented on github-profiles/caffa-4633/index.html
> +        <p>Más adelante subiré un link a mi CV completo, pero por el momento dejaré este archivo hasta aquí.</p>
Sigues poniendo contenido que no se pide, estas haciendo una especie de Blog en este archivo. Solo se pide que tengas un resumen de tu CV. Tienes que limitarte a los pasos que se indican en los ejercicios

2023-03-11 13:35 UTC, yulsdev commented on github-profiles/caffa-4633/README.md
> + ### Ejercicio 3:
Como ya te recomende, NO debes poner contenido que no se pidio.

2023-03-11 16:25 UTC, OrcaCl commented on github-profiles/caffa-4633/index.html
> +        <p>Más adelante subiré un link a mi CV completo, pero por el momento dejaré este archivo hasta aquí.</p>
Sir, yes sir.

Voy a sacar todas las cosas y las voy a tirar para otro lado. 
Ya entendí el asunto.

2023-03-11 16:30 UTC, OrcaCl commented on github-profiles/caffa-4633/README.md
> + ### Ejercicio 3:
okey

2023-03-11 18:48 UTC, yulsdev commented
El ejercicio 1 todavia no esta determinado/identificado. En tu repositorio "el mundo del markdown" tienes varios archivos .md pero no se puede identificar cual es  el correspondiente al Ejercicio 1.
Mi sugerencia es que crees un repositorio llamado ejercicio 1 y coloque ahi un archivo .md con lo que se pide en el ejercicio 1. O sino tambien a tu archivo README.md que esta en la carpeta con tu nombre de usuario, le agregues la parte de los comandos y alias que se pide para dicho ejercicio. Vi que varios hicieron eso, o sea tienen lo del ejercicio 1 en su archivo README.md

2023-03-12 01:43 UTC, OrcaCl commented
> El ejercicio 1 todavia no esta determinado/identificado. En tu repositorio "el mundo del markdown" tienes varios archivos .md pero no se puede identificar cual es el correspondiente al Ejercicio 1. Mi sugerencia es que crees un repositorio llamado ejercicio 1 y coloque ahi un archivo .md con lo que se pide en el ejercicio 1. O sino tambien a tu archivo README.md que esta en la carpeta con tu nombre de usuario, le agregues la parte de los comandos y alias que se pide para dicho ejercicio. Vi que varios hicieron eso, o sea tienen lo del ejercicio 1 en su archivo README.md

Estoy viendo como ordeno las cosas porque para hacer la actividad del html, usé los archivos del encargo anterior sin copiarlos, sino que los renombré y apliqué según lo que pidieron. Entonces, cómo actualizo la información de commits anteriores si ya los archivos no son los mismos.

Debo borrar el pull-request y hacerlo de nuevo?
debo editar solo el readme.md online?
debo editar el readme.md local y pisar el remoto?

2023-03-12 02:26 UTC, yulsdev commented
Seria solo editar el archivo README.md y agregarle lo de los comandos y alias. Lo editas y haces un push normal, poniendo como mensaje del commit, que editaste el archivo para agregar lo que te faltaba del ejercicio 1

2023-03-12 13:28 UTC, yulsdev requested changes

2023-03-12 13:28 UTC, yulsdev commented on github-profiles/caffa-4633/README.md
> +### Tabla de comandos de Terminal
Las lineas de las columnas de las tablas tienen que estar alineadas, aunque esto no se  note al visualizar el documento (como markdown), se aconseja que el documento fuente se encuentre ordenado y bien formateado.

2023-03-12 13:28 UTC, yulsdev commented on github-profiles/caffa-4633/index.html
> +
Se recomienda no dejar espacios entre linea/filas.

2023-03-12 13:28 UTC, yulsdev commented on github-profiles/caffa-4633/.gitignore
> +demo.html
Este archivo no debería estar. Digo esto porque de varios que revise no aparece este archivo, así que supongo que se puede evitar que sea subido.

2023-03-12 21:40 UTC, OrcaCl commented on github-profiles/caffa-4633/.gitignore
> +demo.html
Se supone que .gitignore es el archivo el cual github entiende qué cosas debe y no debe versionar.

2023-03-12 21:41 UTC, OrcaCl commented on github-profiles/caffa-4633/index.html
> +
No afecta ni al funcionamiento ni al display. Es un ambiente de desarrollo, por ende, necesito que haya una buena visibilidad del código. Si es necesario pasar a producción posteriormente, se hará un minificado, uniendo los css, js y quitando todas las lineas y espacios extra.

2023-03-12 21:42 UTC, OrcaCl commented on github-profiles/caffa-4633/README.md
> +### Tabla de comandos de Terminal
Esto ya es una cosa de gustos y es subjetivo.

2023-03-12 23:51 UTC, yulsdev commented on github-profiles/caffa-4633/.gitignore
> +demo.html
Como dice mi comentario, revise varios pull request y la mayoria no lleva este archivo y tampoco vi este archivo en los repositorios que suelo consultar para descargar cosas que necesito para Linux. Asi que  debe haber una manera de que no se suba dicho archivo seguro es solo una opción de configuración de Git.

2023-03-12 23:56 UTC, yulsdev commented on github-profiles/caffa-4633/README.md
> +### Tabla de comandos de Terminal
Es una cuestión de tener ordenado un documento fuente, tu mismo dices abajo que dejas lineas en tu documento html para tener una buena visibilidad.

2023-03-13 00:15 UTC, OrcaCl commented
Será que habrá que incluir .gitignore en el mismo archivo .gitignore?

El dom., 12 mar. 2023 20:51, Julio Carlos ***@***.***>
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In github-profiles/caffa-4633/.gitignore
> <https://github.com/undefined-academy/semana-1/pull/278#discussion_r1133344997>
> :
>
> > @@ -0,0 +1 @@
> +demo.html
>
> Como dice mi comentario, revise varios pull request y la mayoria no lleva
> este archivo y tampoco vi este archivo en los repositorios que suelo
> consultar para descargar cosas que necesito para Linux. Asi que debe haber
> una manera de que no se suba dicho archivo seguro es solo una opción de
> configuración de Git.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-1/pull/278#discussion_r1133344997>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5W35ZIO7LVWOP46L66NIVLW3ZOP3ANCNFSM6AAAAAAVTH2FOQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-13 04:43 UTC, OrcaCl commented on github-profiles/caffa-4633/README.md
> +### Tabla de comandos de Terminal
![snap01030](https://user-images.githubusercontent.com/124632805/224609867-1f927aed-74bd-4a68-82e6-33e8a993be23.jpg)

Traté de reordenar el markdown en Readme.md para que se viera "mas ordenado y bonito" pero como puse descripciones muy largas, al hacer la vista previa en VS Code, se va al carajo la tabla luego de que se hace la conversión.  (Como se ve en la foto). 

Así que lo voy a dejar como está. -pero lo intenté hacer-

2023-03-13 04:46 UTC, OrcaCl commented on github-profiles/caffa-4633/.gitignore
> +demo.html
Leí harto sobre esto y como te comenté en el mail, si uso más archivos de los que quiero versionar, se deben agregar a .gitignore PERO, es importante además agregar .gitignore como primer campo en el archivo para que no se suba. No pude corregir el commit, por lo que sólo me quedó la opción de eliminar .gitignore desde el repo remoto, hacer git pull desde local, dejar que borre mi .gitignore y volver a crearlo en local, con touch y de inmediato agregar el primer parámetro para que no se suba.

Y ahora lo probé para corregir la otra cosa que comentaste, y no se subió.

2023-03-13 08:43 UTC, glrodasz commented
Si @yulsdev aprueba, le hacemos merge, no habría falta un segundo reviewer me hacen ping.

2023-03-13 11:40 UTC, yulsdev approved these changes
Esta todo Ok, solo que en adelante procura no usar `localhost`, ya que si alguien (usuario final) clona tu repositorio para poder ver el funcionamiento de index.html, no se cargara el archivo .css

Como estilos.css esta en la misma ubicación de index.html, entonces solo debe ir el nombre del archivo en la etiqueta link

2023-03-14 09:27 UTC, merged