My perfil de GItHub
undefined-academy/semana-1 pull request #287
Opened 2023-03-08 14:33 UTC by yolombana

Cree la carpeta
Cloné mi repositorio
Cree un archivo con el texto en markdown
Lo edité en visual
Hice git add
Hice git commit
Realicé el pull request

2023-03-10 03:19 UTC, Ezmant requested changes
Te falta renombrar el archivo [Yoel-3728.md](https://github.com/yolombana/semana-1/blob/main/github-profiles/Yoel-3728.md) a README.md y moverlo a la carpeta con tu nombre de discord, recordá que tenes que poner la carpeta [yoel-3728](https://github.com/yolombana/semana-1/tree/main/yoel-3728) dentro de [github-profiles](https://github.com/yolombana/semana-1/tree/main/github-profiles).
Sigue trabajando y agregando css para aprobartelo

2023-03-10 03:19 UTC, Ezmant commented on github-profiles/Yoel-3728.md
> +- **.3** :   `cd ../../..`
Muy bueno, en el alias te recomendaria que lo hagas dentro de una tabla tal como hiciste con los comandos.

2023-03-12 17:17 UTC, yolombana commented on github-profiles/Yoel-3728.md
> +- **.3** :   `cd ../../..`
Hola. Gracias por la revisión.
Lo moví y renombre el md como recomendaste. Quedo atento.

2023-03-12 17:17 UTC, yolombana commented on github-profiles/Yoel-3728.md
> +- **.3** :   `cd ../../..`
Agregé el html y el css.

2023-08-02 02:08 UTC, closed without merging