Mi perfil de Github
undefined-academy/semana-1 pull request #289
Opened 2023-03-08 15:09 UTC by ivan-pugliese

1 - Fork del repositorio
2 - Clonar el repositorio forkeado
3 - Agregar el archivo markdown con mi nombre a la carpeta github-profiles
4 - Colocar mi descripción y el link a mi perfil de Github
5 - Realizar git add .
6 - Realizar git commit
7 - Realizar git push
8 - Crear la pull request

2023-03-12 04:23 UTC, ernzxr requested changes
Esta muy prolijo el `index.html`, me gustaria ver como queda si le sumas la parte de tabla y alias del `README.md`

2023-03-12 04:23 UTC, ernzxr commented on github-profiles/ivanpugliese-8873/README.md
> +| Ctrl + R | Buscar comando |
Hola!

Se puede mejorar el formato rellenando con guiones y espacios para que se visualice mejor la tabla del markdown.

2023-03-12 04:23 UTC, ernzxr commented on github-profiles/ivanpugliese-8873/index.html
> +
Faltarian la tabla y la parte de alias :)

2023-03-13 13:49 UTC, ivan-pugliese commented on github-profiles/ivanpugliese-8873/index.html
> +
Hola! muchas gracias por el feedback, no estaba seguro si en el html poner la tabla de los alias, pero de momento los pondre para cumplir con lo pedido, gracias!!

2023-03-16 23:52 UTC, ernzxr approved these changes

2023-03-19 21:26 UTC, aabrazo approved these changes
Buen trabajo

2023-03-20 03:19 UTC, MauBedoya approved these changes
Se ve bastante bien en general 👍 solo un detalle con el padding.

2023-03-20 03:19 UTC, MauBedoya commented on github-profiles/ivanpugliese-8873/styles.css
> +body {
quizá podrías agregarle un poco de `padding` al body de modo que lo último del contenido no se vea tan pegado a la parte inferior de la ventana del navegador

2023-07-10 17:28 UTC, closed without merging