Semana 1 - Clase 2: Git Control de Versiones
undefined-academy/semana-1 pull request #292
Opened 2023-03-08 16:36 UTC by veacosta13

# Bootcamp Fullstack Javascript
## Semana 1 - Clase 2: Git Control de Versiones
### Pasos para realizar un pull request desde un fork
1. En primer lugar, ingresamos al GitHub y efectuamos el **fork** desde el repositorio **destino** para poder tener una copia de dicho repositorio en mi repositorio.
2. Bajamos el fork en nuestro **local**, realizamos los cambios deseados.
3. Efectuamos un **push** hacia nuestra copia del repositorio.
4. Finalmente, solicitamos un **pull request** desde nuestro repositorio remoto de GitHub hacia el repositorio destino desde el cual hicimos el fork inicial.
5. Esperamos a que el dueño del repositorio acepte nuestra petición.

2023-03-10 18:55 UTC, yulsdev requested changes
Todo Ok, solo te faltaria alinear la tabla y asi podras seguir con el ejercicio 3 y 4.

2023-03-10 18:55 UTC, yulsdev commented on github-profiles/veacosta13-2273.md
> +| Alias   | Descripción                                                                |
Te falta alinear esta tabla

2023-03-20 13:08 UTC, yulsdev requested changes
Realizar los cambios sugeridos, por favor.

2023-03-20 13:08 UTC, yulsdev commented on github-profiles/veacosta13-2273/index.html
> +
Se recomienda borrar estos espacios demas, hasta la linea 55

2023-03-22 01:18 UTC, NicoRomero3210 requested changes

2023-03-22 01:19 UTC, NicoRomero3210 approved these changes
Te apruebo tu PR, muy buen trabajo!

2023-08-02 02:08 UTC, closed without merging