Mi Perfil De Github
undefined-academy/semana-1 pull request #295
Opened 2023-03-08 18:24 UTC by dhdarken

Proceso De Como hice Este PR:

1.me dirijo a github https://github.com/undefined-academy/semana-1.
2.le doy en la parte superior derecha donde dice fork.
3.saco el link de el repositorio.
4.abro la terminal.
5.cree mi carpeta code.
6.inicialice el gitbash.
7.utilice comando ls para listar donde me encontraba, utilizo cd desktop para llegar a mi escritorio.
8.utilice el comando cd para entrar en mi carpeta code.
9.utiltice el comando git clone git@github.com:dhdarken/semana-1.git para clonar el repositorio.
10.use el comando code . para abrir el vscode dentro de la terminal
11.cree un nuevo archivo dentro de vscode con mi usuario de discord.
12.agregue la info de mi perfil en markdown dentro de el archivo con mi usuario de discord.
13.ahora en la terminal utilice comando git status para mirar si habian cambios.
14.utilice el comando git add . para agregar los cambios.
16.utilice el comando git branch-M main para hacer esta mi rama main.
17.utilice el comando git push -u origin main para subir mis cambios y mi commit.
18.ahora en mi repo clonado le doy donde dice pull request.
19.ahora en donde dice create new pull request.
20.llene esta info que estas mirando con el paso a paso y ahora le doy en create pull request.

2023-03-13 21:09 UTC, andrealvarez2d approved these changes
Muy bien, cumple con lo establecido en los ejercicios

2023-03-16 20:00 UTC, laurelone21 reviewed
Revisar etiqueta HTML en formato MarkDown

2023-03-16 20:24 UTC, JoeOsG commented
> 

### El comentario también lo puedes poner con markdown.

Esto para que sea mas fácil de **leer** y sirve como _practica_.

2023-03-16 20:42 UTC, dhdarken reviewed
error en README.md corregido

2023-03-16 20:43 UTC, dhdarken commented on dhdarken-5806/README.md
> +<ul>
ya lo arregle muchas gracias

2023-03-16 23:15 UTC, JoeOsG approved these changes

2023-03-17 18:50 UTC, laurelone21 approved these changes

2023-03-19 18:01 UTC, k4dm3l requested changes
Creo que renombraste una carpeta que no debía ser renombrada, debías crear una carpeta con tu nombre de usuario dentro de la carpeta git-profiles

2023-03-21 17:04 UTC, dhdarken commented
es la actividad de la semana 1 creo que todo esta bien lo hice bajo las especificaciones del profe renombre el archivo a README.md por que es el markdown

2023-03-21 17:13 UTC, dfm555 requested changes

2023-03-21 17:13 UTC, dfm555 commented on dhdarken-5806/.gitkeep
@dhdarken esta carpeta no puede ser renombrada

debes mover tus cambios dentro github-profiles

2023-03-21 19:30 UTC, richardjma commented
Una actividad bastante completa cumple con las meta establecidas para la actividad

2023-03-21 20:49 UTC, dhdarken commented on dhdarken-5806/.gitkeep
ya hice los cambios por favor revísalos cuando puedas . gracias

2023-03-21 20:50 UTC, dfm555 approved these changes

2023-03-21 20:50 UTC, merged