Mi perfil de GitHub
undefined-academy/semana-1 pull request #301
Opened 2023-03-08 20:57 UTC by DarKingSoul

## Pasos ejecutados 

1. Se realizó un fork desde el [repositorio](https://github.com/undefined-academy/semana-1) indicado en clase 
2. Una vez hecho el fork en mi perfil, se realizo la clonación del repositorio de manera local. 
3. Se abrió la carpeta **github-profiles** donde se creo un archivo con el nombre de discord, en mi caso fue *Darksoul-0040*.
4. En el archivo creado se agrego información de mi perfil en formato **markdown**.
5. Se realizo el respectivo **git add** y  **git commit** para subir los cambios en mi perfil de github.
6. Por último, se realizo el pull request.

2023-03-14 22:21 UTC, diirf requested changes
Hola, me ha gustado mucho tu repositorio. Te coloqué unos pequeños cambios.

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/README.md
> +## Link de perfil
El link al perfil de GitHub debería ir al final del README

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/README.md
> +## Comandos Alias
Falta la descripción de los alias

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/README.md
> +[Perfil en GitHub](https://github.com/DarKingSoul)
Este enlace debería ir al final del README

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/README.md
> +## Comandos Alias
Falta la descripción de los alias

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/index.html
> +                        <p>Es una aplicación realizada con amigos para teléfonos android en versiones 9 o superior. Para ver peliculas de
Este salto de línea podrías omitirlo, una persona con un tamaño de pantalla distinto, puede no ver el salto de línea en el mismo lugar que tú. Si quieres poder ver todo el contenido sin hacer scroll horizontal, podrías configurar el editor de texto para que te lo haga automáticamente

2023-03-14 22:21 UTC, diirf commented on github-profiles/Darksoul-0040/css/styles.css
> +    margin: 0;
Puedes colocar en el margin, después del 0 un "auto" para que se centre la página

2023-03-15 03:34 UTC, DarKingSoul commented
> Hola, me ha gustado mucho tu repositorio. Te coloqué unos pequeños cambios.

Hola, muchas gracias por tus observaciones, las corregí y las tomare en cuenta para proyectos futuros ^^.

2023-03-20 14:32 UTC, diirf approved these changes

2023-08-02 02:07 UTC, closed without merging