"Perfil de github de Agustina Romero"
undefined-academy/semana-1 pull request #304
Opened 2023-03-08 21:26 UTC by Romero-Agustina

Fue mas difícil de lo que pensaba, cuando quise ejecutar los comandos desde la consola para pushear los cambios no me pusheaba sobre origin, pude hacerlo con la herramienta de vs code "control de codigo fuente". Lo bueno aprendí mucho git y me familiaricé con los conceptos.

2023-03-09 06:00 UTC, hardstonepaul requested changes
Hello I liked your .md
But I think you have to make the commands table and alias commands.
So amazing to know that you are nurse good job.
I invite to review  my commits too
[hardstone](https://github.com/undefined-academy/semana-1/compare/main...hardstonepaul:semana-1:main)
Best Regards

2023-03-14 00:05 UTC, Romero-Agustina commented
Pude hacer mi primer pagina con html estilada con css y otro logro que quiero destacar es que ya puedo usar la consola con menos dificultad

2023-03-14 03:54 UTC, hardstonepaul approved these changes
### Well Done!!
I'm check again, now i can see the changes.
Congratulations. 🎉

2023-03-21 11:51 UTC, warsant reviewed
Luego de que revises mis comentarios apruebo, saludos

2023-03-22 20:29 UTC, Romero-Agustina commented on style.css
> +header {
Relalizé las modificaciones, espero tu revisión, gracias!

2023-08-01 02:26 UTC, closed without merging