My GitHub profile
undefined-academy/semana-1 pull request #306
Opened 2023-03-09 00:00 UTC by Dalianaguirre

## ToDo: Proceso de cómo hice este Pull Request 👌
1. Hice un fork del repositorio de **undefined-academy**.
2. Cloné el repositorio en mi consola de linux.
3. Dentro de la carpeta **github-profiles** agregué un nuevo archivo de mi perfil en markdown de GitHub.
4. Hice un **commit de ese archivo nuevo.**
5. Fui al repositorio de undefined-academy e hice el **PQ.**

2023-03-10 03:05 UTC, Ezmant commented
Vas bien, te faltaria agregar los comandos y alias para la terminal en el archivo  [Dali#7656.md](https://github.com/Dalianaguirre/semana-1/blob/main/github-profiles/Dali%237656.md) , podes ir revisando como hicieron los demás compañeros para poder guiarte. 
Ojo, no olvides de realizar los demas ejercicios.

2023-03-10 03:06 UTC, Ezmant reviewed
Vas bien, te faltaria agregar los comandos y alias para la terminal en el archivo  [Dali#7656.md](https://github.com/Dalianaguirre/semana-1/blob/main/github-profiles/Dali%237656.md) , podes ir revisando como hicieron los demás compañeros para poder guiarte. 
Ojo, no olvides de realizar los demas ejercicios.

2023-03-15 22:39 UTC, matiioj requested changes
Falta el README.md y el cambio que te sugeri, por lo demas buen codigo

2023-03-15 22:39 UTC, matiioj commented on github-profiles/Dali-7656/index.html
> +    <!-- <h3>✨ Some commands that i use:</h3>
podrias descomentar la parte de los comandos

2023-03-15 23:04 UTC, Dalianaguirre commented on github-profiles/Dali-7656/index.html
> +    <!-- <h3>✨ Some commands that i use:</h3>
Es verdad 😅 gracias

2023-03-21 04:10 UTC, closed without merging

2023-03-21 05:22 UTC, Dalianaguirre commented
Reopen PR