Add markdown with my Github profile
undefined-academy/semana-1 pull request #310
Opened 2023-03-09 00:36 UTC by achequisde

# Semana 1, clase 2

Para esta tarea hice los siguientes pasos:

- [x] Utilizar la funcion _fork_ dentro de Github
- [x] Crear el nuevo documento markdown con el comando `touch` dentro de la carpeta **github-profiles**
- [x] Editar el documento con **VSCode**, copiando el contenido de mi perfil de Github
- [x] Agregar el link a mi perfil de Github
- [x] Usar `git add .`, `git commit`, `git push` y muchos `git status` para visualizar y guardar los cambios
- [x] Crear el _Pull request_ desde la interfaz de Github

**Saludos!**

2023-03-10 20:37 UTC, equiman commented
# Revisión

![image](https://user-images.githubusercontent.com/933393/224420715-e16f5265-4433-4cbd-b3ff-d5737a3f8263.png)

[x] Creación de carpeta con nombre de usuario de discord
[x] Nombrado correcto de los archivos siguiendo las convenciones
[x] Aplicó la guía de diseño en 4 minutos
[x] El código CSS se definió siguiendo la estructura del HTML haciendo más fácil de entender su aplicabilidad

# Recomendaciones

- Poner la etiqueta `<code>` a la lista de comandos y alias para que tome el estilo
![image](https://user-images.githubusercontent.com/933393/224422247-650c4a31-415b-4c39-bcd6-c60dbeab75b8.png)
- Revisar la indentación del HTML, hay etiquetas al mismo nivel de `<body>`
- Tratar de usar otras etiquetas semánticas como `header`, `main`, `section`

2023-03-10 20:40 UTC, equiman reviewed
# Revisión

![image](https://user-images.githubusercontent.com/933393/224420715-e16f5265-4433-4cbd-b3ff-d5737a3f8263.png)

[x] Creación de carpeta con nombre de usuario de discord
[x] Nombrado correcto de los archivos siguiendo las convenciones
[x] Aplicó la guía de diseño en 4 minutos
[x] El código CSS se definió siguiendo la estructura del HTML haciendo más fácil de entender su aplicabilidad

# Recomendaciones

- Poner la etiqueta `<code>` a la lista de comandos y alias para que tome el estilo
![image](https://user-images.githubusercontent.com/933393/224422247-650c4a31-415b-4c39-bcd6-c60dbeab75b8.png)
- Revisar la indentación del HTML, hay etiquetas al mismo nivel de `<body>`
- Tratar de usar otras etiquetas semánticas como `header`, `main`, `section`

2023-03-10 20:49 UTC, equiman requested changes

2023-03-10 20:49 UTC, equiman commented on github-profiles/achequisde-5168/README.md
> +| `more` | File viewer |
Formatear las tablas para que se lean mejor cuando se está viendo el código fuente. Ejemplo:

```
| Name     | Description                                                    |
| --------- | ------------------------------------------------ |
| `uptime` | Tells how long the system has been running |
| `df`         | Shows available disk space                            |
```

2023-03-10 20:49 UTC, equiman commented on github-profiles/achequisde-5168/README.md
> +| Name | Description |
Tambien formatear esta

2023-03-10 20:49 UTC, equiman commented on github-profiles/achequisde-5168/index.html
> +</p>
indenter un nivel a la derecha para que no quede al mismo nivel de `body` considerar agruparlo dentro de una etiqueta semántica como `header`

2023-03-10 20:49 UTC, equiman commented on github-profiles/achequisde-5168/index.html
> +
indenter un nivel a la derecha para que no quede al mismo nivel de `body` y considerar usar etiquetas semánticas como `main` para agrupar todo el contenido principal y casa tema con un `section`

2023-03-10 21:45 UTC, nobody-redhawk commented on github-profiles/achequisde-5168/README.md
> +| `more` | File viewer |
exacto, alinear los separadorea de la tapa que se visualice mejor

2023-03-10 21:45 UTC, nobody-redhawk commented on github-profiles/achequisde-5168/README.md
> +| `ins` | Expands to `sudo apt install` to save a lot of typing 💀 |
Alinear los separadores de la tabla para que se visualice mejor

2023-03-10 21:50 UTC, nobody-redhawk commented on github-profiles/achequisde-5168/index.html
> +<body>
Anidar la etiqueta `header` para el encabezado y `main` para el contenido principal de página luego agrupar el contenido en secciones utilizando la etiqueta `section`  y anidar `div` dentro de `section` para tener mayor control al momento de la estilización.

2023-03-10 21:56 UTC, nobody-redhawk reviewed
# Recomendaciones
1. Anotar el paso a paso de las actividades requeridas en los ejercicios de las clases de la semana 1.
1. Mejorar en la indentación del archivo `index.html`, utilizar etiquetas `header`, `main`, `section` y `div` para estructurar mejor el código.
2. Hacer una deploying con *vercer* o *Github page* y compartir el link en la descripcion para ver el resultado mas facilmente.
3. Crear una carpeta `img` y mover las imagenes.
4. Espero sea de ayuda, éxitos.

2023-03-11 18:16 UTC, achequisde commented on github-profiles/achequisde-5168/README.md
> +| `more` | File viewer |
**Listo!** Ya introduje los cambios, gracias por el review. [Aqui esta el link](https://achequisde.github.io/semana-1/) del deployment en GH pages.

2023-03-11 18:16 UTC, achequisde commented on github-profiles/achequisde-5168/index.html
> +<body>
**Listo!** Ya introduje los cambios, gracias por el review. [Aqui esta el link](https://achequisde.github.io/semana-1/) del deployment en GH pages.

2023-03-11 21:19 UTC, nobody-redhawk approved these changes

2023-03-12 00:23 UTC, equiman approved these changes
Excelente, muy buen trabajo 👏👏👏

Un plus eso del despliegue a Vercel 🚀

2023-03-13 15:51 UTC, merged