mi perfil de github
undefined-academy/semana-1 pull request #312
Opened 2023-03-09 00:50 UTC by sebasvalencia

TODO: Proceso de cmo hice este PR Sebas Valencia

2023-03-09 15:31 UTC, marisolSv22 requested changes
Te faltan los alias mas usados en tu markdown

2023-03-13 00:12 UTC, sebasvalencia commented
> Te faltan los alias mas usados en tu markdown

Ya se agregaron los alias al markdown, gracias por el catch!

2023-03-13 14:12 UTC, marisolSv22 approved these changes

2023-03-23 00:15 UTC, lllariogonzalez reviewed
Falta agregar estilos según las recomendaciones de diseño de jeremy thomas https://jgthms.com/web-design-in-4-minutes/
para completar la semana-1

2023-03-23 01:25 UTC, lllariogonzalez approved these changes
Approve :octocat:

2023-03-23 13:53 UTC, merged