Mi perfil de Github
undefined-academy/semana-1 pull request #313
Opened 2023-03-09 01:33 UTC by RomiCode

Este PR se realizó utilizando los distintos comandos llevados acabo en la terminal de Ubuntu y en VSCode por medio de GIT

2023-03-09 15:31 UTC, marisolSv22 requested changes
Te faltaron los alias más usados

2023-03-10 21:40 UTC, nobody-redhawk commented on github-profiles/romina-2621.md
> +
Aqui puedes usar esta sintaxis `[Visite aqui mi perfil de Github](https://github.com/RomiCode)` que se veria así [Visite aqui mi perfil de Github](https://github.com/RomiCode)

2023-03-10 21:41 UTC, nobody-redhawk reviewed
Vas muy bien, sigue avanzando... 👍

2023-03-12 19:19 UTC, joaquinesteban approved these changes
Muy bien, Ejercicios correctos!

2023-03-13 13:36 UTC, cadifilippo commented
> Te faltaron los alias más usados

@RomiCode cuando te solicitan cambios (veo que lo has agregado ya) puedes informarle al revisor que ya está listo para que te apruebe.

![image](https://user-images.githubusercontent.com/26164385/224717528-ddd19956-c635-4c09-b2d6-dae367243874.png)
ahí seguramente te aparezca un icono de refresh, con darle ahí ya le avisaría...

2023-03-13 13:38 UTC, cadifilippo commented
> Vas muy bien, sigue avanzando... 👍

@nobody-redhawk para este ejercicio (Revisión) sería bueno aprobar o pedir cambios, no simplemente comentar, si consideras que lo que tu comentas no es bloqueante lo apruebas, si te parece necesario modificarlo, rechazas.

2023-03-13 14:05 UTC, marisolSv22 approved these changes

2023-03-14 00:59 UTC, merged