Perfil de github - Ever
undefined-academy/semana-1 pull request #319
Opened 2023-03-09 02:44 UTC by everjm0128

En este proceso investige acerca de como y que es un fork para poder "copiar" el repositorio ami cuenta, luego lo clone a mi pc he hize los cambios necesarios y añadi nuevas cosas en mi markdown, luego los agrege los  archviso cambiados al staging y los hize commit, para despues hacerles push y luego investigue un poco para la creacion del pull request.

2023-03-15 05:25 UTC, oabm77 approved these changes
Cumple con todos los requerimientos solicitados.

2023-03-22 04:13 UTC, oabm77 approved these changes
Excelente trabajo!

2023-03-22 04:18 UTC, julietalazzaro requested changes
Hola Ever! muy bien la pagina y markdown, pero estan las carpetas de practicas de js de la semana 2

2023-03-22 04:39 UTC, everjm0128 commented
> Hola Ever! muy bien la pagina y markdown, pero estan las carpetas de practicas de js de la semana 2

Listo muchas gracias, me había equivocado en los archivos de la semana.

2023-03-22 20:13 UTC, JoeOsG approved these changes
### Bien.

2023-03-28 09:09 UTC, merged