alexcaiced0#3094
undefined-academy/semana-1 pull request #33
Opened 2023-03-03 22:40 UTC by alexcaicedo

El proceso estuvo chevere! Aún no estoy muy acostumbrado a hacer Pull Requests. Creo que es el 2do que hago desde que decidí sumergirme en este mundo Tech. Pero básicamente copié la descripción que ya tenía en mi perfil de GitHub para ponerla en este ejercicio, le cambié el nombre al archivo (de README.md a alexcaiced0-3094.md) de acuerdo a las instrucciones.

Let's goo! 😃

2023-03-09 05:41 UTC, INGCapaDev requested changes

2023-03-09 05:41 UTC, INGCapaDev commented on github-profiles/alexcaiced0-3094/README.md
> +
Falta agregar la parte de los alias y comandos mas usados

2023-03-09 13:26 UTC, alexcaicedo commented on github-profiles/alexcaiced0-3094/README.md
> +
Hola! Muchas gracias por tu feedback. Aunque haya sido parte de lo propuesto por el instructor del Bootcamp, decidí omitir esa parte en el .md ya que no lo planeo colocar en el website que vamos a crear con nuestro CV.

Feliz dia!

2023-03-09 20:54 UTC, alexcaicedo commented on github-profiles/alexcaiced0-3094/README.md
> +
Finalmente cambié de opinión y decidí poner lo de los alias y comandos. 👍

2023-03-09 23:21 UTC, lllariogonzalez approved these changes
Approved, good job, I liked the alias to show the log of commits.

2023-03-10 00:37 UTC, nobody-redhawk commented on github-profiles/alexcaiced0-3094/index.html
> +    <!-- Aquí va el contenido -->
Como sugerencia dentro del body anidar una etiqueta `header` para el encabezado, donde puedes anidar un `h1` luego una etiqueta `main`, luego en la etiqueta `main` anidar etiquetas de `section` para tener el contenido mas organizado, dentro de la etiqueta `section` puedes anidar  las etiquetas `div`, ya dentro de la etiquetas `div` puedea anidar las etiquetas `h2`, `p`. Todo esto para que tengas mayor contro al momento de realizar la estilizacion.

2023-03-15 02:12 UTC, alexcaicedo commented on github-profiles/alexcaiced0-3094/index.html
> +    <!-- Aquí va el contenido -->
Hola @nobody-redhawk!... Acabo de hacer commit del website con algunas de las sugerencias que me diste. Quedo muy agradecido. Entiendo que aún queda mucho por mejorar, por lo que de ahora en adelante los siguientes cambios los haré teniendo en cuenta el ejercicio propuesto en la última clase sobre HTML semántico que nos dió Guillermo, el cual consiste en crear un nuevo PR. Te agradecería si por favor me dejas este último como revisado. Feliz dia!

2023-03-15 03:09 UTC, nobody-redhawk approved these changes

2023-03-16 01:00 UTC, alexcaicedo commented on github-profiles/alexcaiced0-3094/README.md
> +
Hola @INGCapaDev!, cómo estas?... Podrias por favor aceptar la revisión con los cambios realizados? Te lo agradezco un montón!

2023-03-16 01:21 UTC, INGCapaDev commented on github-profiles/alexcaiced0-3094/README.md
> +
Por supuesto

2023-03-16 01:34 UTC, INGCapaDev approved these changes
Buen trabajo, implemento correctamente los cambios.

2023-03-17 12:48 UTC, merged