perfil GitHub
undefined-academy/semana-1 pull request #333
Opened 2023-03-09 06:28 UTC by CaesarAlej24

## Proceso Ejercicio clase 2 perfil *GitHub*

Se repasó la **información** y los **comandos** de las clases previamente vistas, para lograr *clonar el repositorio* y generar el archivo **.md**, y se investigó igualmente en la red los **conceptos** que se desconocían al momento como **Fork**, se completa el ejercicio incluyendo en el archivo *markdown* mi perfil de **GitHub**.
- Se incluye **link** al perfil del *Github* en el archivo **.md**

2023-03-09 15:29 UTC, marisolSv22 requested changes
te recomiendo que alinees tus tablas markdown para mayor orden, Sigue asi!

2023-03-09 17:29 UTC, Mateo872 reviewed
Hola, te recomiendo que a tu repositorio le pongas el mismo nombre que tenés en github, así el readme te aparece en el inicio, como una representación.

2023-03-10 19:30 UTC, CaesarAlej24 commented
> te recomiendo que alinees tus tablas markdown para mayor orden, Sigue asi!

Hola Marisol, para hacer los cambios necesito hacer el commit de nuevo. con el mismo archivo y el mismo nombre del commit gracias.

2023-03-10 19:35 UTC, CaesarAlej24 commented
> Hola, te recomiendo que a tu repositorio le pongas el mismo nombre que tenés en github, así el readme te aparece en el inicio, como una representación.

Hola Mateo, te refieres a cambiar el nombre de el-mundo-del-markdown repositorio por mi nombre de perfil? gracias

2023-03-13 14:07 UTC, marisolSv22 approved these changes

2023-03-22 12:40 UTC, joseandresgavilanes reviewed
Hola Caesar, estos debería de ir en la semana N°2 sin embargo lo estás realizando en el repositorio de la semana 1. HTML semántico es parte de los ejercicios de la semana 2

2023-03-22 13:00 UTC, CaesarAlej24 commented
Hola @joseandresgavilanes , No solo le puse el nombre al commit asi con correccion de algunos errores que tenia, pero todavia no es el de la semana 2.

2023-03-22 13:18 UTC, dfm555 requested changes
@CaesarAlej24 tu fork no cumple con la estructura de carpetas solicitada

`github-profiles/caesara20-9814`

Crea el directorio `github-profiles/`

2023-03-22 15:30 UTC, dfm555 requested changes
@CaesarAlej24 revisa la estructura de carpetas nuevamente

2023-03-22 15:30 UTC, dfm555 commented on README.md
Este archivo no debe ser eliminado

2023-03-22 15:59 UTC, CaesarAlej24 commented on README.md
ya restaure el archivo README.md! ya esta la carpeta "github-profiles" debo pasar dentro de esa carpeta tambien los ejercicios de las otras clases?

2023-03-22 16:22 UTC, dfm555 requested changes

2023-03-22 16:22 UTC, dfm555 commented on README.md
@CaesarAlej24 Sí, todos tus archivos deben quedar dentro de la carpeta `github-profiles/`

2023-03-22 18:23 UTC, dfm555 requested changes

2023-03-22 18:23 UTC, dfm555 commented on github-profiles/caesara20-9814/index1.css
> +  /* background: #f5f7f9; */
Elimina el código comentado.

2023-03-22 18:34 UTC, CaesarAlej24 commented on github-profiles/caesara20-9814/index1.css
> +  /* background: #f5f7f9; */
@dfm555 ya corregi el codigo comentado. gracias

2023-03-22 18:47 UTC, dfm555 approved these changes

2023-03-22 18:48 UTC, merged