Mi perfil de GitHub: ernzxr
undefined-academy/semana-1 pull request #334
Opened 2023-03-09 07:19 UTC by ernzxr

## Clase 2 - Pasos realizados: Primer commit.

**1.** Se realizó un fork al repositorio <https://github.com/undefined-academy/semana-1>
**2.** Clone el fork en una subcarpeta local.
**3.** Creé el archivo `ernzxr-2086.md` a partir del primer markdown que realice `ernestojrcv.md`.
**4.** Hice un `git commit` de la `branch main`.
**5.** Realicé un `git push`.
**6.** Inicié una pull request en el repositorio raiz.

2023-03-10 18:44 UTC, yulsdev requested changes

2023-03-10 18:44 UTC, yulsdev commented on github-profiles/ernzxr-2086/README.md
> +    | Languages | Level |
Es recomendable tener las tablas alineadas, aunque no note al visualizarlas. Es aconsejable que el documento se encuentre bien formatedo.

2023-03-10 22:42 UTC, equiman requested changes
En general vas muy bien, pero se deben hacer algunas correcciones. 
Aun estaría pendiente aplicar la parte de estilos.

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/README.md
> +* ```alias cl="clear"``` Clear the terminal.
Cuando vas a escribir multiples lineas se usa el back-tick tres veces en este caso que solo se debe usar una

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/README.md
> +
Se recomienda alinear con espacion la tabla para que se pueda vere mejor tambien en el codigo fuente y no solo en la previsualizacion

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/README.md
> +| ls | Shows a list of elements inside the folder we're in. |
encerrar cada uno de los comandos con backtick para que los muestre con un formato diferente.

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/README.md
> +* ``` alias cafe="cat /dev/urandom | hexdump | grep \"ca fe\"" ``` 4fun.
Agrupar estos también en una tabla.

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/index.html
> +    <h1> Hello, I'm Ernesto José Riveiro </h1>
Corregir la indentacion por niveles para mejorar la legibilidad.

Hay varios typos, podes instalar esta extensión que te puede ayudar a corregirlos.

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/index.html
> +    <h3><strong>&#128195 Experience</strong></h3>
Está generando un error al intentar hacer el parseo en HTML. Te recomiendo probarlo en un navegador.

![image](https://user-images.githubusercontent.com/933393/224441287-aa893294-68e0-49a2-a135-4ecae63f10b0.png)

2023-03-10 22:42 UTC, equiman commented on github-profiles/ernzxr-2086/index.html
> +    <h3><strong>&#128170;&#127995 Skills</strong></h3>
Acá también está generando un error.

2023-03-11 22:13 UTC, ernzxr commented on github-profiles/ernzxr-2086/index.html
> +    <h1> Hello, I'm Ernesto José Riveiro </h1>
Me queda pendiente esto!, voy a revisar la extension para usarla en el proximo commit 😃 

Todo lo demas quedo actualizado en el ultimo commit junto con con la hoja de estilo.

2023-03-12 00:39 UTC, ernzxr commented
> Veo que creaste una carpeta adicional y dentro archivos adicionales, si fueran imagenes no habria problema pero son .html y .css no entiendo el motivo. En la carpeta con tu nombre de usuario solo deberia estar: README.md, index.html, el archivo `.css` y finalmente el o los archivos de imagen que usas en tu index.html

Habia resuelto los ejercicios de CSS que estaban en la clase y los agregue para navegar desde mi index y verlos, pero escapa de la consigna, lo corrijo en el proximo commit!

2023-03-12 00:43 UTC, ernzxr commented
## Clase 3 - Pasos realizados: Primer index.html

**1.** Se copio el contenido del .md creado en la clase anterior para traducirlo a .html en un nuevo archivo llamado index.html
**2.** Se renombro el archivo markdown a README.md y se lo movio junto con el index.html a una nueva subcarpeta /github-profiles/ernzxr-2086
**3.** Hice un git commit.
**4.** Realicé un git push.

2023-03-12 00:49 UTC, ernzxr commented
## Clase 3 - Pasos realizados: Primer style.css

**1.** Se crearon `exercise1.html`, `exercise2.html`, `exercises-css.html`, `style1.css` y `style2.css` para realizar los ejercicios de descendencia y layout.
**2.** Se creo el archivo `style.css` y se le dio formato utilizando la guia de [Jeremy Thomas](https://jgthms.com/web-design-in-4-minutes/).
**3.** Actualice el contenido y tablas de `README.md` e `index.html`.
**4.** Se busco tutoriales para dar un mejor formato a las tablas con CSS.
**x.** Hice un git commit.
**x.** Realicé un git push.

2023-03-12 02:52 UTC, ernzxr commented
## Updates 11/03

* Update on the `<header>`: I move the first `<h1>` outside the background image and we center the rest of the elements (`<a>` & `<img>`).
* Spells and indentation fixed on `index.html` fixed.
* `git commit`.
* `git push`.

2023-03-12 13:09 UTC, yulsdev approved these changes
Todo Ok, solo unos pequeños detalles en el README.md en la linea 55 tienes un espacio demás. En el archivo index.html procura no dejar espacios entre filas/lineas.
En el archivo style.css tambien solo dejar los espacios entre filas/lineas necesario para diferenciar los distintos selectores usados.
Te doy por aprobado, ya que son pequeños detalles, felicidades!!!

2023-03-12 22:55 UTC, equiman approved these changes

2023-03-14 09:38 UTC, merged