Mi perfil de Github
undefined-academy/semana-1 pull request #336
Opened 2023-03-09 12:57 UTC by Psychobroder

TODO: proceso de como hice este PR

2023-03-10 02:18 UTC, Psychobroder commented
> Deberías crear una tabla que muestre los alias de tu terminal

si tengo una, se muestra asi en Files changed, casi al final. eso si no esta muy ordenado, tenia prisa xD

| shortcut | description |
| ------ | ------ |
| npmd | alias npmd="npm run dev" | 
|npms | alias npms="npm start"|
| alias rm="trash" |Para evitar eliminar permanente los archivos|
| cl="clear" |El comando de clear se suele usar muchoalias |
| gst | Git Status alias gst="git status"|

2023-03-21 00:02 UTC, Lmendev requested changes
Buen trabajo! Con estos cambios por mi parte estaría listo

2023-03-21 00:02 UTC, Lmendev commented on github-profiles/psychobroder-2234/README.md
> +| command | description |
[SUG] Las tabals en markdown debería tener un formato agradable para su lectura por lo que podrías añadirle algunos espacios para dejarlas más simétricas y que se vean ordenadas

2023-03-21 00:02 UTC, Lmendev commented on github-profiles/psychobroder-2234/README.md
> +| command | description |
[SUG] Esta tabla como tiene las columnas muy grandes la dejaría así como está 👍

2023-03-21 00:02 UTC, Lmendev commented on github-profiles/psychobroder-2234/style.css
> +
[SUG] Se fueron unos espacios de más

2023-03-21 00:02 UTC, Lmendev commented on github-profiles/psychobroder-2234/style.css
> +
.

2023-03-21 09:20 UTC, Lmendev requested changes
Dejé una duda, resolviendo eso estaría por mi parte listo 👍

2023-03-21 09:20 UTC, Lmendev commented on README.md
[REQ] Por qué se intenta eliminar este archivo en el pull request? 🤔 

Acá solo deberían mostrarse que estas añadiendo tu info, no eliminando otros archivos

2023-07-18 20:38 UTC, closed without merging