Mi perfil de Github
undefined-academy/semana-1 pull request #337
Opened 2023-03-09 13:00 UTC by Hcofanelli

## Pasos para realizar el ejercicio:

- Hacer fork al repositorio de semana 1 de undefined-academy/semana-1
- Clonar el repositorio en la carpeta Code
- Crear nuevo archivo, con el comando touch, cuyo nombre sea el usuario de discord.
- Dentro del archivo, agregar un link al perfil de github y el contenido del archivo de profile creado la clase anterior.
- Ejecutar el comando **git add .** .
- Ejecutar el comando **git commit -m "Mi perfil de Github"**.
- Ejecutar el comando **git push origin main**.
- Dentro de Github, ir al repositorio forkeado, ir a **pull request** y presionar **"New pull request"**.
-  Finalmente **create pull request", agregamos la descripción y **create pull request**.

2023-03-14 19:45 UTC, Wannmi requested changes
En general esta muy bien. 👍
El **Markdown** esta bien, solo destaque algunas cosas visuales (lo cual muy relativo), por otro lado en el **HTML** es importante tener los estilos en otro, ya que brinda mayor flexibilidad a la hora de hacer proyectos mas grandes.
**Me gusto mucho el color de fondo que utilizaste!** 🎨

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/README.md
> +Ingeniero Electrónico dando los primeros pasos en la programación y el desarrollo web. Mi objetivo es convertirme en un 🌟 full stack developer y trabajar en proyectos desafiantes y emocionantes.
Me gustan como se ven los markdown con emoticones. En este caso la estrella en medio del texto solo genero que me **detenga** en la lectura, utilizaría emoticones al **principio** o al **final** del _texto_ o de cada _oración_. 💫

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/README.md
> +| `cp` | Copia un archivo o carpeta. |
Para una mejor **visualización** del _código markdown_  es recomendable que la tabla este bien alineada. 📐

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/README.md
> +- **alias ..='cd ..'** : Para volver al directorio padre.
Para no generar confusiones pondría el _código_ y la _descripción_ en distintas **líneas** o simplemente hacerlo en _formato_ de **tabla**.

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/index.html
> +    </style>
Es recomendable tener los estilos en un archivo distinto al del HTML.
Para ello creas un archivo con extensión `.css` el cual contendrá los estilos y lo vinculas al HTML en el **head** con la _etiqueta_ `<link>`.

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/index.html
> +    </table>
Por ultimo para una mejor **visualización** de la tabla, mediante _estilos_, podrías agregarle bordes y colores (a gusto).
Podrías probar con `border-collapse:` y `border:` y también podes experimentar con cada etiqueta de la tabla `tr`, `th` y `td`.

2023-03-14 19:45 UTC, Wannmi commented on github-profiles/hcofanelli-9792/index.html
> +        <td>Descripción</td>
Para los encabezados de celdas se usa la etiqueta `th`.

2023-03-17 17:16 UTC, Wannmi approved these changes

2023-03-20 23:08 UTC, Hcofanelli commented
> muy buen trabajo luce muy bien tanto el markdown como el html. Pero te sugiero que a la etiqueta ul le agregues `list-style: none; padding: 0;` para que no se vean los puntos de la lista por defecto y solo queden los emoticones

Perfecto, muchas gracias por la review!

2023-03-21 17:33 UTC, merged