uploading readme
undefined-academy/semana-1 pull request #341
Opened 2023-03-09 17:27 UTC by rachelbq

## 🐾 Pasos para resolver el ejercicio:
        1.	Login a mi cuenta de GitHub
        2.	Acceso al repositorio https://github.com/undefined-academy/semana-1
        3.	Pulsar “Fork” -> se creó un nuevo repositorio en mi cuenta con una copia del repo original
        4.	Copiar el código de la dirección URL del repositorio forkeado desde mi cuenta de GitHub
        5.	Abrir Git Bash, cambiar el directorio de trabajo actual por el de la ubicación donde clonar el repo
        6.	Escribir comando git clone seguido de la dirección URL copiada de antes
        7.	Agregar el archivo markdown de mi perfil de GitHub dentro de la carpeta github-profiles, cambiando el nombre del archivo por el de mi usuaria de Discord
        8.	Modificar el archivo para incluir un link directo a mi perfil de GitHub
        9.	Comando git add . en Git Bash para añadir los cambios en el repo
        10.	Realizar el commit de ese archivo
        11.	Realizar el push de la nueva versión del repo de local a mi respositorio remoto
        12. Solicitar un Pull Request al administrador del repositorio inicial para que se apruebe el merge
        13.	Describir el proceso de resolver el ejercicio en la descripción del Pull Request en formato Markdown

2023-03-09 19:44 UTC, lucianogarriga requested changes

2023-03-09 19:44 UTC, lucianogarriga commented on github-profiles/Raquel_Burgos-Full_Stack-2874.md
> +
Increíble el diseño en markdown que has dado a tu perfil Raquel! Muy bueno. 

Lo único, no sé si tu nombre de discord es "Raquel_Burgos-Full_Stack", ya que debe coincidir con el nombre del archivo .md.

A continuar así, muchos éxitos!

2023-03-09 21:18 UTC, rachelbq commented on github-profiles/Raquel_Burgos-Full_Stack-2874.md
> +
Hola,

Gracias por el feedback!!!

Mi nombre de discord es: "Raquel Burgos - Full Stack#2874", lo único que le añadí los guiones bajos al nombrar el archivo. 

Un saludo!

2023-03-12 02:58 UTC, Veysia commented
Que bonito tu perfil, te quedo muy bien :smile: :clap: :clap:

2023-03-14 20:45 UTC, MauBedoya approved these changes
Quedo muy bien el readme y todo parece estar correcto 👍

2023-03-14 20:45 UTC, MauBedoya commented on github-profiles/Raquel_Burgos-Full_Stack-2874/index.html
> +            <ul><p><strong><span style="color:rgb(2, 119, 128)">JAVASCRIPT | NODE.JS | BOOTSTRAP | REACT</span></strong></p></ul>
como comentario, quizá usar una clase en los span y modificar el color desde el CSS, para así poder cambiar el color fácilmente si se diera la necesidad.

2023-03-15 11:09 UTC, rachelbq commented
Gracias por el feedback @MauBedoya!!!

Y sobretodo por la mejora propuesta!!! Tienes razón, mucho mejor en el caso
de querer modificar el color en algún momento!!!

El mar., 14 mar. 2023 21:46, MauBedoya ***@***.***> escribió:

> ***@***.**** approved this pull request.
>
> Quedo muy bien el readme y todo parece estar correcto 👍
> ------------------------------
>
> In github-profiles/Raquel_Burgos-Full_Stack-2874/index.html
> <https://github.com/undefined-academy/semana-1/pull/341#discussion_r1136176711>
> :
>
> > +    <title>My profile</title>
> +    <link rel="stylesheet" href="./main.css" />
> +</head>
> +<body>
> +    <div class="container">
> +        <img src="./foto_GH.png" alt="Me" height="130" width="120">
> +        <h1>Hi, I'm Rachel B.</h1>
> +        <h2>Jr. Full-Stack developer</h2>
> +        <p>Straight to <strong>full-stack development</strong> from now on... 🚀 My creative front profile, agreeing with my curious back profile that needs to understand how magic is created... ✨</p>
> +        <hr />
> +    </div>
> +    <div>
> +    <h3>🔗 Link to <a href="https://github.com/rachelbq">my GitHub</a></h3>
> +    <ul>
> +       <h3>· I'm currently learning:</h3>
> +            <ul><p><strong><span style="color:rgb(2, 119, 128)">JAVASCRIPT | NODE.JS | BOOTSTRAP | REACT</span></strong></p></ul>
>
> como comentario, quizá usar una clase en los span y modificar el color
> desde el CSS, para así poder cambiar el color fácilmente si se diera la
> necesidad.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-1/pull/341#pullrequestreview-1340249595>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXK77KEIE5GZVT6OYL7IODW4DKIZANCNFSM6AAAAAAVVM7GBQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-03-20 18:44 UTC, cadifilippo commented
@rachelbq puedes pedirle a @lucianogarriga  que te revise de nuevo la PR, cuando tengas los 2 aprobados le hago merge!

2023-03-20 18:55 UTC, lucianogarriga approved these changes
He observado que actualmente tu PR cumple con todo lo solicitado, felicitaciones!! Aprobaré tu PR!

2023-03-20 18:55 UTC, lucianogarriga commented
Listo @cadifilippo gracias por la mención, acabo de corroborar que @rachelbq cumplió con lo requerido asique he aprobado su PR!

2023-03-20 18:58 UTC, merged

2023-03-21 09:34 UTC, rachelbq commented
Gracias ***@***.***!!! 😊*


El lun., 20 mar. 2023 19:55, Luciano Garriga ***@***.***>
escribió:

> ***@***.**** approved this pull request.
>
> He observado que actualmente tu PR cumple con todo lo solicitado,
> felicitaciones!! Aprobaré tu PR!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-1/pull/341#pullrequestreview-1349216463>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXK77JOLEAO5R6WHCVRDWLW5CRZHANCNFSM6AAAAAAVVM7GBQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>