Add github profile file, laurelone21
undefined-academy/semana-1 pull request #348
Opened 2023-03-09 22:55 UTC by laurelone21

## Creación de archivo Markdown
Enriqueciendo el ejercicio (tarea) de crear un README a un repositorio, se agregó un link referencia para el perfil de GitHub de un servidor laurelone21

2023-03-11 15:30 UTC, yulsdev requested changes

2023-03-11 15:30 UTC, yulsdev commented on github-profiles/laurelone-6335/README.md
> +|Comando|Descripción|
Se recomienda tener alineadas las columnas de la tabla, aunque al visualizar el documento (en el visualizador) no se note, es preferible que tambien el documento fuente se encuentre ordenado.

2023-03-11 15:30 UTC, yulsdev commented on .gitignore
> +.DS_Store
Este archivo no deberia estar aqui, te recomiendo revisar porque se subio.

2023-03-12 01:19 UTC, laurelone21 commented on github-profiles/laurelone-6335/README.md
> +|Comando|Descripción|
Qué tal, si, es lo preferible; he empezado a hacer mis notas con dicho marcado de lenguaje de Markdown
Tomado en consideración

2023-03-12 01:22 UTC, laurelone21 commented on .gitignore
> +.DS_Store
Buen día, este lo deje solo para que  no considere los archivos temporales que genera la Mac; cuando utilizas el Finder.

2023-03-13 20:25 UTC, yulsdev approved these changes
Todo Ok, felicidades.

2023-03-13 20:25 UTC, yulsdev commented on .gitignore
> +.DS_Store
No recuerdo bien, pero creo que es posible incluir al propio archivo `.gitignore` dentro de `.gitignore` para que no sea subido al repositorio.

2023-03-15 14:49 UTC, yulsdev approved these changes
Todo Ok, felicidades.

2023-03-15 15:52 UTC, dhdarken approved these changes

2023-03-28 23:11 UTC, merged