GitHub Profile -> Marcelo Reyna-8629.md
undefined-academy/semana-1 pull request #35
Opened 2023-03-03 23:27 UTC by marceloreyran

**Pasos para realizar el Ejericicio**

    1-Hacer un Fork del repositorio de la semana 1.
    2-Clonar el repositorio creado al hacer el Fork, No el repositorio original.
    3-Agregar la primera tarea en un archivo con nombrado con el usuario y tag de discord. Marcelo Reyna-8629.md.
    4-Agregar un link al perfil de GitHub dentro de una cita.
    5-Crear el Pull Request.

2023-03-09 22:35 UTC, olezdev reviewed
Se agregaron archivos .DS_Store, creo que no hay que subirlos

2023-03-09 22:35 UTC, olezdev commented on github-profiles/Marcelo Reyna-8629/main.css
> +
Quitaría espacios en blancos y daría formato al css `Shift + Alt + F`

2023-03-13 20:14 UTC, marceloreyran commented on github-profiles/Marcelo Reyna-8629/main.css
> +
Gracias por tu feedback los tomare en cuenta para seguir mejorando saludos!!

2023-03-15 18:06 UTC, EvanaSabatella1989 approved these changes

2023-03-15 18:06 UTC, EvanaSabatella1989 commented on github-profiles/Marcelo Reyna-8629/README.md
> +
Buenas tardes compañero. Excelente trabajo. Felicitaciones

2023-03-21 00:03 UTC, camilasilvab approved these changes

2023-03-26 20:52 UTC, glrodasz requested changes

2023-03-26 20:52 UTC, glrodasz commented on github-profiles/README.md
Este archivo no debe ser movido.

2023-03-26 20:52 UTC, glrodasz commented on github-profiles/.DS_Store
Podrias remover este archivo? `rm .DS_Store` y `rm github-profiles/.DS_Store`

2023-04-02 19:54 UTC, closed without merging