Perfil
undefined-academy/semana-1 pull request #353
Opened 2023-03-10 01:27 UTC by andresarioro

## Proceso de Pull Request  

[x] Hice fork y copié la dirección del repositorio (el mio)  
[x] Accedí al directorio */home/Code*  
[x] Cloné el  repositorio con el comando **git clone** y la url copiada previamente  
[x] Busque el archivo README.md en el repositorio anterior, donde tengo mi perfil ya creado  
[x] Copié dicho archivo con el comando **cp README.md /home/esandresaristi/Code/semana-1/github-profiles/esandresaristi-5768.md**  
[x] Abrí este archivo con **Code**  
[x] Realicé las modificaciones respectivas, como por ejemplo la inclusión del enlace a mi perfil GIT  
[x] Verifiqué estas modificaciones con **git status** y guardé los cambios con **git add**  
[x] Hice commit con **git commit -m**  
[x] Hice push con **git push**
[  ] En proceso de hacer pull request al realizar esta descripción  

# Fue una experiencia maravillosa

2023-03-14 14:38 UTC, joseandresgavilanes approved these changes
**Hola Andrés!** Me gustó mucho el trabajo que realizaste, solamente tengo una acotación. Tal vez el mover la **carpeta resources** a una **carpeta aparte** estaría mejor así podrías tener más control de todo en un futuro. 

![image](https://user-images.githubusercontent.com/76002851/225035734-a6ae3647-2ea6-4ce3-b101-12b71d05b7b6.png)

Saludos!

2023-03-16 05:28 UTC, andresarioro commented
# Saludos Jose. 

Mil gracias por tomarte el tiempo de revisar. Te cuento que moví la carpeta **Resourses** un directorio atrás, quedando al mismo nivel de la carpeta **esandresaristi-5768** donde se encuentra el ***index.html***  

Adicionalmente, actualicé los respectivos enlaces, hice commit de los cambios e hice push de dicho commit.   

Quedo atento a  tus comentarios, de antemano, muchas gracias.


![image](https://user-images.githubusercontent.com/56662924/225522091-41efbb01-83e1-493e-8b74-768285b1a5a5.png)

2023-03-22 03:56 UTC, everjm0128 approved these changes
**Hola que tal**, acabo de verificar y me gusto mucho tu trabajo, solo es necesario **cambiar** la etiqueta 
```html 
<header> 
```
por
```html 
<head> 
```
por lo demás excelente 👍

2023-03-22 04:07 UTC, andresarioro commented
# Saludos @everjm0128 agradezco mucho tu revisión.    
El tema del **<header>** se debe a que algunas propiedades que apliqué en la hoja de estilos no me funcionaba al aplicarse al **<head>**, al utilizar **<header>** funcionó sin problemas.  
¿Sabes cual es la diferencia entre ambas etiquetas?. Investigaré el tema, pero si vos sabes, agradezco me cuentes. Nuevamente, mil gracias.

2023-03-22 18:58 UTC, dfm555 requested changes
Hola @andresarioro 

La estructura de carpetas debería cambiar.

Debes mover la carpeta Resouces dentro de la carpeta` github-profiles/esandresaristi-5768/` y como sugerencia la renombraría a resources.

2023-03-23 03:18 UTC, andresarioro commented
Saludos @dfm555 agradezco mucho tu observación, realmente quedó mucho más ordenado ahora, y lamento el error de ortografía que tenía.
Moví la carpeta con  el nuevo nombre y actualicé los respectivos enlaces, tanto en los .html como en las hojas de estilo.

Agradezco puedas darle un  vistazo, aprobar el cambio y aprobar el pull request.

2023-03-23 13:32 UTC, merged