Mi Perfil de Github
undefined-academy/semana-1 pull request #357
Opened 2023-03-10 04:06 UTC by googlerax

### *Como hacer pull request:*:grinning:

1. *Hacer fork del repositorio deseado.*
2. *Copiar el link del nuevo repositorio "forkeado" y clonarlo con el comando  `$ git clone [DIRECCIÓN HTTPS].`*
3. *Una vez clonado puedes trabajar con el repositorio haciendo cambios, agregando contenido etc*.
4. *Agregar los cambios/contenidos con el comando `git add .`*
5. *Confirma los cambios con `git commit -m "texto-descriptivo".`*
6. *Identifica el nombre del repositorio remoto con `git remote`, esto es para poder enviar los cambios al repo remoto.*
7. *Realiza `git push origin [Nombre del repositorio]` para enviar en forma segura los cambios a GitHub.*
8. *Ve a tu repositorio en GitHub y verás un botón llamado "Pull request", has clic en él.*
9. *Detalla los cambios hechos, luego click en Create pull request y listo!.*

2023-03-11 05:01 UTC, gurrutia15 reviewed
Está bien, te faltaría poner un enlace que lleve a tu perfil

2023-03-11 06:33 UTC, luanarmo requested changes

2023-03-11 06:33 UTC, luanarmo commented on github-profiles/Griselda_S-0715.md
> +| Comando | Uso |
Hola 👋, estaría bien que la tabla estuviera alineada, me refiero a poner varios "tabs" y los pipes "|" queden alineados 😁

2023-03-11 06:33 UTC, luanarmo commented on github-profiles/Griselda_S-0715.md
> +
Minireto! 😎 Añade el alias del cafe: `alias cafe="cat /dev/urandom | hexdump | grep "ca fe""` sin que la tabla se rompa.
El alias utiliza el  "|" que es con lo que se compone la tabla.

2023-03-23 03:37 UTC, luanarmo requested changes
# Hola 👋
Veo que haz hecho cambios, por ejemplo las tablas ya estan alineadas, pero tienes un pequeño error.
Cuando clonaste el repositorio habia una carpeta llamada `github-profiles` y dentro de esta debe estar tu carpeta `Griselda_S-0715`. 
La ruta deberia quedar asi `github-profiles/Griselda_S-0715` , por favor mueve tu carpeta `Griselda_S-0715` dentro de `github-profiles` 🙏

2023-07-29 02:08 UTC, closed without merging