semana-1
undefined-academy/semana-1 pull request #362
Opened 2023-03-10 06:15 UTC by MMMarcoAntonio

### Gracias **Guillermo Rodas**
Hace 6 meses deje este camino de convertirme en FrontEnd, pero gracias al bootcamp que creaste y la suerte de econtrarlo volvi a perseguir mi meta de convertirme en FrontEnd... y estos pocos dias aprendi mucho... muchas Gracias.

2023-03-10 21:23 UTC, MartinRodrigoVargas requested changes

2023-03-10 21:23 UTC, MartinRodrigoVargas commented on github-profiles/marco-antonio-5338.md
> +
Ya no es necesario que conserves este archivo markdown (`marco-antonio-5338.md`). 
La idea era que lo renombraras y lo movieras a la nueva carpeta.

2023-03-10 21:23 UTC, MartinRodrigoVargas commented on marco-antonio-5338/README.md
> +
En este ejercicio te falto agregar al menos 2 alias de la Terminal y su función.

2023-03-10 21:23 UTC, MartinRodrigoVargas commented on marco-antonio-5338/index.html
> +
Al igual que en el README, te faltan agregar los alias. Lo demás pareciera estar perfecto 👍

2023-03-10 21:24 UTC, MartinRodrigoVargas commented
### En la descripción del Pull Request deberías haber puesto cómo fue el proceso de resolver el ejercicio (desde el Fork hasta el ultimo paso) utilizando markdown.
#### PD: Bienvenido de vuelta al mundo del FrontEnd/BackEnd.

2023-03-13 03:14 UTC, Vickmagar commented on marco-antonio-5338/index.html
> +  <body>
Hola colega fullstack, quisiera comentarte que puedes hacerle algunas mejoras a tu archivo index.html mi sugerencia es la siguiente:

Puedes utilizar el diseño semantico, donde defines tu archivo con un header, main y footer.
Tambien para darle un poco mas de estructura puedes utilizar articule, sections y div.
Puedes agregarle clase a tus selectores, para que con el uso de css puedas ponerlo mas chulo. 

Todas estas recomendaciones son para que puedas tener las bases de como es diseñar un sitio web estatico, de forma profesional

Yo no soy experto y llevo un año intentando aprender todas estas cosas de manera autodidactica, son muchos conceptos y mucha informacion, este bootcamp es una gran opcion para que podamos aprender mas. Te felicito por tu desarrollo, excelente trabajo.

2023-07-28 02:13 UTC, closed without merging