mi perfil github
undefined-academy/semana-1 pull request #369
Opened 2023-03-10 20:04 UTC by EdwinOrtizCantillo

proceso de como hice este PR 
Primero hice un forks y clone el repositorio de   https://github.com/undefined-academy/semana-1
luego cree mi perfil en MD, ya después realice un commit posteriormente el push después me dirigí al repositorio de github donde realice el forks y cree un nuevo PR
Muchas Gracias

2023-03-13 20:20 UTC, andrealvarez2d commented
> proceso de como hice este PR Primero hice un forks y clone el repositorio de https://github.com/undefined-academy/semana-1 luego cree mi perfil en MD, ya después realice un commit posteriormente el push después me dirigí al repositorio de github donde realice el forks y cree un nuevo PR Muchas Gracias

Como sugerencia le agregaria mas detalle al proceso y lo acomodaria con markdown

2023-03-13 20:34 UTC, dhdarken requested changes

2023-03-13 20:34 UTC, dhdarken commented on github-profiles/Edwin_Ortiz-3619.md
> +| ------ | ------ |
arreglaria mejor el diseño de la tabla.

2023-03-13 20:34 UTC, dhdarken commented on github-profiles/Edwin_Ortiz-3619.md
> +|  cl  |  Clear  |
daria una mejor descripcion de el alias ya que hay compañeros o me incluyo estamos aprendiendo.

2023-03-15 02:22 UTC, fjquants commented on Edwin_Ortiz-3619/README.md
> +**Los 5 comandos mas usados son:**
Como recomendación, las tablas realizados en md hay que cuadrarlas para que sean más legibles.

2023-03-15 13:34 UTC, EdwinOrtizCantillo commented on github-profiles/Edwin_Ortiz-3619.md
> +| ------ | ------ |
Hola, muchas gracias, lo haré.

2023-03-15 13:34 UTC, EdwinOrtizCantillo commented on github-profiles/Edwin_Ortiz-3619.md
> +|  cl  |  Clear  |
Hola, muchas gracias, lo corregiré.

2023-03-15 13:35 UTC, EdwinOrtizCantillo commented on Edwin_Ortiz-3619/README.md
> +**Los 5 comandos mas usados son:**
Hola, muchas gracias, lo corregiré.

2023-07-28 02:12 UTC, closed without merging