Create MonsterT#9886
undefined-academy/semana-1 pull request #37
Opened 2023-03-04 00:15 UTC by Codemonster808

Para este proceso lo intente desde la terminal pero me estaba dando un error de permisos, ya que cuando intentaba clonar el repo directo en mi home no me permitía por un error parecido , debí crear primero la carpeta de semana-1 y ya después en esa ubicación me permitió clonar el repo pero cuando inicie la ubicación en code no me permitía agregar, no se por que ya que yo configure las llaves ssh con antelación , sin embargo decidí intentarlo desde la interfaz y pues aqui estoy

2023-03-15 19:29 UTC, cristianruiz2023 commented on README.md
Hola impecable trabao!!!! nose que parte del bootcamp vas,veo que pusiste los estilos dentro del html capaz una mejor practica seria  linkearlo a un archivo style,css sigue asi vas muy bien

2023-03-16 16:10 UTC, fjquants commented on github-profiles/MonsterT#9886/index.html
> +    <style>
Recomendable colocar todo esta parte del estilo en un archivo con extension css y aqui hacer enlace a dicho archivo con:
<link rel="stylesheet" href="nombre del archivo.css">

2023-03-18 16:40 UTC, fjquants commented on github-profiles/MonsterT#9886/styles.css
> +<!DOCTYPE html>
Hola, en el archivo de css solo se coloca lo que está en la etiqueta de <style> no se tiene que colocar lo de DOCTYPE, html, head, body.

2023-03-18 21:07 UTC, fjquants approved these changes

2023-03-26 20:52 UTC, glrodasz requested changes

2023-03-26 20:52 UTC, glrodasz commented on README.md
Este archivo no puede ser removido.

2023-03-26 21:03 UTC, Codemonster808 commented on README.md
Ok que debería hacer entonces Guillermo debo accionar algo para esto ? quedo presto a resolver lo que sea necesario

2023-04-02 19:59 UTC, glrodasz commented on README.md
Puedes sincronizar con el repositorio fork, o simplemente volver a crearlo en base al repositorio fork, para que no existan cambios.

2023-04-25 17:41 UTC, closed without merging