Proyecto Semana 1 Git y Markdown
undefined-academy/semana-1 pull request #375
Opened 2023-03-10 23:48 UTC by angelormz

# Resolviendo este primer reto

La verdad no fue tan complicado como se veía en un primer momento el uso de **Git y Markdown**. Para retroalimentarme un poco más en el uso de Markdown entré al sitio oficial y vi algunos ejemplos, así como un sitio en Medium donde venía un ejemplo para el uso de tablas lo que me ayudó a facilitar el trabajo.

Para _git_ y para realizar el _fork_ y mi primer _pull request_ de igual manera tuve que entrar a documentación de GitHub donde encontré como hacer el **fork** o **bifurcación** y cómo guardarla en mi sistema mediante el uso de la terminal para posteriormente hacer el commit y por último ejecutar el pull request.

A mí me gusta completar mucho las clases con información adicional, es decir, investigo para completar un poco los temas y con esto fortalecer lo aprendido, hasta ahora un excelente bootcamp.

2023-03-11 15:43 UTC, yulsdev requested changes
Te recomiendo revisar el nombre del archivo, parece que el espacio en el nombre del archivo/carpeta causa conflictos para revisar el documento.
No logro diferenciar el nombre del archivo, seguramente lo creaste sin la extension .md
o talvez sea por el espacio entre tu nombre y tu apellido.

2023-03-11 15:43 UTC, yulsdev commented on github-profiles/Angelo Ramirez-5010
> +| **Nombre del Comando** | **Descripción** |
Se recomienda alinear las lineas de las columnas, aunque no se note al ser visualizado (en el visor de markdown), el documento fuente tambien debe estar ordenado.

2023-03-11 16:09 UTC, angelormz commented on github-profiles/Angelo Ramirez-5010
> +| **Nombre del Comando** | **Descripción** |
Hola Yuls de acuerdo al primer comentario ya renombre el nombre del archivo con la extensión.md y de igual manera quité el espacio entre mi nombre y apellido esperando se resuelva esta cuestión. En cuanto al segundo comentario para alinear las columnas en el markdown ya realicé este cambio directamente desde el documento fuente. Cualquier comentario quedo atento, muchas gracias por la retro 👍

2023-03-11 16:20 UTC, yulsdev commented on github-profiles/Angelo Ramirez-5010
> +| **Nombre del Comando** | **Descripción** |
Ok lo del nombre del archivo ya esta solucionado, pero la tabla en markdown sigue sin alinear. La alineacion de las tablas tienen que verse "igual", tanto al ser visualizadas como en el documento fuente. Si te fijas en el documento fuente las columnas estan desalieneadas.

2023-03-11 19:16 UTC, angelormz commented on github-profiles/Angelo Ramirez-5010
> +| **Nombre del Comando** | **Descripción** |
Listo ya hice los cambios solicitados en ambas tablas para alinear cada una de ellas en el documento fuente. Quedo atento :)

2023-03-11 19:24 UTC, yulsdev approved these changes
Todo Ok, felicidades. Ahora te toca realizar los siguientes ejercicios

2023-03-21 19:51 UTC, angelormz commented
Envío archivo index.html para revisión.

2023-03-22 00:49 UTC, yulsdev commented
Hola, te cuento que esta bien el Index.html, pero tendrias que renombrar a index.html.
Otra cosa, no se si es problema de GitHub, pero no veo la carpeta `AngelRamirez-5010`, esa carpeta deberia estar **dentro** de la carpeta `github-profiles` y recien ahi iria el README.md y el index.html. Lo que hiciste fue el ejercicio de la semana 1 clase 3?.

2023-03-22 01:01 UTC, angelormz commented
> Hola, te cuento que esta bien el Index.html, pero tendrias que renombrar a index.html. Otra cosa, no se si es problema de GitHub, pero no veo la carpeta `AngelRamirez-5010`, esa carpeta deberia estar **dentro** de la carpeta `github-profiles` y recien ahi iria el README.md y el index.html. Lo que hiciste fue el ejercicio de la semana 1 clase 3?.

Hola, ya lo renombré a index.html una duda, ¿por qué tiene que ir en minúsculas los nombres de los archivos? De lo otro que me comentas si justo estaba batallando con eso porque no se visualizaba mi carpeta y estuve intentando de muchas maneras, según yo ya quedó pero si me apoyas en verificar te lo agradecería mucho. Si hice el ejercicio de la clase 3, muchas gracias por la retro!

2023-03-22 17:57 UTC, yulsdev commented
Sigo viendo a AngelRamirez-5010 como un `archivo` , como te dije, no se si es un error de GitHub.

Respecto a los nombres de archivo en minusculas, tiene que ver mas que todo sobre buenas practicas. Cuando solo tienes un archivo html no se percibe mucho, pero cuando ya tengas varios archivos, por ej. contacto.html, index.html, encuesta.html, inicio.html etc. al momento de crear los archivos puede que los crees de diferente forma, por ej. Contacto, index.html, encuesta.html, Inicio.html ....debe haber una concordancia con los nombres...al crear Contacto con mayuscula se puede entender que es mas importante que index.html. Entonces o creas todos con mayuscula al inicio o directamente todos con minuscula, es mas facil crearlos todos con minusculas.

2023-03-22 18:30 UTC, yulsdev commented
Revisa a donde apunta tu origin con: `git remote -v` en lo que te salga tiene que aparecer tu nombre de usuario.
Segun lo que me dices el error que te sale es porque esta apuntando directamente al repositorio original, por eso no te deja hacer push

2023-03-22 23:18 UTC, closed without merging