mi primer markdown
undefined-academy/semana-1 pull request #376
Opened 2023-03-10 23:55 UTC by Ender96

el proceso fue sencillo, me toco averiguar sobre el fork porque no sabia como hacerlo, y tambien averiguar como hacer el pull request , de resto lo demas lo hice desde la terminal de ubuntu.

2023-03-15 23:41 UTC, sebasvalencia approved these changes

2023-03-15 23:56 UTC, Jejorm reviewed
Puedes realizar estos dos cambios, todo lo demás está muy bien!  👍

2023-03-15 23:56 UTC, Jejorm commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
Puedes añadir un titulo mas descriptivo a tu documento

2023-03-15 23:56 UTC, Jejorm commented on github-profiles/Ender26-3118.md
La estructura de archivos es diferente a la que menciono Guillermo, todos tus archivos deben estar dentro de la carpeta `Ender26-3118` para tener una mejor idea puedes dirigirte a la diapositiva del ejercicio, allí está el modelo que debes seguir.

2023-03-16 00:09 UTC, Ender96 commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
si es valido, gracias por tu sugerencia

2023-03-16 00:12 UTC, Jejorm approved these changes
Gran trabajo, bien hecho felicidades 🎉

2023-04-01 01:22 UTC, dfm555 requested changes

2023-04-01 01:22 UTC, dfm555 commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
Agrega el título a tu página cv y tu nombre

2023-04-01 01:33 UTC, Ender96 commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
el titulo y el nombre lo coloco en la etiqueta title?

2023-04-01 01:36 UTC, dfm555 commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
Sí.

2023-04-01 01:43 UTC, Ender96 commented on github-profiles/Ender26-3118/index.html
> +    <title>index</title>
ya hice la modificacion, gracias por la sugerencia.

2023-04-13 13:05 UTC, dfm555 approved these changes

2023-04-13 13:05 UTC, merged