actividad 2
undefined-academy/semana-1 pull request #38
Opened 2023-03-04 00:58 UTC by AlbertoCaroBarrera

# Apartado 1.
Vamos a Github al repositorio que creamos, y hacemos un fork, nos hará una copia del repositorio en nuestro propio Githib.

# Apartado 2.
Ejecutamos el código en nuestro directorio /home
```
git clone "link ssh del repo"

```

# Apartado 3 y 4
Creamos un markdown como el siguiente dentro de la carpeta especificada.

![image](https://user-images.githubusercontent.com/118636132/222863313-db736327-639c-4ab1-9746-17a11b0d817e.png)

# Apartado 5

``` 
git init
git add .
git commit -m 'actividad 2'
git remote add origin <url-de-tu-repo>
git push -u origin main

```

# Apartado 6

Simplemente ejecutamos un pullrequest de mi rama nueva.

# Errores cometidos a la hora de la actividad

- Cuando se clona un directorio no es necesario hacer un Commit.  En este caso sería:
```
git clone ...../semana-1
cd semana-1
git status
```

Muchas Gracias a Codernicula por la ayuda en la correccion de errores!

2023-03-15 23:55 UTC, truquinio requested changes

2023-03-15 23:55 UTC, truquinio commented on github-profiles/Alberto-7443/README.md
> +| Alias | Utilidad |
Estaría bueno alinear la tabla, como decía Guillermo la vez pasada

2023-03-15 23:55 UTC, truquinio commented on github-profiles/Alberto-7443/README.md
> +| HABILIDADES |------------        | CERTIFICADOS |
Estaría bueno alinear la tabla, como decía Guillermo la vez pasada

2023-03-15 23:55 UTC, truquinio commented on github-profiles/Alberto-7443/README.md
> +| ll: | alias de "ls -l", muestra el contenido de un directorio en formato largo.
Si mal no veo, creo que te faltan los cierres de la tabla   " | "

2023-03-26 20:53 UTC, glrodasz requested changes

2023-03-26 20:53 UTC, glrodasz commented on README.md
Este archivo no puede ser removido.

2023-04-02 19:59 UTC, closed without merging