Ejercicio semana 1
undefined-academy/semana-1 pull request #383
Opened 2023-03-11 15:37 UTC by sheifg

2023-03-11 22:38 UTC, misterdan100 commented
Hola, me gustó mucho el ejercicio que realizaste.

Solamente recomendaría dos cosas.
- Renombrar el archivo con la extensión .md para que puede ser visualizado directamente en GitHub en versión markdown y se sepa que se trata de tal tecnología.
- Hay que darle un nombre más descriptivo a los commits para poder ver solo con el título del commit de que se trata.

Felicidades por tu avance 👏🏼

2023-03-11 22:40 UTC, misterdan100 requested changes
Hola, me gustó mucho el ejercicio que realizaste.

Solamente recomendaría dos cosas.
- Renombrar el archivo con la extensión .md para que puede ser visualizado directamente en GitHub en versión markdown y se sepa que se trata de tal tecnología.
- Hay que darle un nombre más descriptivo a los commits para poder ver solo con el título del commit de que se trata.

Felicidades por tu avance 👏🏼

2023-03-12 15:46 UTC, sheifg commented
@misterdan100 muchas gracias por las recomendaciones Daniel :)
He realizado los cambios que me has sugerido y también lo tendré en cuenta para los siguientes ejercicios.

2023-03-12 23:50 UTC, sheifg commented
### Resolution of exercise 2
* Inside the github-profiles folder I have created a folder with my Discord username _Sheila_FG-7067_
* With the folder created I have renamed the Markdown file of my GitHub created in the exercise 1 with _README.md_ and moved it there
* In order to continue I have made an _index.html_ based on _README.md_
* To conclude I have sent a commit of the file _index.html_ and named it with _Creation of HTML file based on the Markdown file from my profile_

2023-03-15 18:57 UTC, sheifg commented
### Resolution of class 4 exercise
- Check the tutorial "Web Design in 4 minutes" of Jeremy Thomas
- Review what I learned during the class and decide how I wanted to improve the appearance of my index.html through CSS
- Add _<div>_ to organise into sections and include _id_ and _class_ selectors to select the HTML element(s) I want to style
- Create the file style.css and style the _index.hmtl_: body, content, tittles, paragraphs, tables, links... 
- Search for CSS tutorials to do everything I want to do
- Once everything was done, sent the commit _Adding CCS to style index.html_

2023-03-17 08:55 UTC, cristinacdm approved these changes
Todo parece bien, good job!👍🏻

2023-03-17 09:03 UTC, sheifg commented
@cristinacdm muchas gracias por revisar mi PR :)

2023-03-17 15:46 UTC, Byron2016 reviewed
@undefined-academy :+1: This PR looks great - it's ready to merge! :shipit:

Hola, @Sheila_FG

- [x] En cuanto a los commits de pronto completar la idea, por ejemplo agregas extensión a archivo pero no pones a que archivo

2023-03-17 15:46 UTC, Byron2016 commented on github-profiles/Sheila_FG-7067/README.md
@undefined-academy :+1: This PR looks great - it's ready to merge! :shipit:

Hola, @Sheila_FG

- [x] Nombre de carpeta: Correcto
- [x] README.md: me pareció que  bien, no importante pero que algo dijo Guillermo es que para tema de legibilidad el raw deberían las tablas estar alineadas, pero no es algo necesario en realidad.

2023-03-17 15:46 UTC, Byron2016 commented on github-profiles/Sheila_FG-7067/github-mark.png
@undefined-academy :+1: This PR looks great - it's ready to merge! :shipit:

Hola, @Sheila_FG

- [x] .png: podría estar en una carpeta img, pero sobre esto Guillermo no indicó nada.

2023-03-17 15:52 UTC, Byron2016 requested changes
Hola, @Sheila_FG

- [x] Archivo Sheila_FG-7067.md: **No** debería estar directamente en carpeta Github-profiles
- [x] .png: podría estar en una carpeta img, pero sobre esto Guillermo no indicó nada.

2023-03-17 20:23 UTC, sheifg commented
@Byron2016 Muchas gracias por tus comentarios y he realizado los cambios que me sugeriste. Respecto al archivo Sheila_FG-7067.md lo había sustituido por el README.md que aparece, pero creo que por un error en cuanto a ubicación en carpetas al hacer push, no se actualizó o sincronizó.

2023-03-17 20:36 UTC, Byron2016 approved these changes
@undefined-academy :+1: This PR looks great - it's ready to merge! :shipit:

2023-03-20 18:34 UTC, merged