subir profile
undefined-academy/semana-1 pull request #385
Opened 2023-03-11 18:42 UTC by basco1979

Subiendo mi perfil de Github

2023-03-19 16:28 UTC, JoseCamilo84 requested changes

2023-03-19 16:28 UTC, JoseCamilo84 commented on github-profiles/basko79-1418/index.html
>          <h1>Bootcamp</h1>
Hola, creo que tienes muchos h1 en la misma página, deberías de colocarlos dentro de otro contenedor como un section o article, es decir segmentar más tu código

2023-03-20 20:43 UTC, basco1979 commented on github-profiles/basko79-1418/index.html
>          <h1>Bootcamp</h1>
Hola JoseCamilo84
Ahi realice algunas modificaciones.
Gracias

2023-03-20 23:01 UTC, basco1979 reviewed
Cambios realizados

2023-03-27 08:56 UTC, Lmendev requested changes
Dejé unos comentarios :)

2023-03-27 08:56 UTC, Lmendev commented on github-profiles/basko79-1418/Readme.md
> +# Alias
por la jerarquía este `# Alias` debería ser `## Alias` https://www.markdownguide.org/basic-syntax/#headings

2023-03-27 08:56 UTC, Lmendev commented on github-profiles/basko79-1418/Readme.md
> + * perfil Github : https://github.com/basco1979
Acá podrías unas un link de markdown https://www.markdownguide.org/basic-syntax/#links

2023-03-27 09:23 UTC, basco1979 commented on github-profiles/basko79-1418.md
> +# CV
Corregido

2023-03-27 09:23 UTC, basco1979 commented on github-profiles/basko79-1418/Readme.md
> + * perfil Github : https://github.com/basco1979
Corregido

2023-03-27 10:16 UTC, Jorem999 approved these changes
Todo bien!

2023-03-27 10:16 UTC, Jorem999 commented on github-profiles/basko79-1418/alex-siale-qH36EgNjPJY-unsplash.jpg:Zone.Identifier
> +[ZoneTransfer]
Hola Basko, en mi repositorio también se me generó un archivo de estas características, creo que sucede cuando se copia el archivo con el Explorer de Windows, hubo un problema con una compañera que quería hacer Fork de la semana usando git bash de Windows y no podía porque el nombre del archivo no es compatible con Windows (por los dos puntos en el nombre).
Me pidieron que lo borrara para evitar futuros inconvenientes, me parece que hay que borrarlo para evitar el mismo problema

2023-03-27 17:25 UTC, glrodasz commented on github-profiles/basko79-1418/Readme.md
Lo más común es que este archivo sea llamado en mayuscula. `README.md`

2023-03-27 17:25 UTC, merged