Ejercicio clase 2
undefined-academy/semana-1 pull request #387
Opened 2023-03-11 21:04 UTC by LinaDeLosReyes

- Revisé el la web como hacer un fork en https://www.youtube.com/watch?v=9YUaf-uxuRM
- Fuí a [https://github.com/undefined-academy/semana-1](https://github.com/undefined-academy/semana-1) y le doy en fork
- en la terminal pongo cd (lo que me lleva a /home/ldreyes)
- Comprobé con pwd que estoy en el folder correcto
- Usé **git clone** git@github.com:LinaDeLosReyes/semana-1.git para clonar el repositorio en **HOME**
-Dí comando **ls** para ver el contenido
- Creé el archivo con mi usuario de discord con comando **touch** LDR-2846.md
- Modifiqué el archivo con code LDR-2846.md
- Copié la información del archivo de markdown y lo pegué
- Agregué mi url de github y guardo
- Pasé los cambios a stage con git add .
- Realicé comiteo con git commit -m "Ejercicio clase 2"
- Dí Push con git push
- Fuí al repositorio y doy clic en pull request
- Escribí el paso a paso de lo que hice en markdown para llenar la descripción

****Recursos : Diapositivas Git****

https://undefinedshell.notion.site/Semana-1-1cd3b0f777a44b4894456521cc0e649c

2023-03-19 17:10 UTC, JoseCamilo84 requested changes

2023-03-19 17:10 UTC, JoseCamilo84 commented on LDR-2846/index.html
> +    <html lang="en">
Hola, te falta el archivo css

2023-03-22 07:30 UTC, delospp requested changes
Porfa sube el archivo main.css a la carpeta con tu nombre de discord con el ejercicio de la clase 4 de la semana 1

2023-03-22 07:33 UTC, delospp commented on LDR-2846/index.html
> +    <html lang="en">
no solo el archivo sino linkearlo con el html agregando la linea `<link rel="stylesheet" href="/main.css">` antes de que cierre el head

2023-03-24 02:35 UTC, delospp approved these changes
Gracias por subir los cambios, gran trabajo

2023-03-24 14:52 UTC, LinaDeLosReyes commented on LDR-2846/index.html
> +    <html lang="en">
Hola. El archivo css listo.

2023-08-09 02:11 UTC, closed without merging