Primera solicitud de pull request.
undefined-academy/semana-1 pull request #39
Opened 2023-03-04 01:44 UTC by kendar9

## planteamiento inicial del  ejercicio
_Forkear el repositorio de un  tercero  bajarlo a local,  actualizarlo con los  commits  y resubirlo a mi github para realizar el pull  request_

## Solucion del ejercicio

1. **se forkea el  repositorio del tercero.**
2. **se clona en local por medio  de la terminal**
3. **se crea el  documento markdown y  se ejecuta en  vsc para complementarlo**
4. **se realiza el pull para  actualizarlo con respecto al original**
5. **se realiza el commit  y posteriormente se realiza el push**
6. **por ultimo se solicita el pull request**

## comentarios  del ejercicio.

***se realizo sin problemas hasta el punto de realizar el push, pienso que fue porque no realice correctamente el pull al inicio y tuve  que recurrir a otros coomandos  con ayuda de google  realmente, pero al final pude realizar el ejercicio, espero seguir aprendiendo y lograr la meta de completar satisfactoriamente el bootcamp.***

2023-03-15 23:52 UTC, truquinio requested changes

2023-03-15 23:52 UTC, truquinio commented on Christian-Duque-8776/README.md
> +| COMANDO | SOBRE ESO |
Se te pisó la tabla de comandos con los pasatiempos.

2023-03-20 21:27 UTC, Skydeer94 commented
Hola buenas tardes,

Te recomiendo iniciar cada párrafo o título con mayúsculas, para darle más estética, y manejar los signos de puntuación donde haya lugar.

Pero es un buen trabajo, felicitaciones.

2023-03-20 21:44 UTC, nbarbettim requested changes

2023-03-20 21:44 UTC, nbarbettim commented on Christian-Duque-8776/index.html
> +<!DOCTYPE html>
Buen trabajo, sin embargo deberías incluir el charset dentro del archivo  HTML

2023-03-26 20:54 UTC, glrodasz requested changes

2023-03-26 20:54 UTC, glrodasz commented on github-profiles
Creo que inicializaste un repositorio dentro del repositorio, mi recomendación es que crees un nuevo pull request con los cambios de tu carpeta de usuario de Discord.

2023-04-28 14:14 UTC, kendar9 commented on github-profiles
listo profe ya elimine el  subrepositorio para  poder estar  en e l  merge , gracias.

2023-07-18 13:59 UTC, glrodasz commented on github-profiles
Aun hace falta remover la carpeta `node_modules`

2023-07-18 20:00 UTC, closed without merging