Primer commit con markdown
undefined-academy/semana-1 pull request #393
Opened 2023-03-11 23:43 UTC by Luchonathor

2023-03-12 01:48 UTC, jaiver-1 approved these changes
El primer ejercicio esta de acuerdo a las especificaciones

2023-03-12 01:48 UTC, jaiver-1 commented on github-profiles/Luchonathor-2123.md
> +# QUIEN SOY
Esta muy bien el perfil.

2023-03-12 03:55 UTC, nobody-redhawk requested changes
# Recomendaciones
1. Detallar el paso a paso del desarrollo de los ejercicios en la descripcion.
2. Eliminar el archivo `Luchonathor-2123.md` ya que la informacion está en el archivo README.md
3. Crear el archivo `style.css` para estilizar el contenido del archivo `index.html`

2023-03-14 04:05 UTC, Luchonathor commented
> # Recomendaciones
> 1. Detallar el paso a paso del desarrollo de los ejercicios en la descripcion.
> 2. Eliminar el archivo `Luchonathor-2123.md` ya que la informacion está en el archivo README.md
> 3. Crear el archivo `style.css` para estilizar el contenido del archivo `index.html`

## Gracias por la observación
No había lleagado esta parte del trabajo, acabo de subirlo, espero sea de tu agrado.

2023-03-14 14:50 UTC, nobody-redhawk approved these changes

2023-08-08 02:11 UTC, closed without merging