Mi perfil de Github
undefined-academy/semana-1 pull request #397
Opened 2023-03-12 02:38 UTC by Veysia

Me costó un poco saber como poder hacer el pull request porque aun estoy aprendiendo a manejar la terminal y todos los comandos pero creo que he conseguido hacerlo. 
También al empezar a trabajar este ejercicio lo que más me costó fue que no estaba en la carpeta correcta ya que este repositorio lo incluí clonado en otra carpeta, y al trabajar desde otro directorio me salía el siguiente mensaje.

`fatal: not a git repository (or any of the parent directories): .git`

Si a alguno le sale este error, es que simplemente no están en la carpeta correcta. Espero que les sea de ayuda ♥ :relieved:

---
## Para hacer este ejercicio se requería lo siguiente: ##

1. Hacer un *fork* del repositorio https://github.com/undefined-academy/semana-1.
2. Clonar tu repositorio *"forked"* en tu carpeta de HOME.
3. Agregar allí un archivo **markdown** de tu perfil de **GitHub**, dentro de la carpeta **github-profiles** y el nombre de archivo debe ser tu usuario de Discord incluyendo el tag numérico (pero cambiando # por -) .
4. Incluyir dentro del archivo un link que nos lleve directamente a tu perfil de GitHub.
5. Hacer commit del archivo.
6. ir al repositorio original y crear tu primer Pull Request [^1]. 
7. Rellenar la descripción del Pull Request, escribe cómo fue el proceso de resolver este ejercicio, usar Markdown.

[^1]: aunque cuando haces el commit te aparece en la parte de arriba un mensaje como que puedes crear un pull request, aquí es donde pensé que no me aparecian los cambios al hacer commit, por lo que no hace falta ir al repositorio original desde donde se hizo el *fork*.

2023-03-12 19:05 UTC, FranBichego approved these changes
Buen trabajo

2023-03-13 19:10 UTC, Veysia commented
> Buen trabajo

Muchas gracias :)

2023-03-13 19:34 UTC, joaquinesteban commented
> Muchas gracias :)
Genial esta todo ok, lo unico que falta es dentro del README.md poner toda tu presentacion echa en markdown que hicimos en clase con el profesor en https://dillinger.io/

2023-03-15 22:01 UTC, Veysia commented
> 

si, es que se me borro sin querer, creo que ya lo volví a poner. Muchas gracias

2023-03-19 23:26 UTC, julietalazzaro approved these changes
Hola! Esta muy bueno el sitio, te agregue algunos comentarios para tener en cuenta, espero te ayude. Saludos

2023-03-19 23:26 UTC, julietalazzaro commented on github-profiles/νєуѕια-8225/style.css
> +    font-family: poppins;
Agregaría otras fuentes de "fallback" por si no llega a cargar la del servidor de google font

2023-03-20 10:04 UTC, aitorias approved these changes

2023-03-20 10:04 UTC, aitorias commented on github-profiles/νєуѕια-8225/README.md
Muy completo el README, genial!

2023-03-20 17:59 UTC, joaquinesteban approved these changes
Quedo todo Perfecto!!

2023-03-20 18:37 UTC, cadifilippo commented
@Veysia tienes conflictos al haber editado el readme base de la carpeta github-profiles, corrige eso para que podamos aceptar tu PR

2023-04-02 19:57 UTC, glrodasz requested changes

2023-04-02 19:57 UTC, glrodasz commented on README.md
Esta muy bien, lo único es que este archivo no debe ser removido.

2023-08-08 02:11 UTC, closed without merging