Add Profile Yolcar#7642
undefined-academy/semana-1 pull request #4
Opened 2023-03-03 05:07 UTC by Yolcar

Casi nunca he usado `Markdown`, me agrada mucho aprender a usarlo, ya permite dar formato a los textos de manera rápida.

2023-03-09 04:18 UTC, Seujumon requested changes
**Muy bueno tu perfil.** 
Aún le falta al primer ejercicio poner al menos dos comandos alias. 
También veo que falta completar los dos ejercicios siguientes, que serían pasar el md a HTML y luego agregarle CSS.

2023-03-20 01:07 UTC, Juanmiyo0696 requested changes

2023-03-20 01:07 UTC, Juanmiyo0696 commented on github-profiles/Yolcar-7642.md
>  | npm install   | Install packages to project       |
Hola, recuerda que son 5 comandos para pasar el readme

2023-03-20 01:09 UTC, Juanmiyo0696 commented
> Casi nunca he usado `Markdown`, me agrada mucho aprender a usarlo, ya permite dar formato a los textos de manera rápida.

Y aquí recuerda añadir los pasos que diste para hacer estos procesos

2023-03-26 20:21 UTC, merged