Primer Pull Request
undefined-academy/semana-1 pull request #40
Opened 2023-03-04 01:44 UTC by Skydeer94

## DESARROLLO DEL EJERCICIO

La mayoría del ejercicio me fue muy bien, hasta que llegue a la parte de generar el ***"git push -u origin main"*** , el cual me generaba el siguiente error:

1. ! [rejected]        main -> main (fetch first) error: failed to push some refs to 'github.com:Skydeer94/semana-1.git'.

## SOLUCIÓN
Para solucionarlo tuve que investigar porque se generaba este error y lo logre usando los siguientes códigos:

1. git config pull.rebase false
2. git pull origin main --allow-unrelated-histories
3. Repetir el git push -u origin main

Al parecer se trataba de un error generado por unos commits que se habían realizado en el repositorio original y que a la hora de yo generar mi código no los estaba teniendo en cuenta.

Me encuentro muy motivado para continuar aprendiendo en este bootcamp, agradezco todo el conocimiento que nos están brindando.

2023-03-09 18:31 UTC, kendar9 requested changes

2023-03-09 18:31 UTC, kendar9 commented on Steven-Angel-6151.md
> +# Alvaro Steven Angel Chaves
este archivo se tiene  que  llamar  `README.md`  y  tiene que estar dentro de la carpeta con tu  usario de discord.

2023-03-20 20:12 UTC, Juanmi72 commented
Buen trabajo

2023-03-20 20:13 UTC, Juanmi72 approved these changes
Buen trabajo

2023-03-20 21:32 UTC, nbarbettim commented on steven-angel-6151/README.md
> +# Alvaro Steven Angel Chaves
Me parece que el archivo md se encuentra muy bien estructurado y contiene todo lo visto en el Bootcamp, buen trabajo Steven.

2023-04-12 09:14 UTC, glrodasz requested changes

2023-04-12 09:14 UTC, glrodasz commented on .gitkeep
Este archivo no debería ir.

2023-07-18 20:02 UTC, glrodasz commented
@Skydeer94 por alguna razón los tests de este PR no están pasando, podrías por favor actualizar tu branch local, instalar dependencias `npm install` y luego ejecutar `npm run test` y revisar que puede estar pasando.

Si necesitas apoyo con esto, puedes por favor pedir ayuda en Discord, pero a simple vista el PR está bien, solo esta el detalle del test.

2023-09-13 02:02 UTC, closed without merging