Mi perfil de GitHub
undefined-academy/semana-1 pull request #400
Opened 2023-03-12 04:35 UTC by MatiasCusinato

En este proceso se resolvió el ejercicio dos

2023-03-15 13:21 UTC, EdwinOrtizCantillo commented on github-profiles/mmcusinato-12.md
Buenos días Matías esta bien el Markdown, hubieras colocado tus conocimientos en un listado

2023-03-15 13:21 UTC, EdwinOrtizCantillo commented on github-profiles/mmcusinato-12.md
Como sugerencia en la parte de alias, en vez de colocar Comando deberias colocar alias para que el comando fuera independiente

2023-07-18 15:02 UTC, glrodasz requested changes

2023-07-18 15:02 UTC, glrodasz commented on github-profiles/mmcusinato-12.md
Este archivo no debería ir.

2023-08-08 02:11 UTC, closed without merging