Mi perfil de GitHub
undefined-academy/semana-1 pull request #403
Opened 2023-03-12 07:27 UTC by JohaIles

Realmente no fue facil, realizar el proceso, sobretodo la parte del Pull request, me senti perdida, siento que voy lento pero bueno voy practicando en la terminal, familiarizandome con los comandos y realmente he cometido varios errores y nada vuelvo y empiezo desde el comienzo y borro lo que deba para intentar hacer el proceso de la manera correcta,  vpy en la 3 clase pero ha sido una experiencia maravillosa.

2023-03-12 17:01 UTC, yolombana reviewed
Hola.
Me parece muy bien el avance que llevas.
Por favor agrega el html y el css con los estilos para poder aprobartelo.

2023-03-13 13:37 UTC, yolombana reviewed
Hola. 
Buen trabajo.
Por favor agrega la hoja de style css para darlo por aprobado.

2023-03-20 04:04 UTC, JohaIles commented
hola casi que no puedo agregar la hoja de CSS y sabes no fue por la realizacion de la hoja en si, si no por el commit y el push, realmente no se que paso pero no me enviaba la informacion, no me guardaba la ruta, no se su no me ubicaba donde era, no se realmente, pero lo importante fue que lo hice y creo que quedo bien, esta dentro de github-profiles)/Joha1701-9119/
Quedo atenta y perdón la demora, espero me rinda de aqui en adelante.

2023-03-20 22:44 UTC, gustavo-arana approved these changes
Excelente trabajo, veo que organizaste toda los archivos y los cambios sugeridos por el canal. Sigue asi 🔥🔥🔥🔥

2023-03-21 01:06 UTC, MauBedoya requested changes
El `README.md` se ve bien, solo diría que corrijas el tema de la carpeta que no debería estar.

2023-03-21 01:06 UTC, MauBedoya commented on github-profiles/Joha1701-9119/index.html
también te recomendaría que vayas perfilando más el contenido de tu html hacia el contenido que puedes encontrar en una hoja de vida o un portafolio.

2023-03-21 01:06 UTC, MauBedoya commented on .vite/deps_temp_bf74e80c/package.json
al parecer se te coló una carpeta que no debería estar aquí, la que contiene este archivo `.json` y se llama `.vite` 👀

2023-03-21 19:05 UTC, camilasilvab commented
Si te sirve, cuando agregas un archivo nuevo al repositorio debes usar git add nombreArchivo.css para que el archivo se adhiera al repositorio. Entonces el flujo seria: 

git add archivo
git commit -am "El mensaje de commit"
git push origin main (Para enviar los cambios al repositorio aca en github) 

Cualquier duda me puedes preguntar en el discord

2023-03-24 01:22 UTC, JohaIles commented
Buenas noches, se genero un conflicto con un archivo README.md por lo cual opte por borrar lo hecho y volver a subirlo por commits  separados, me ayudan por fa con el aprobado para que puedan hacer merge.
muchas gracias!

2023-03-24 01:22 UTC, gustavo-arana approved these changes
Super !!!

2023-03-24 15:26 UTC, camilasilvab approved these changes

2023-03-24 16:51 UTC, MauBedoya approved these changes

2023-07-18 10:14 UTC, merged