Crear mi curriculum
undefined-academy/semana-1 pull request #404
Opened 2023-03-12 14:13 UTC by bvirreyra

2023-03-13 00:52 UTC, bvirreyra commented
# ***Perfil Boris Virreyra***
## Tareas cumplidas
* [x] Crear Perfil
* [x] Agregar link para visitar mi perfil
* [x] Hacer commit
* [x] Hacer Pull request
* [x] Agregar comentario con markdown

2023-03-13 01:05 UTC, bvirreyra commented
# ***Perfil Boris Virreyra***
## Tareas cumplidas
* [x] Crear Perfil
* [x] Agregar link para visitar mi perfil
* [x] Hacer commit
* [x] Hacer Pull request
* [x] Agregar comentario con markdown

2023-04-03 03:29 UTC, miguel7g approved these changes

2023-04-03 03:29 UTC, miguel7g commented on github-profiles/bvirreyra-0159/README-0159.md
excelente

2023-04-03 19:06 UTC, LichtEwig commented
genial

2023-04-03 19:07 UTC, LichtEwig approved these changes
muy bien!

2023-07-18 13:06 UTC, glrodasz requested changes
Los archivos .avif no deberian estar por fuera de tu carpeta de usuario.

2023-07-28 02:12 UTC, closed without merging