hoja de migue7
undefined-academy/semana-1 pull request #408
Opened 2023-03-12 16:21 UTC by miguel7g

2023-03-12 16:37 UTC, santiago01est commented
Excelente Trabajo!

2023-03-12 19:23 UTC, LichtEwig approved these changes
Quedo genial empezar desde cero y mira todo lo que avanza

2023-04-03 03:25 UTC, bvirreyra requested changes

2023-04-03 03:25 UTC, bvirreyra commented on github-profiles/migue7#9741/index.html
Excelente trabajo!

Tal vez un poco más de CSS para que tu página quede más llamativa

2023-04-03 03:53 UTC, bvirreyra approved these changes

2023-04-03 03:53 UTC, bvirreyra commented on github-profiles/migue7#9741/index.html
Maravilloso!

2023-04-05 20:46 UTC, miguel7g commented
El dom, 2 abr 2023 a las 23:53, Boris Virreyra ***@***.***>)
escribió:

> ***@***.**** approved this pull request.
> ------------------------------
>
> On github-profiles/migue7#9741/index.html
> <https://github.com/undefined-academy/semana-1/pull/408#discussion_r1155458959>
> :
>
> Maravilloso!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-1/pull/408#pullrequestreview-1368252872>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6K525WBC7GQPUDEKEIX23DW7JCU5ANCNFSM6AAAAAAVYGOTXA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-18 14:26 UTC, closed without merging