[ES] Agregado de archivo markdown de perfil / [EN] Adding markdown profile file
undefined-academy/semana-1 pull request #41
Opened 2023-03-04 01:53 UTC by jpaddeo

# [ES] Descripción
Se adjunta archivo markdown con README del repositorio personal de [jpaddeo](https://github.com/jpaddeo).

## Proceso para llegar al resutlado

1. Hacer un "fork" del repositorio propuesto por el profesor: [undefined-academy/semana-1](https://github.com/undefined-academy/semana-1.git).
2. Hacer un checkout local de dicho repositorio nuevo (fork).
3. Realizar los cambios sugeridos (crear archivo `<nombre_user_discord>-<id_user_discord>.md`).
4. Comitear los cambios en repostorio local (stage files => commit).
5. Pushear los cambios al respositorio remoto u origin (push).
6. Generar Pull Request (PR) a repositorio upstream.
7. Llenar la descripción de la PR.

# [EN] Description
I attach README markdown file of my personal repository [jpaddeo](https://github.com/jpaddeo).

## Process

1. Make a fork of upstream repository [undefined-academy/semana-1](https://github.com/undefined-academy/semana-1.git).
2. Make a local checkout of this forked repository.
3. Make suggested changes (create file called `<username_discord>-<userid_discord>.md`).
4. Commit changes on local repository (stage files + commit).
5. Push changes to remote repository (origin).
6. Make Pull Request to upstream repository.
7. Fill PR description.

2023-03-16 15:29 UTC, EvanaSabatella1989 requested changes

2023-03-16 15:33 UTC, jpaddeo commented on github-profiles/jpaddeo-3681/README.md
> +
Hola Evana!  Muchas gracias por tu comentario!

Te comento...hay etiquetas html en principio porque es posible incluirlas (Markdown lo permite) y luego porque si bien podría haber utilizado el formato "markdown" para incluirlas no hubiera podido ajustar el tamaño (ancho y largo) de las mismas, la única forma (que yo conozco hasta ahora) de hacer eso en markdown es con el tag img de html.

Si conoces otra forma a disposición para que me la comentes...y nuevamente te agradezco el feedback!

2023-03-16 15:50 UTC, EvanaSabatella1989 commented on github-profiles/jpaddeo-3681/README.md
> +
Ah ok, si estuve viendo y esta excelente. No se mucho de Markdown aún, pero se que en los slides hay un link hacia una página, por ahí encuentras tu respuesta. Muchos Éxitos

2023-03-21 00:50 UTC, pablo-alex approved these changes
Correctamente aplicado el conocimiento de la semana 1, muy buen diseño y estilos!

2023-03-21 01:51 UTC, julietalazzaro approved these changes

2023-03-21 01:51 UTC, julietalazzaro commented on github-profiles/jpaddeo-3681/README.md
> +![github contribution grid snake animation](https://raw.githubusercontent.com/jpaddeo/jpaddeo/output/github-contribution-grid-snake-dark.svg#gh-dark-mode-only)
Muy buena la animacion de las contribuciones ☺️

2023-03-21 01:51 UTC, julietalazzaro commented on github-profiles/jpaddeo-3681/index.html
> +    <style>
El css es una "buena práctica" separarlo en un archivo .css aparte

2023-03-22 13:24 UTC, Alexisdc5 approved these changes
Muy buen trabajo, solo como sugerencia aplicar los style css en archivo separado,

2023-07-18 14:01 UTC, glrodasz commented
Hace parte el archivo de CSS.

2023-07-18 14:06 UTC, closed without merging