ejercicio ejercicio-semana1-clase2
undefined-academy/semana-1 pull request #410
Opened 2023-03-12 19:30 UTC by jayler0203

## pasos para resolver el ejercicio
-Primero busque que era un fork(pense que era un comando)
-Clone el repositorio con ```git clone git@github.com:jayler0203/jayler0203.git ```
-Utilize cd para llegar hasta la carpeta para crear el archivo
-Con touch cree el archivo con mi nombre de usurio de discord
-Abri nano para editar el archivo
-Copie el link de mi perfil y lo que hice en el primer ejercicio
-Use el comando ```git add jayler-1407.md ``` ```git commit -m "ejercicio-semana1-clase2" ``` para hacer el commit
-Actualize el repositorio con ```git push```
-Hice unos cambios en el repositorio porque en link quedo como parte de la tabla

2023-03-12 19:34 UTC, Giohero approved these changes

2023-03-12 19:47 UTC, Giohero requested changes
Crea una nueva carpeta adentro de la carpeta github-profiles, esa carpeta se debe llamar igual que la de tu perfil jayler-1407, la ruta ahora te deberia quedar asi github-profiles,/jayler-1407 y dentro de tu carpeta jayler-1407 mete tu archivo jayler-1407.md

2023-03-14 05:17 UTC, Giohero approved these changes

2023-03-19 23:32 UTC, julietalazzaro approved these changes
Hola Jayler! Muy bien el sitio, sigue asi

2023-03-19 23:32 UTC, julietalazzaro commented on github-profiles/jayler-1407/index.html
> +    <title>index.html</title>
El titulo de la pagina es el texto que se visualiza en la pestaña del navegador, quizas podria tu nombre o algo que describa el sitio

2023-03-20 20:25 UTC, merged