Se agrega enlace de perfil de GitHub (fran-rs)
undefined-academy/semana-1 pull request #412
Opened 2023-03-12 20:44 UTC by fran-rs

# Ejercicio semana 1
### Pasos:
1. Hice un fork del [repositorio](https://github.com/undefined-academy/semana-1).
2. Cloné mi repositorio _forked_ en mi carpeta **HOME**.
3. Creé un archivo markdown  y le puse el nombre de mi _perfil de Discord_, incluyendo el tag.
4. Agregué al archivo un enlace a mi **[perfil de GitHub](https://github.com/fran-rs)**.
5. Hice un _commit_ del cambio.
6. Hice un _push_ a mi repositorio _forked_.
7. Hice un **Pull Request** al repositorio del paso **1**.

2023-03-14 04:08 UTC, Codemonster808 requested changes
Is missing having the 2 files an creating the folder with your discord name and changing the markdown archive for readme.md and apply the HTML  and the CSS  to the index.html that is the archive that you are pushing here

2023-03-21 05:58 UTC, gurrutia15 approved these changes
se ve bien, buen trabajo

2023-03-21 15:17 UTC, QuirogaPau reviewed
Estas haciendo un buen trabajo!! 
Para completar la semana faltaria los estilos de CSS que con la ayuda de la guía [Diseño Web en 4 Minutos](https://jgthms.com/web-design-in-4-minutes) tu HTML se va a ver mejor. 
Espero aportar a tu proceso de aprendizaje con los comentarios. Cualquier duda, no dudes en consultar.
Saludos

2023-03-21 15:17 UTC, QuirogaPau commented on github-profiles/Fransilandia-7372/index.html
> +    <h1> Hola!. <a href="https://github.com/fran-rs">Soy María Francisca Riquelme</a> ,</h1>
Como adelanto (esto lo vas a poder ver en la semana 2 con "HTML semántico") los enlaces se pueden poner dentro de una etiqueta `<nav>` que es etiqueta de navegación.

2023-03-21 19:21 UTC, warsant approved these changes
Muy bien estructurado y ampliado tu código, pero es recomendable tener los estilos en uno o varios archivos separados, esto con la finalidad de que el código sea de fácil comprensión para otro desarrollador.

2023-03-21 19:21 UTC, warsant commented on github-profiles/Fransilandia-7372/index.html
>  <html lang="en">
Seria bueno que colocaras el estilo en un archivo aparte del tipo .css, esto para que sea más legible y entendible tu código, ya que como se puede observar son muchas línes de código HTML y como tienes los estilos incluidos en el código HTML, se hace pesado y en ocasiones dificil de entender

2023-03-23 01:32 UTC, kiltro-dev commented
bueno

2023-03-23 01:47 UTC, kiltro-dev approved these changes

2023-03-23 12:07 UTC, merged