este es el primer commit de Johns-6483.md
undefined-academy/semana-1 pull request #414
Opened 2023-03-12 22:26 UTC by johns70

## Challenge Semana 1
*  hacer fork, clonar Github-profefiles en Home
*  hacer el archivo con el name de discord y su contenido en Markdown
*  hacer commit de los cambios 
*  hacer push a undefined-academy/semana-1
*  dar click en contribute
*  dar click en open pull 
*  dar click en create pull Request

2023-03-13 21:47 UTC, AlfonsoIng requested changes

2023-03-13 21:47 UTC, AlfonsoIng commented on github-profiles/Johns-6483/README.md
> +
Hola!, Según el ejercicio te faltaría colocar al menos 3 comandos que usas en la consola de Linux o de Visual Studio Code.

2023-03-13 21:47 UTC, AlfonsoIng commented on github-profiles/Johns-6483/index.html
> +<head>
Hola!, si estas en el ejercicios de la semana 1 clase 4, no olvides seguir las instrucciones de Diseño en en 4 minutos de Jeremy Thomas esta en ingles pero es bastante intuitivo.

2023-03-14 04:05 UTC, Codemonster808 approved these changes
quedo bien el markdown

2023-03-26 18:39 UTC, johns70 commented on github-profiles/Johns-6483/index.html
> +<head>
# hola Broo
## ya termine haber que les parece y ya agregue los comandos de Terminal

2023-03-26 18:40 UTC, johns70 commented on github-profiles/Johns-6483/index.html
> +<head>
hola broo, Listo ya termine la tarea XD haber que les parece me dicen para ver que le cambio, Gracias

2023-03-27 21:44 UTC, AlfonsoIng approved these changes

2023-07-19 03:31 UTC, closed without merging