My first activity
undefined-academy/semana-1 pull request #415
Opened 2023-03-12 22:50 UTC by sebasricop

# 👨‍💻 Sebastián Rico Pérez

#### 🎉Es una experiencia muy buena, aun me falta mucho para arpender sobre Git pero para eso estamos aca, a darle con toda

2023-03-17 16:25 UTC, Byron2016 requested changes
Hola, @sebasrico-3054
- [x] Archivo sebasrico-3054.md: **No** debería estar directamente en carpeta Github-profiles
- [x] Carpeta .vite: **No** debió haber sido subida. Debes hacer en tu repositorio un `git fetch` para traer los cambios de la carpeta principal y luego un `git pull origin main` para bajarlos a tu repositorio, con eso ya te va a ignorar el .vite. Sería bueno consultes como quitar el .vite de tu commit x q eso ya se subió, se me ocurre q antes de hacer los pasos del git fetch y pull, borres la carpeta, subas el commit, y luego si hagas lo indicado inicialmente.- [x] Nombre de carpeta: Correcto
- [x] README.md: me pareció que está chévere y se ve muy bien con las imágenes que has puesto.
- [x] En cuanto a los commits de pronto que sean más descriptivos, pero para la próxiima, no para esta vez, yo desconozco como cambiar la descripción de los commits si de pronto aprendes, no te olvides de contarme.

2023-03-17 16:25 UTC, Byron2016 commented on github-profiles/sebasrico-3054.md
Hola, @sebasrico-3054
- [x] Archivo sebasrico-3054.md: **No** debería estar directamente en carpeta Github-profiles

2023-03-17 16:25 UTC, Byron2016 commented on github-profiles/sebasrico-3054/css/style.css
Hola, @sebasrico-3054
- [x] Carpeta .vite: **No** debió haber sido subida. Debes hacer en tu repositorio un `git fetch` para traer los cambios de la carpeta principal y luego un `git pull origin main` para bajarlos a tu repositorio, con eso ya te va a ignorar el .vite. Sería bueno consultes como quitar el .vite de tu commit x q eso ya se subió, se me ocurre q antes de hacer los pasos del git fetch y pull, borres la carpeta, subas el commit, y luego si hagas lo indicado inicialmente.

2023-03-17 16:25 UTC, Byron2016 commented on github-profiles/sebasrico-3054/README.md
Hola, @sebasrico-3054
- [x] README.md: me pareció que está chévere y se ve muy bien con las imágenes que has puesto.

2023-03-18 04:12 UTC, sebasricop commented on github-profiles/sebasrico-3054.md
Hola Byron, mil gracias por tu feedback, ya corregí lo de la carpeta vite, lo tendré en cuenta para la próxima, solo tengo una duda, este archivo donde debe ir exactamente   sebasrico-3054.md?

2023-03-18 04:13 UTC, sebasricop commented on github-profiles/sebasrico-3054/css/style.css
Gracias, ya fue resuelto.👌

2023-03-18 04:13 UTC, sebasricop commented on github-profiles/sebasrico-3054/README.md
Gracias Byron !!!🧑‍🎓

2023-03-18 15:36 UTC, Byron2016 commented on github-profiles/sebasrico-3054.md
Hola Sebas, que chévere lo hallas podido haber corregido. El archivo sebasrico-3054.md ya no deberías ponerlo x que fue renombrado a README.md, pero si lo deseas conservar debería ir dentro de tu carpeta sebasricoa-3054

2023-03-22 12:54 UTC, Byron2016 requested changes
Hola sebasrico-3054, aún veo el archivo sebasrico3054.md fuera de la carpeta sebasrico-3054. Justo ayer comentaba Guillermo que deben ser eliminados.

2023-03-22 13:11 UTC, dfm555 approved these changes
¡Buen trabajo Sebas!

2023-03-22 13:12 UTC, merged

2023-03-22 13:14 UTC, sebasricop commented
Gracias Fernando 👌