chore: se agrega a perfil de github de kiltro-dev-2143
undefined-academy/semana-1 pull request #421
Opened 2023-03-13 03:03 UTC by kiltro-dev

# Ejercicio Semana 1, clase dos
### Los pasos ejecutados son los siguientes:

1. Desde el [repositorio base](https://github.com/undefined-academy/semana1), realicé un fork en mi cuenta de Github
2. Cloné mi [repositorio forkeado](https://github.com/kiltro-dev/semana-1) desde mi local
3. Cree el archivo **kiltro-dev-2143.md** dentro del directorio **github-profiles**
4. Agregué un enlace que lleva a [mi perfil de GitHub](https://github.com/kiltro-dev)
5. Agregué los cambios al **staging area** con el comando **git add .**
6. Envié los cambios a mi [repositorio forkeado](https://github.com/kiltro-dev/semana-1) con el comando **git push**
7. Finalmente, en la página del [repositorio base](https://github.com/undefined-academy/semana1), hice un **Pull Request** para incluir los cambios de mi [repositorio forkeado](https://github.com/kiltro-dev/semana-1) en el [repositorio base](https://github.com/undefined-academy/semana1).

#### Saludos :wave:

2023-03-14 18:24 UTC, EvanaSabatella1989 requested changes

2023-03-14 18:24 UTC, EvanaSabatella1989 commented on github-profiles/kiltro-dev-2143.md
> +
Hola, este documento debe ser echo en Markdown, por eso es .md pero estoy viendo que tiene formato html

2023-03-28 01:35 UTC, kiltro-dev commented on github-profiles/kiltro-dev-2143.md
> +
Gracias por el feedback!, ya lo corregí, revísalo por favor

2023-03-28 13:48 UTC, lllariogonzalez approved these changes
✔️

2023-03-28 13:50 UTC, dfm555 requested changes
@kiltro-dev podrías darle estilos al html con styles.css

2023-03-28 13:51 UTC, dfm555 requested changes

2023-03-28 13:51 UTC, dfm555 commented on github-profiles/kiltro-dev-2143/index.html
> +    <style>
Mueve estos estilos a un archivo

2023-03-28 14:18 UTC, dfm555 commented on github-profiles/kiltro-dev-2143/index.html
> +    <style>
@kiltro-dev esperaría que siguieras la recomendación para poder mezclar tu PR

2023-03-28 14:22 UTC, dfm555 commented on github-profiles/kiltro-dev-2143/index.html
> +    <style>
![image](https://user-images.githubusercontent.com/6820026/228268911-ff7e6463-c9e2-44dd-b9ce-98313b49b1e3.png)

@kiltro-dev no olvides de realizar este ejercicio.

2023-03-28 14:38 UTC, dfm555 requested changes
Realizar el ejercicio 4
https://jgthms.com/web-design-in-4-minutes/

2023-03-28 15:20 UTC, kiltro-dev commented on github-profiles/kiltro-dev-2143/index.html
> +    <style>
Feedback listo

2023-03-28 15:24 UTC, dfm555 approved these changes
Buen trabajo, me gustó tu github profile 🦾

2023-03-28 15:25 UTC, merged