Mi perfil de github
undefined-academy/semana-1 pull request #426
Opened 2023-03-13 16:06 UTC by facu1391

Proceso de mi peril: 

* Primero entré al repositorio origen, en la pestaña Code copié el link https para clonar.
* En la terminal Ubuntu entre a mi carpeta y usé git clone https://github.com/richardjma/semana-1.git para clonar el repositorio dentro de mi home.
* Luego abrí VS Code en la carpeta de semana-1 del repositorio clonado con code .
* Creando un archivo con mi nombre de discord usando touch kalenz-6327.md dentro de la carpeta de github-profiles.
* Dentro del archivo puse mi perfil realizado en MarkDown junto al link que dirige al mi perfil de GitHub.
* Después con: git status - git add . - git commit -m " Mi perfil de Github" - git push actualicé el repositorio con el documento en mi perfil de Github en línea.
* Por ultimo en la pestaña pull request del repositorio clonado en mi perfil usé new pull request para actualizar el repositorio original y culminar con el ejercicio.

2023-03-13 17:48 UTC, RREYES0424 reviewed
Hola Facu!
Como recomendación el archivo de Markdown, las tablas podrían estar alienadas, para que se puedan leer mejor al editar

2023-03-13 17:49 UTC, RREYES0424 requested changes
Hola Facu!
Como recomendación el archivo de Markdown, las tablas podrían estar alienadas, para que se puedan leer mejor al editar

2023-03-13 20:47 UTC, facu1391 commented
Muchas gracias por la corrección, ya lo estaré modificando.

2023-03-13 20:51 UTC, facu1391 commented
> Hola Facu! Como recomendación el archivo de Markdown, las tablas podrían estar alienadas, para que se puedan leer mejor al editar

Hola Ricardo! muchas gracias por la corrección, ya lo estaré modificando.

2023-03-15 01:32 UTC, VicBocanegra25 approved these changes
Estimado Facundo, 

Te dejo mi review: 

1.- Bien ambos archivos indexhtml y el main.css, se cumple con lo solicitado en los ejercicios. 

2.- Me gustó cómo formateaste tu página, es de fácil lectura y me gustó que agregaste un enlace a tus redes sociales. Tal vez como comentario puramente subjetivo, me gustaría que esa imagen que agregaste (la que tiene el código), la subieras hasta el comienzo. 

3.- En general, es un muy buen trabajo y te deseo éxito en tus futuros commits. 

Sigamos en esto, saludos desde México hasta la Argentina!

2023-03-16 22:06 UTC, facu1391 commented
> Estimado Facundo,
> 
> Te dejo mi review:
> 
> 1.- Bien ambos archivos indexhtml y el main.css, se cumple con lo solicitado en los ejercicios.
> 
> 2.- Me gustó cómo formateaste tu página, es de fácil lectura y me gustó que agregaste un enlace a tus redes sociales. Tal vez como comentario puramente subjetivo, me gustaría que esa imagen que agregaste (la que tiene el código), la subieras hasta el comienzo.
> 
> 3.- En general, es un muy buen trabajo y te deseo éxito en tus futuros commits.
> 
> Sigamos en esto, saludos desde México hasta la Argentina!

Muchas gracias Víctor, muchos éxitos para vos también! Saludos cordialmente desde Argentina a  México

2023-04-27 13:03 UTC, merged