Oiranca#1500 : git-profile first week
undefined-academy/semana-1 pull request #438
Opened 2023-03-14 13:15 UTC by Oiranca

1. Realized a fork from the [repository](https://github.com/undefined-academy/semana-1.git)
2. Made Oiranca-1500 directory
3. Moved the Readme.md file
4. Made some changes in the Readme.md file
5. Wrote into the terminal the command 'git add .' and after the command' git commit -a'
6. Finally wrote the command  'git push' and created a new **pr**

2023-03-15 03:44 UTC, OrcaCl requested changes
Hola, la carpeta donde tiene que ir index.html es la misma donde está README.md, o sea, debes sacarlo de src, para poder completar el ejercicio como fue solicitado originalmente.

2023-03-15 03:44 UTC, OrcaCl commented on github-profiles/Oiranca-1500/README.md
> +| touch            |Crea un archivo nuevo dada una ruta o solo el nombre si la ruta es donde estás ejecutando el comando|
Si escribes 'touch' por si solo te va a lanzar error. Debes escribir a continuación del comando, el nombre del archivo o la ruta+nombre archivo. Sugerencia: touch  new-file.md

2023-03-15 03:44 UTC, OrcaCl commented on github-profiles/Oiranca-1500/README.md
> +|  mv<sup>2</sup>  |Comando para mover arcvhivo o carpeta dada una ruta inicial y una ruta final  |
Creo que tienes un error de tipeo. El comando debería ser "mv origen destino".

2023-03-15 03:44 UTC, OrcaCl commented on github-profiles/Oiranca-1500/src/index.html
> +            <th style="text-align:left">Comandos</th>
Si bien es cierto que Guillermo no entró en detalle sobre el uso de tablas, para sitios web no se recomienda usar estilos inline en el html.  Las tablas por omisión vienen con el texto alineado a la izquierda. Y si deseas que queden hacia otro lado, podrás hacerlo posteriormente en CSS. Este no es un error, solo una sugerencia. :)

2023-03-16 11:19 UTC, Oiranca commented on github-profiles/Oiranca-1500/src/index.html
> +            <th style="text-align:left">Comandos</th>
Corregido!! :smile:

2023-03-19 12:10 UTC, Oiranca commented on github-profiles/Oiranca-1500/README.md
> +|  mv<sup>2</sup>  |Comando para mover arcvhivo o carpeta dada una ruta inicial y una ruta final  |
lo que ves de <sup>2</sup> es para crear un subíndice porque el comando mv también se usa para cmabiar de nombre

2023-03-19 12:13 UTC, Oiranca commented on github-profiles/Oiranca-1500/README.md
> +| touch            |Crea un archivo nuevo dada una ruta o solo el nombre si la ruta es donde estás ejecutando el comando|
Ok, lo he corregido gracias

2023-03-19 16:25 UTC, closed without merging