steps
undefined-academy/semana-1 pull request #44
Opened 2023-03-04 02:35 UTC by jmanwel

- Fork repository
- clone repository
- create markdown file
- commit and push to remote
- pull request

2023-03-10 03:56 UTC, nobody-redhawk requested changes
# Cambios que hay que realizar:
1. Mover la carpeta `jmg-7520` a la carpeta `github-profile`.
2. Eliminar el archivo `jmg-7520.md` que hay dentro de la carpeta `github-profiles`, porque el contenido de este archivo está en `README.md`.
3. Crear un archivo `styles.css` dentro de la carpeta `jmg-7520` para estilizar el archivo `index.html` de tu perfil siguiendo los pasos del tutoria [Diseño Web en 4 minutos](https://jgthms.com/web-design-in-4-minutes).
4. Finalmente hacer `commit` y `push.`
5. Éxitos...

2023-03-10 22:57 UTC, nobody-redhawk approved these changes

2023-06-15 02:23 UTC, zulito93 commented on github-profiles/jmg-7520.md
Eliminar archivo para que ya que este fue reemplazado por el README.md que se encuentra en la carpeta renombrada con el usuario de Discord indicada en el ejercicio.

2023-06-15 02:23 UTC, zulito93 commented on github-profiles/jmg-7520/README.md
Descripción del perfil, cualidades y demás. No es necesario indicar en él md las respuestas a las preguntas indicadas en cada sesión. 
Alinear tabla para que viendo el código se pueda visualizar correctamente cada columna.

2023-06-15 02:25 UTC, zulito93 reviewed
Eliminar archivo md que se encuentra por fuera de la carpeta del usuario, alinear tabla en archivo README y organizar información incluida en el perfil.

2023-07-18 14:06 UTC, closed without merging