Mi perfil de GitHub
undefined-academy/semana-1 pull request #441
Opened 2023-03-14 16:13 UTC by Hernan4280

1. Hice fork del repositorio: semana-1
2. Clone el repositorio:
 - Aquí tuve un problema que lo resolví, después de investigar bastante, creando otra clave ssh, pero esta vez desde la terminal de ubuntu.
3. Cree un archivo con el nombre de mi perfil discord en la carpeta github-profiles
4. Agregue los cambios con git add .
5. Hice un commit:
 - Aquí tuve otro problema, que también pude resolver. Al parecer no había configurado mi email y mi nombre em git.
6. Hice un push.
7.  Por ultimo realice el pull request.

2023-03-18 05:57 UTC, DianaRussi requested changes

2023-03-18 05:57 UTC, DianaRussi commented on github-profiles/README.md
Muy buen trabajo pero debes de colocar los archivos dentro de una carpeta  que va dentro de github-profile con el nombre de usuario de tu discord (cambiar el # por -)

2023-03-18 05:57 UTC, DianaRussi commented on github-profiles/README.md
> +https://github.com/Hernan4280
En cuanto a tu perfil de git hazlo con la sintaxis para link
[*Texto representativo*](tu link de git)

2023-03-20 15:22 UTC, Hernan4280 commented on github-profiles/README.md
Muchas gracias. Ya corregí lo de la carpeta.

2023-03-20 15:26 UTC, Hernan4280 commented on github-profiles/README.md
> +https://github.com/Hernan4280
Gracias. Corregido.

2023-03-20 16:01 UTC, DianaRussi approved these changes
Listo todo ok

2023-03-20 16:25 UTC, jaardila-3 reviewed
Porque nombraste la carpeta: Hernan4280? debe ser tu usuario de discord y en vez de #, usar un -; además creo que le falta mas info, es tu CV, por lo menos tus estudios y experiencia laboral

2023-03-20 16:38 UTC, julietalazzaro requested changes
Hola Hernan, como comento un compañero tu carpeta debería tener de nombre el usuario de Discord, no el de github, para poder ubicarte por chat. Fuera de eso va muy bien, faltaria la tabla de comandos y alias del markdown en el html.

2023-03-21 02:34 UTC, julietalazzaro approved these changes

2023-03-21 02:43 UTC, jaardila-3 approved these changes
Hola, los comandos mas utilizados eran de linux terminal, no de markdown, pero el resto esta muy bien.

2023-03-21 17:29 UTC, merged