Mi perfil de github
undefined-academy/semana-1 pull request #450
Opened 2023-03-15 02:00 UTC by profpablonicolas

* Realizo fork del repositorio
* Busco en la terminal la ubicacion home
* Uso git clone para clonar el repositorio fork
* Ingreso a github-profiles 
* Ejecuto echo "https://github.com/profpablonicolas" > profpablonicolasrdyk#7869.md
*Abro en code el archivo y agrego mi informacion de presentacion.
* Ejecuto git init, git status y git add.
* Hago  git commit -m "clase2 "
* Y finalizo con git log para chequear que se hizo el commit correctamente.
*Ejecuto git branch main para pasar a la rama main.
*hago un nuevo commit ya desde la rama main.
*Establezco git remote add origin  
*Hago el push
*Y finalizo con el pull

2023-03-15 03:53 UTC, OrcaCl reviewed
Mis comentarios son más sugerencias que corrección de errores.

2023-03-15 03:53 UTC, OrcaCl commented on profpablonicolasrdyk-7869/index.html
> +    <h1>Hola, mi nombre Es <a href="about.html">Pablo Nicolas Rudyk</a> </h1>
Hola. Si no tienes una página "about.html" construida, este link te lanzará un error. Te sugiero que apuntes a tu perfil de GH o crees una página about. Además se sugiere que uses rutas absolutas para los links, usando /about.html.

2023-03-15 03:53 UTC, OrcaCl commented on profpablonicolasrdyk-7869/index.html
> +        <img src= "perro.jpeg" width="300px" height="200px">
La ruta de la foto podría tener problemas si es relativa.

2023-03-15 05:14 UTC, OrcaCl requested changes
Estos ajustes de css pueden provocarte problemas con la herencia de estilos y que no te carguen correctamente las tipografías.

2023-03-15 05:14 UTC, OrcaCl commented on style.css
Ojo con repetir las modificaciones de estilo.  Estás cambiando los atributos de body en 3 partes diferentes.
Si no vas a usar los estilos de arriba del @import de google fonts pero no quieres borrarlos, puedes dejarlos como comentario, agregando `/** al inicio de lo que quieres dejar comentado, y **/ al final para cerrar`

Por otro lado, se recomienda que los @imports los dejes al inicio del archivo.css para que los "recoja" antes de esperar que existan o sean invocados más abajo.

2023-03-16 02:21 UTC, OrcaCl approved these changes
Ahí quedó bien.
:)

2023-03-19 20:55 UTC, profpablonicolas commented on style.css
Hola, ya modifique los styles, gracias por la observacion. saludos.

2023-07-08 02:46 UTC, closed without merging