Mi 1ra asignación
undefined-academy/semana-1 pull request #453
Opened 2023-03-15 13:31 UTC by Melisa-Herrera

## **Desde clonar repositorio a realizar mi 1er pull request**
Los comandos que más utilicé:
| Comandos |
|     -----       |
|      pwd      |
|        ls         |
|        cd       |
|     touch     |
|     mkdir     |
|      cd ../     |

A continuación para completar la actividad realicé los sig pasos:
1. Copiar en terminal https://github.com/undefined-academy/semana-1
2. Comando git clone
3. Comando git status
4. Comando git add .
5. Comando git commit -m ""
6. Comando git push origin main

2023-03-15 22:37 UTC, daniela03h approved these changes
hola, esta muy completo tu ejercicio, te felicito :+1:

2023-03-17 00:16 UTC, CaesarAlej24 requested changes

2023-03-19 05:24 UTC, Melisa-Herrera commented
> descripción tuya tipo CV.
> 3. Añade una tabla en Markdown (Obviamente) con al meno

2023-03-19 05:27 UTC, Melisa-Herrera commented
> hola, esta muy completo tu ejercicio, te felicito 👍

2023-03-19 05:57 UTC, Melisa-Herrera commented
Hola, muchas gracias por comentar @daniela03h y @CaesarAlej24, estoy aprendiendo y me cuesta mucho el navegar por el sitio, espero estar contestando en el lugar correcto y haber implementado y ejecutado los cambios pertinentes. Saludos :)

2023-03-19 09:35 UTC, Melisa-Herrera reviewed
Hola! Gracias por las sugerencias, espero haber corregido bien, saludos

2023-03-20 21:46 UTC, CaesarAlej24 approved these changes

2023-07-02 02:51 UTC, closed without merging