EJERCICIO 2
undefined-academy/semana-1 pull request #46
Opened 2023-03-04 03:00 UTC by joelhuba

* vine al repositorio
* cree el branch
* clone el repositorio en mi host
* cree un archivo de **MARKDOWN** en la carpeta github-profile
* agregue mi archivo de la primera clase
* agregue los cambio en la rama main con git add.
* cree el commit 
* luego lo subi con git push. 

_lo mas resumido sin la cantidad de errores que tuve_   __XD__

2023-03-07 16:39 UTC, joelhuba commented
#tarea 2.
*no pude inicializar git con el fork por ende clone de nuevo la carpeta
* cree la carpeta joelhuba-5339
* agregue los arhivos
* modificque el archivo para crear el index.html 
* lueg cree el commit y lo subi.

2023-03-09 18:46 UTC, fjquants commented on github-profiles/joelhuba-5339/README.md
> +|COMANDOS   |DEFINICION   |
Se recomienda cuadrar la tabla en markdown para que sea visualmente más legible

2023-04-08 14:05 UTC, joelhuba reviewed
# cambios realizados

2023-04-08 14:05 UTC, joelhuba commented on github-profiles/joelhuba-5339/README.md
> +|COMANDOS   |DEFINICION   |
gracias ya las arregle espero respuesta para ver si quedo bien

2023-04-23 13:49 UTC, DevOld112 requested changes
Solamente te falta agregar tu archivo css enlazado al HTML y estariamos listos con la semana-1 :)

2023-04-23 20:25 UTC, jorge9372 requested changes

2023-04-23 20:25 UTC, jorge9372 commented on github-profiles/joelhuba-5339/index.html
> +
Hola en el html también debes agregar la tabla con los principales comandos , y nombrar los alias.

2023-07-18 14:06 UTC, closed without merging