Mi perfil en markdown, mi perfil de github esta en el icono 😁
undefined-academy/semana-1 pull request #461
Opened 2023-03-16 07:24 UTC by StephanyCS1

# Hola, este es mi ejercicio de pull request

> Los pasos que hice para realizar el pull request desde la terminal son:

1. Hacer Fork del repo
2. Clonar el repo en la terminal
3. Crear mi capeta
4. Copiar el archivo .md con el comando cp
5. Comandos git add .
6. git commit -m 
7. git log
8. git push origin main

2023-03-16 16:35 UTC, EvanaSabatella1989 requested changes

2023-03-16 16:35 UTC, EvanaSabatella1989 commented on github-profiles/tefis96-9675/README.md
> +
Hola Stephany, bien tu Markdown. Puedes agregar alguna tabla para practicar

2023-03-16 17:22 UTC, StephanyCS1 commented on github-profiles/tefis96-9675/README.md
> +
Hola, muchas gracias por tu **feedback**, ya realicé los cambios 😁

2023-03-16 17:49 UTC, EvanaSabatella1989 approved these changes

2023-03-16 17:49 UTC, EvanaSabatella1989 commented on github-profiles/tefis96-9675/README.md
> +
Excelente. Felicitaciones y éxitos

2023-03-16 17:50 UTC, EvanaSabatella1989 commented on github-profiles/tefis96-9675/README.md
> +
Si quieres también me dejas tu feedback :)

2023-03-16 23:38 UTC, cristinacdm reviewed
Te he marcado un par de cosillas, no soy experta pero échale un vistazo por si hay que corregirlas ;)

2023-03-16 23:38 UTC, cristinacdm commented on github-profiles/tefis96-9675/index.html
> +    <p>Estoy iniciando en desarrollo, me estoy preparando para ser <strong>FullStack</strong> </p>
Otra opción en vez de hacer dos `p` sería añadir un `br` dónde quieras hacer el salto de línea, ya que la información forma parte del mismo párrafo, sería como punto y aparte.

2023-03-16 23:38 UTC, cristinacdm commented on github-profiles/tefis96-9675/index.html
> +        <span>SCRUM</span>
`Span` es un contenedor de línea que se una para dar estilo a una parte especifica por ejemplo de un párrafo, a nivel sintáxico no determina nada, es la versión en línea del ´div´

2023-03-16 23:38 UTC, cristinacdm commented on github-profiles/tefis96-9675/index.html
> +            <td>Comando</td>
la primera fila de una tabla lleva el elemento ´th´ **table head** que sería el encabezado de cada columna

2023-03-16 23:38 UTC, cristinacdm commented on github-profiles/tefis96-9675/index.html
> +            <td>Comando</td>
Lo mismo que la otra tabla

2023-03-17 08:25 UTC, cristinacdm approved these changes
Genial (sólo la última tabla los th en minúscula) good job!

2023-03-17 17:49 UTC, Byron2016 commented on github-profiles/tefis96-9675/README.md
Hola, @tefis96-9675
- [x] README.md: me pareció que  bien, se ve muy bonito con los emojis colocados. Buen trabajo.

2023-03-18 04:10 UTC, sebasricop commented on github-profiles/tefis96-9675/README.md
> +
Hola como estas Stephany, muy bien por corregir y querer seguir adelante, me pareció muy bacano tu trabajo

2023-03-20 19:06 UTC, merged