Pull request del markdown
undefined-academy/semana-1 pull request #472
Opened 2023-03-17 06:26 UTC by fgcas

## Proceso para hacer el pull request

1. El primer paso fue hacer un **fork** al repositorio de Undefines Academy, que se encuentra en este [Enlace](https://github.com/undefined-academy/semana-1)
2. Luego cloné el repositorio "forkeado" a mi repositorio local.
3. Añadir mi archivo markdown a directorio nombrado `FrankCasanova-2182` que representa a mi usuario de Discord.
4. Modifiqué el el archivo añadiendo el enlace de mi [Github](https://github.com/fgcas).
5. Añadí el archivo con `git add .` y a continuación hice un `git commit -m "text"`.
6. Lo que hice a continuación fue hacer un `git push` para subir los archivos al **repositorio remoto**
7. Una vez actualizado todo, hice el **Pull Request**.

2023-03-17 07:57 UTC, BingenWeb approved these changes

2023-03-18 18:28 UTC, RockoMdq requested changes
agregale algun icono o algun link a una red social

2023-03-20 03:31 UTC, fgcas commented
> agregale algun icono o algun link a una red social

**Gracias**, lo voy a tomar en cuenta 👍

2023-03-20 21:28 UTC, RockoMdq approved these changes

2023-03-21 17:05 UTC, JoeOsG commented on github-profiles/FrankCasanova-2182/main.css
> +}*/
Podrías quitar el codigo comentado que ya no piensas usar.

2023-04-02 07:18 UTC, merged