My profile github
undefined-academy/semana-1 pull request #474
Opened 2023-03-17 14:59 UTC by anghelitalo

TODO: process to PR

2023-03-20 23:32 UTC, Lmendev requested changes
No se ha completado el ejercicio

2023-03-21 01:58 UTC, anghelitalo commented
@Lmendev que paso falta para completar el ejercicio? para el index.?? puedes ser mas especifico gracias

2023-03-21 08:39 UTC, Lmendev requested changes

2023-03-21 08:39 UTC, Lmendev commented on github-profiles/angi-8078/angi-8078.md
> +# Commands Linux used before
Esta info no aparece en el `index.html`

2023-03-21 08:39 UTC, Lmendev commented on github-profiles/angi-8078/angi-8078.md
> +### Commands Alias
Tampoco esta sección

2023-03-21 08:39 UTC, Lmendev commented on github-profiles/angi-8078/index.html
> +    <h2> Experience as an SDET, domains E-commerce/testing web client-server,
Acá este el texto es más un párrafo `<p />` que un encabezado `<h2 />`

2023-03-21 08:40 UTC, Lmendev commented
Claro que si @anghelitalo :) te dejo los comentarios con más detalle más arriba

2023-03-21 08:42 UTC, Lmendev commented
además que en la descripción del PR no se encuentran las instrucciones de la actividad para dar contexto de lo que se debe revisar

2023-06-29 02:43 UTC, closed without merging