Primer pull request
undefined-academy/semana-1 pull request #476
Opened 2023-03-17 17:48 UTC by mpchaneton

#### En Github

1. En https://github.com/undefined-academy/semana-1
2. Derecha/arriba -> **Fork**
3. **Create New fork**
4. Entro a mis repositorios, busco **semana-1**
5. <Code> / Clone / copiar 

#### En la terminal
1. Abro **Ubuntu**
7. pwd para saber donde estoy
8. cd _nombre de la carpeta de Bootcamp_
9. **git clone <pego el repositorio>**
10. cd semana-1
11. cd git-profiles
12. mkdir <mi nombre Discord + # Discord>
13. cd <la carpeta creada>
14. touch <mi nombre Discord + # Discord.md>
15. Code <mi nombre Discord + # Discord.md>

#### En VSC 

1. Copiar/pegar el archivo creado en el ejercicio 1
17. **Guardar**
18. En la **Terminal de VSC:**

| Comandos |
|----------|
|1. git init |
|2. git status|
|3. git add .|
|4. git commit -m "First commit"|
|5. git log|
| 6.git push -u origin main|

#### En Github

1. Verificar que se encuentre el commit en el repositorio de nuestro perfil
2. Volver al repositorio https://github.com/undefined-academy/semana-1
3. En la isquierda/arriba **Pull Requests**/compare across forks
4. Seleccionar comparacion entre el _repositorio original_ vs _nuestro repositorio_
5. **Create pull request**/
6. Completar la descripción del trabajo realizado utilizando markdown

2023-03-20 19:29 UTC, gustavo-arana requested changes
Hola Paula, creo que todo estuvo grandioso solo son detalles. Gran trabajo.

2023-03-20 19:29 UTC, gustavo-arana commented on github-profiles/PaulaChaneton-2365/PaulaChaneton-2365
> +https://github.com/mpchaneton
Hola Paula, existe una sintaxis para hacer url en markdown

2023-03-20 19:29 UTC, gustavo-arana commented on github-profiles/PaulaChaneton-2365/PaulaChaneton-2365
> +#Prueba de cambio en Staging area con git status#
Eliminar linea de prueba

2023-03-20 19:29 UTC, gustavo-arana commented on github-profiles/PaulaChaneton-2365/PaulaChaneton-2365
> +changes no staged for commit
Eliminar linea de prueba

2023-03-20 19:29 UTC, gustavo-arana commented on github-profiles/PaulaChaneton-2365/PaulaChaneton-2365
> +*Cambio para probar en la rama main*
Eliminar linea de prueba.

2023-03-20 19:31 UTC, gustavo-arana commented
Hola Paula, no estoy seguro pero creo que tienes un carpeta de mas.

2023-03-22 19:08 UTC, mpchaneton commented
Gracias por las correcciones! =)

2023-03-22 19:15 UTC, gustavo-arana commented
Super, gracias por tomarte el tiempo de hacerlas. Y recuerda que la estructura de los link es:

My favorite search engine is [Duck Duck Go](https://duckduckgo.com)

2023-03-22 19:16 UTC, gustavo-arana approved these changes

2023-03-30 21:00 UTC, merged