Alfredo M. Vázquez-8921
undefined-academy/semana-1 pull request #479
Opened 2023-03-17 23:29 UTC by fredyMX

## _Proceso para crear mi primer Pull requests._

<li>
   Cree mi
     <a href="https://github.com/fredyMX">perfil</a>
   en Github.
</li>
<li>
   Crear el
     <a href="https://github.com/fredyMX/semana-1/blob/main/github-profiles/Alfredo%20M.%20Vázquez-8921">repositorio</a>.
</li>
<li>
Realice el Fork, y agregué un archivo con el nombre de mi usuario y id de Discord.
</li>
<li>
Realizar el Pull requests.
</li>

2023-03-19 15:52 UTC, JoseCamilo84 requested changes
Hola, que tal... veo que te falta el archivo html y css además crear la carpeta en donde iran los 2 archivos

2023-03-20 23:44 UTC, Lmendev commented
@JoseCamilo84 No, eso va en otro PR más adelante

2023-03-20 23:45 UTC, Lmendev approved these changes
En general solo un comentario., lo dejo aprobado ✅

2023-03-20 23:45 UTC, Lmendev commented on github-profiles/Alfredo M. Vázquez-8921
> +| N° | Comando | Descripción |
[SUG] Alinear los espaciados de la tabla para que se pueda leer de forma más cómoda

2023-06-29 02:43 UTC, closed without merging