Mi perfil de Github
undefined-academy/semana-1 pull request #482
Opened 2023-03-18 01:22 UTC by Hincapie-OscarH

Proceso de como hice este Pull Request:

Investigué y tuve ayuda del Discord par aesto, creé la carpeta, el archivo y usé comandos como Git add, commit -m y push origin main para esto.

2023-03-20 23:42 UTC, Lmendev requested changes
Dejé los comentarios 👋 sigamos avanzando, va tomando forma 👍

2023-03-20 23:42 UTC, Lmendev commented on github-profiles/Masaru-3255/masaru-3255.md
> +#
Este `#` está sin texto

2023-03-20 23:42 UTC, Lmendev commented on github-profiles/Masaru-3255/masaru-3255.md
> +| Comando | Descripción |
Las tablas pueden quedar mejor espaciadas

2023-03-20 23:42 UTC, Lmendev commented on github-profiles/Masaru-3255/masaru-3255.md
> +En mejora...
Espero los próximos `commits` con las modificaciones

2023-03-20 23:42 UTC, Lmendev commented on github-profiles/Masaru-3255/masaru-3255.md
> +##### Estos son los 5 comandos de la terminal que he aprendido
Los `headings` deben utilizarse para añadir jerarquía al documento

https://www.markdownguide.org/basic-syntax/#headings

2023-03-21 19:47 UTC, Hincapie-OscarH commented
Espero que las recomendaciones de mejora hayan quedado.

Usé git init, git status, git add y git pull para poder actualizar el repositorio.

2023-03-21 23:35 UTC, Lmendev approved these changes
Me parece que cumple con la actividad💎 Lo dejo aprobado ✅

2023-03-22 01:09 UTC, Hincapie-OscarH commented
Cambié el nombre del archivo md y subi el index.html.

Con ayuda de las personas de Discord pude subir los archivos ya que Git se me complica, hice tablas en los index aunque creo que puedo mejorar en ello.

2023-03-24 23:26 UTC, Hincapie-OscarH commented
Pull Request de la actividad 4 de la semana 1, agregué fondo y unos detalles a la tabla

2023-03-30 21:55 UTC, dfm555 approved these changes
Sigue así

2023-03-30 21:56 UTC, merged