Mi Perfil de GitHub
undefined-academy/semana-1 pull request #483
Opened 2023-03-18 02:08 UTC by VIKDUART

Todo el proceso de mi perfil con marksown

2023-03-20 00:59 UTC, Juanmiyo0696 requested changes

2023-03-20 00:59 UTC, Juanmiyo0696 commented on github-profiles/Victor_D-4044.md
> +| Encabezado de columna 1 | Encabezado de columna 2 |
hola, Victor en tu perfil de git Hub te falto poner los encabezados recuerda cambiarlos

2023-03-20 23:38 UTC, Lmendev requested changes
Falta añadir una descripción con más detalles al PR

2023-03-21 00:44 UTC, VIKDUART commented
Perdon ando lento las cosas x falta de tiempo que es el PR?? Y para hacer
el cambio al archivo clonado tengo que hacer un pull request no ??

El lun, 20 mar 2023, 20:38, Luis Mendoza ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> Falta añadir una descripción con más detalles al PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/undefined-academy/semana-1/pull/483#pullrequestreview-1349535976>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZDR6ZWXEOIA4DMQCVMHSKLW5DTA3ANCNFSM6AAAAAAV7FRDUE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-21 08:45 UTC, Lmendev commented
@VIKDUART PR: Pull Request

2023-03-21 08:49 UTC, Lmendev commented
No es necesario, para hacer un cambio al archivo solo debes
- Realizar los cambios que necesites
- Guardar los archivos
- Hacer `git commit` de los cambios
- Hacer `git push` para actualizar este Pull Request

Al recargar la página deberían aparecer los cambios acá

2023-03-21 08:50 UTC, Lmendev commented
Para editar la descripción lo puedes hacer en el menú de los tres `...` te debe aparecer una opción de `edit`

![image](https://user-images.githubusercontent.com/2933342/226556734-1f612ea7-f58d-427e-86c3-b4e607c59cfe.png)

2023-03-22 23:03 UTC, Lmendev approved these changes

2023-04-02 19:56 UTC, glrodasz requested changes

2023-04-02 19:56 UTC, glrodasz commented on top
Este archivo debe ser removido.

2023-06-25 02:59 UTC, closed without merging