Perfil
undefined-academy/semana-1 pull request #489
Opened 2023-03-19 00:20 UTC by OscarOLopez

1. Crear un Fork de la "semana 1"
2. Clonar la "semana 1" a mi local
3. Agregar un archivo md y editarlo con mi perfil
4. Hacer un commit al fork hecho con anterioridad.

2023-03-20 01:07 UTC, Cristhian-Medina approved these changes

2023-03-20 01:19 UTC, Juanmiyo0696 requested changes

2023-03-20 01:19 UTC, Juanmiyo0696 commented on OscarOLopez.md
> +
hola Oscar, recuerda poner los 5 comandos de la terminal y los 2 alias. Éxitos!

2023-03-29 09:07 UTC, pacorroX commented on OscarOLopez.md
> +Anterior a este trabajo estuve trabajando en el área de sistemas computacionales 🖥 para una empresa de turismo ✈️️, entre mis funciones estaba administrar y gestionar equipos, usuarios, software, har
Creo que sobra una "s" al final de la línea.

2023-03-29 09:11 UTC, pacorroX requested changes
Propongo unos cámbios:

- Cambiar el nombre del archivo a tu nombre y tag de Discord separados de un "-" en vez de un "#".
- Meter el archivo dentro del directorio `github-profiles/`.
- Añadir lo requerido en el ejercicio (una tabla con los 5 comandos más utilizados y una sección con 2 aliases), [clica aquí para verlo](https://github.com/undefined-academy/semana-1#clase-1-ejercicio).

2023-06-24 02:46 UTC, closed without merging