mi nuevo pull_request
undefined-academy/semana-1 pull request #490
Opened 2023-03-19 02:47 UTC by Matiaspercivale2001

2023-03-20 00:05 UTC, BingenWeb approved these changes

2023-03-20 00:13 UTC, BingenWeb approved these changes

2023-03-20 00:13 UTC, BingenWeb commented on github-profiles/percivv-5104/README.md
> +```bash
Bien, pero le falta la explicación de la función al alias

2023-03-21 16:55 UTC, dfm555 requested changes

2023-03-21 16:55 UTC, dfm555 commented on .gitkeep
Elimina esta archivo

2023-03-21 23:04 UTC, dfm555 approved these changes

2023-03-21 23:05 UTC, merged