Oiranca Profile and Link Github
undefined-academy/semana-1 pull request #497
Opened 2023-03-19 16:54 UTC by Oiranca

1. Realized a fork from the [repository](https://github.com/undefined-academy/semana-1.git)
2. Made Oiranca-1500 directory
3. Moved the Readme.md file
4. Made some changes in the Readme.md file
5. Wrote into the terminal the command 'git add .' and after the command' git commit -a'
6. Finally wrote the command  'git push' and created a new **pr**

2023-03-19 19:01 UTC, k4dm3l approved these changes
God job, keep it up!

2023-03-19 23:42 UTC, julietalazzaro requested changes
Hola Samuel, te comente algunas cuestiones a mejorar del sitio pero vas muy bien! Tambien faltaria agregar los estilos para finalizar con el ejercicio de la semana 1. Cualquier duda escribime

2023-03-19 23:42 UTC, julietalazzaro commented on github-profiles/Oiranca-1500/index.html
> +<h2>Sobre mi ..</h2>
Falta la estructura del HTML, te dejo un recurso si ayuda (https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics#anatomy_of_an_html_document)

2023-03-19 23:42 UTC, julietalazzaro commented on github-profiles/Oiranca-1500/index.html
Deberias indentar el codigo para una mayor legibilidad y entendimiento del codigo. Si usas Visual Studio Code hay extenisones que lo hacen por vos, como Prettier.

2023-03-19 23:42 UTC, julietalazzaro commented on github-profiles/Oiranca-1500/index.html
> +<p>1- <strong>cat</strong>: Imprime el contenido de un archivo dada su ruta.</br>
Creo que una mejor práctica es usar dos etiquetas de parrafo para separar el contenido (ya que tienen display block y se separan solo) y no usar un salto de linea forzado

2023-03-20 18:25 UTC, Oiranca commented on github-profiles/Oiranca-1500/index.html
> +<h2>Sobre mi ..</h2>
Tienes razón, no me había fijado que 11ty no me lo había puesto.Lo corrijo en el siguiente commit. Gracias!! :smile:

2023-03-20 18:26 UTC, Oiranca commented on github-profiles/Oiranca-1500/index.html
Cierto, lo tenía hecho, pero no había guardado y no me cuenta :weary: . Lo subo en el siguiente commit. Gracias!!!

2023-03-20 18:27 UTC, Oiranca commented on github-profiles/Oiranca-1500/index.html
> +<p>1- <strong>cat</strong>: Imprime el contenido de un archivo dada su ruta.</br>
Gracias, tienes toda la razón. :smile:

2023-03-21 00:35 UTC, Yanina-Unrein reviewed
me pareció bastante bien, esta el readme con los 5 comandos y los alias además del enlace a github, el index se ve bastante bien también y la carpeta parce bien nombrada. Faltaría el archivo css con los estilos

2023-03-21 02:38 UTC, julietalazzaro commented on github-profiles/Oiranca-1500/index.html
> +<html lang="en">
El lenguaje deberia coincidir con el idioma usado para elaborar el sitio, es por temas de accesibilidad

2023-03-21 11:46 UTC, Oiranca commented on github-profiles/Oiranca-1500/index.html
> +<html lang="en">
Corregido, gracias!! :smile:

2023-03-22 02:19 UTC, julietalazzaro approved these changes

2023-06-22 02:31 UTC, closed without merging