github profile added
undefined-academy/semana-1 pull request #5
Opened 2023-03-03 05:18 UTC by brianbrallard

# Descripción del proceso.
### Fue un poco difícil pero muy llevadero gracias a la información de la clase.

-----------------------------
# Pasos del proceso

- [x] Hacer un fork del repositorio.
- [x] Clonar el repositorio "forked" en carpeta HOME.
- [x] Agregar archivo markdown con el perfil de mi GitHub en la carpeta github-profiles.
- [x] Incluir dentro del archivo mi link de GitHub.
- [x] Hacer el commit.
- [x] Ir al repositorio del paso 1 y hacer Pull Request.
- [x] No dejar el PR vacío y usar markdown.

2023-03-09 03:04 UTC, Cristianp9927 approved these changes
esta todo perfecto

2023-03-09 20:50 UTC, r4vc31 requested changes

2023-03-09 20:50 UTC, r4vc31 commented on github-profiles/brianbr-3719/index.js
> +  }
1. Debe plantear la ecuación para la resolución con la información brindada en el ejercicio.
2.  Recuerde que debe considerarse el caso de que la variable tenga un valor de null.

2023-03-09 21:24 UTC, brianbrallard commented on github-profiles/brianbr-3719/index.js
> +  }
muchas gracias por la revisión, ahora lo corrijo

2023-03-10 04:29 UTC, brianbrallard commented
ya lo correji, espero tu approve, gracias

2023-03-10 04:30 UTC, brianbrallard commented on github-profiles/brianbr-3719/index.js
> +  }
ya lo correji, espero tu approve, gracias

2023-03-10 05:08 UTC, nobody-redhawk approved these changes
# Sugerencia
1. Describe paso a paso todo el proceso de cada uno de los ejercicios de las clases de la semana 1.

2023-03-10 07:32 UTC, r4vc31 approved these changes
Good Job! ✌️

2023-03-14 20:59 UTC, ManuCastrillonM requested changes
Hola Brian!
Creo que accidentalmente modificaste el archivo README.md. Podrías por favor deshacer los cambios en ese archivo? Si tienes alguna duda de como hacerlo, con mucho gusto te puedo ayudar.

2023-03-14 21:43 UTC, brianbrallard commented
> Hola Brian! Creo que accidentalmente modificaste el archivo README.md. Podrías por favor deshacer los cambios en ese archivo? Si tienes alguna duda de como hacerlo, con mucho gusto te puedo ayudar.

Hola, si, me pasó que no entendí muy bien una consigna de un ejercicio y me quedó mal el README.md, despues lo solucioné pero me quedó el commit de que lo borré, y no se como deshacer eso, muchas gracias por la revisión

2023-03-16 16:37 UTC, DevOld112 approved these changes
Excelente, tienes mi aprobacion has cumplido con todo lo solicitado en los ejercicios de semana 01

2023-03-17 12:33 UTC, merged