ejercicio 1
undefined-academy/semana-1 pull request #50
Opened 2023-03-04 04:07 UTC by Jorem999

Un montón de esfuerzo hasta encontrar la forma de hacer un git push,  por el manejo de las llaves de seguridad ssh

2023-03-12 19:19 UTC, LichtEwig approved these changes

2023-03-14 16:12 UTC, joaquinesteban commented
Todo Perfecto!

2023-03-14 16:14 UTC, joaquinesteban approved these changes
Todo Perfecto!!

2023-03-14 16:20 UTC, dfm555 requested changes
Debes resolver los conflictos generados el archivo .gitignore

Debes eliminar el archivo Jorem999-5406.md

2023-03-14 16:20 UTC, dfm555 commented on github-profiles/Jorem999-5406/main.css
> +header {
@Jorem999 agrupa las propiedades header en una sola, revisa que tienes dos.

2023-03-14 19:41 UTC, Jorem999 commented
>

2023-03-14 19:49 UTC, Jorem999 commented on github-profiles/Jorem999-5406/main.css
> +header {
@dfm555, listos los cambios que has sugerido!
¡Gracias por tu revisión!
Cualquier otra sugerencia bienvenido! :-)

2023-03-14 19:50 UTC, Jorem999 commented on github-profiles/Jorem999-5406/main.css
> +header {
... eliminé el mi archivo .gitignore
agrupé los header

2023-03-14 20:01 UTC, merged