Agregado mi perfil de git y el link
undefined-academy/semana-1 pull request #501
Opened 2023-03-20 04:54 UTC by restre17

# Pasos que seguir para desarrollar el ejercicio 

- Ingrese al link del repositorio semana 1
- alli busque la opcion de hacer el fork y lo cree
- Ingrese a mi perfil busque el repositorio Forked y copie el link para clonarlo
- En mi Terminal fui a la carpeta Code y alli use `git clone` + el link 
- Una vez creado el repositorio, copie el contenido del  archivo creado en el ejercicio anterior y lo copie en un archivo nuevo con el usuario del discord 
- ahora solo fue hacer `commit` + `push` 
- y por ultimo ingre al repositorio forked en github y solicite el pull request que estoy haciendo ahora mismo.

2023-03-20 15:56 UTC, bEERRE96 commented on github-profiles/Diego-3282.md
> +| COMANDO | DESCRIPCIÓN |
Quizas estaria bueno que las tablas esten ordenadas a la misma altura, para una visualizacion mas prolija.

2023-03-20 23:29 UTC, Lmendev requested changes

2023-03-20 23:29 UTC, Lmendev commented on github-profiles/Diego-3282.md
> +| COMANDO | DESCRIPCIÓN |
creo que solo para esta tabla, la segunda se no se vería tan bien por la cantidad de texto

2023-03-22 22:58 UTC, Lmendev approved these changes
💎

2023-03-24 04:59 UTC, andresarioro approved these changes
Saludos @restre17 
He revisado tu trabajo y siento que cumple bastante bien con lo aplicado en las clases, están muy geniales las tablas en el html. Supongo que aplicaste algunos de los detalles sugeridos de **Diseño Web en 4 minutos de Jeremy Thomas**, de acuerdo a tu necesidad y gusto.

2023-06-25 21:07 UTC, merged