Add file with my profile in github using Markdown
undefined-academy/semana-1 pull request #503
Opened 2023-03-20 17:08 UTC by davidherrera0921

👍

2023-03-20 19:58 UTC, MauBedoya requested changes
El README.md parece correcto, pero recuerda que la última practica de semana 1 es agregar estilos según el link que dejan en las Slides.
Ahh y también sería bueno que dejes una pequeña descripción de tu proceso en el comentario del pull request!

2023-03-20 20:00 UTC, PiCureDev reviewed
hola, te he hecho dos comentarios en la linea dos y en la linea 7. si puedes tambien me das feedback

2023-03-20 20:00 UTC, PiCureDev commented on github-profiles/DevidH092101-6070/index.html
> +    <title>This is a web page</title>
tambien podrias cambiar a español ya que toda tu pagina esta en español

2023-03-21 14:02 UTC, davidherrera0921 commented on github-profiles/DevidH092101-6070/README.md
> +### [_Link perfil de github_] (https://github.com/davidherrera0921)
Tenias razón con el espacio entre los paréntesis y los corchetes, Muchas gracias <3

2023-03-24 01:02 UTC, davidherrera0921 commented
Realizado el ejercicio de la clase 4 semana 1

2023-03-24 17:55 UTC, JoeOsG approved these changes
### Bien.
**Buen trabajo.**

2023-03-24 23:44 UTC, dlozanoc82 approved these changes
Good Job. David 🎉👏

2023-03-25 00:09 UTC, davidherrera0921 commented on github-profiles/DevidH092101-6070/index.html
> +    <title>This is a web page</title>
Gracias por tu revisión, ya realice el cambio en mi ultimo commit

2023-03-25 00:15 UTC, MauBedoya approved these changes
Solo queda que pidas que aprueben tu merge en discord, creo 👀

2023-03-28 13:46 UTC, merged