Semana 1
undefined-academy/semana-1 pull request #504
Opened 2023-03-20 17:51 UTC by giovanyosorio

Ejercicio semana 1

- Actualice mi perfil ya que lo tenia pero estaba desactualizado.
- Realice un Fork y agregué un archivo con el nombre de Discord.
- Realice el Pull Request.

2023-03-20 18:11 UTC, joaquinesteban approved these changes
Cumple con lo pedido en la semana-1, lo unico los estilos de css en otra plantilla con la extencion.css Saludos!

2023-03-20 18:19 UTC, giovanyosorio commented
# Hola

Tienes razon una mejor practica es dejar los estilos de css en otro archivo
Cambio ajustado

2023-03-20 19:06 UTC, julietalazzaro requested changes

2023-03-20 19:06 UTC, julietalazzaro commented on github-profiles/gio799-7609/README.md
> +| comandos | Descripcion |
Puedes alinear los bordes de la tabla para que sean mas legibles en texto puro

2023-03-20 19:06 UTC, julietalazzaro commented on github-profiles/gio799-7609/gio799.html
Este archivo deberia llamarse index.html
este es archivo que muestra un navegador por defecto

2023-03-20 19:06 UTC, julietalazzaro commented on github-profiles/gio799-7609/styles.css
podrias agregar algunos estilos como recomienda el sitio "diseñador grafico en 4 minutos" que recomendo Guillermo. Son pocas lineas de codigo pero ayudan mucho a la estetica de la pagina

2023-03-20 19:43 UTC, giovanyosorio commented on github-profiles/gio799-7609/README.md
> +| comandos | Descripcion |
Listos , es verdad visualmente no esta muy bien, corregido con otros comandos

2023-03-20 19:43 UTC, giovanyosorio commented on github-profiles/gio799-7609/styles.css
Le agregue otro diseño que tengo igualmente en la semana dos mejorando el css, usando flexbox y pseudoelementos

2023-03-21 02:32 UTC, julietalazzaro approved these changes

2023-03-21 15:26 UTC, closed without merging