Mi perfil de GitHub
undefined-academy/semana-1 pull request #529
Opened 2023-03-22 21:15 UTC by adriancarrion05

## Ejercicio 1

1. Realicé una fork del repositorio de undefined-academy.
2. Copié el repositorio de la 'semana-1' mediante mi consola de ubuntu.
3. Dentro de la carpeta github-profiles incluí un archivo nuevo en formato markdown con mi perfil de GitHub.
4. Confirmé el archivo nuevo con un commit.
5. Accedí al repositorio de undefined-academy y presenté una solicitud de pull request.

### Comandos:
1. cd Code
2. cd semana-1
3. github-profiles
4. git status
5. git add .
6. git commit -m "Mi perfil de GitHub"
7. git push origin main

2023-04-02 21:05 UTC, ivanpachecos commented on github-profiles/aacarrion4-4565/README.md
> +https://github.com/adriancarrion05
Una surgerencia, te recomiendo que hagas un hiperenlace o una imagen-enlace de tu perfil de github.

2023-04-03 07:31 UTC, ivanpachecos requested changes
Nice, te recomendaria que los link puedas ubicarlo en una imagen o hipervinculo para que tenga una mejor visualización. El resto OK.

2023-04-03 17:30 UTC, JoeOsG approved these changes
### bien
Quedo muy bien.

2023-04-03 17:33 UTC, overcome18 requested changes

2023-04-03 17:33 UTC, overcome18 commented on github-profiles/aacarrion4-4565/README.md
> +| Comandos | Descripcion |
Seria importante alinear las columnas, el aspecto visual es importante.

2023-04-05 04:47 UTC, zucerkia approved these changes

2023-06-06 02:45 UTC, closed without merging