My first pull request - Alejandro Rivas
undefined-academy/semana-1 pull request #530
Opened 2023-03-22 21:35 UTC by aerr96

## Class 2 Week 1 exercise:

1.  I made the fork directly from the GitHub page of the undefined-academy repository to my user repositories.
2.  Then, I cloned the repository to a folder called "semana1" in my root path. Just using the command  `` git clone <my_forked_repo_url> ``
3.  I moved to the directory `` github-profiles `` using the command `` cd ``, I created the README file with the command `` touch `` with the name of my discord username.
4.  Using the command `` code `` I edited the README file with my previously made Markdown code in VisualStudio Code.
5. With the command, `` git add `` I added the file to the repository, and then with the command `` git commit `` I committed.
6. Finally, I'm requesting a pull request to finish and review this first exercise, thanks so much.

📝**Note**: Indiferentemente de que el curso es dictado en Español, prefiero redactar mis informes y ejercios en ingles, ya que, busco entrar directamente a un mercado laboral en ingles. Gracias.

2023-03-22 23:41 UTC, aerr96 commented
### Class 3 Week 1 exercise: 

1. Highlight last class missing step: after commit requires a push with `` git push `` 
2. Folder created with `` mkdir `` command.
3. Previous `` .md `` file copied to a new folder as a new file and named README.
4. Index HTML file created according to the class 3 and committed all the changes.

2023-03-23 04:23 UTC, aerr96 commented
### Class 4 Week 1 final commit:

1. Following Jeremy Thomas tutorial, a ccs style file was implemented, adding formats, color, and an image to reach a better-looking presentation.

2023-03-29 21:18 UTC, dfm555 requested changes

2023-03-29 21:18 UTC, dfm555 commented on github-profiles/aerr96-4844.md
Mueve este archivo dentro de carpeta aerr96-4844/ o elimínalo pues no deben ir archivos dentro de github-profiles/

2023-03-29 21:18 UTC, dfm555 commented on github-profiles/aerr96-4844/README.md
Agrega los alias

2023-03-29 21:18 UTC, dfm555 commented on github-profiles/aerr96-4844/style.css
> +/*code,
Elimina el código comentado

2023-03-29 21:33 UTC, aerr96 commented on github-profiles/aerr96-4844/style.css
> +/*code,
Listo acabo de limpiar y ajustar mi PR con los cambios sugeridos, gracias. Espero la re-revision.

2023-06-04 02:56 UTC, closed without merging