My profile on Github
undefined-academy/semana-1 pull request #538
Opened 2023-03-23 15:07 UTC by BlueDiamond2022

He intentado hacer mi primer Pull Request, me ha costado mucho. Hay que mejorar cada dia , por eso voy a ir intentando repasar las clases. Gracias a todos.

2023-03-23 15:31 UTC, BlueDiamond2022 commented
Al segundo pull me salio :)

2023-03-25 00:02 UTC, davidherrera0921 reviewed
Hay algunos errores de sintaxis pero nada grave, corrígelos y quedara genial el Markdown

2023-03-25 00:02 UTC, davidherrera0921 commented on github-profiles/ianApt-1386.md
> +| ls | Lista el contenido de un  directorio
Hay algunos problemas cerrando las columnas en las tablas de MarkDown, recuerda que para hacer una Columna debes colocarlas de este forma | Columna | Descripción | de esta manera se visualizaran bien las columnas.

2023-03-25 00:02 UTC, davidherrera0921 commented on github-profiles/ianApt-1386.md
> +| Alias Clear = cl                                           |
Lo mismo aquí, estaría cool si agregas otra columna en lugar de usar el "="

2023-03-25 02:22 UTC, restre17 requested changes
Primero felicitarte por empezar el bootcamp y animarte a que lo continues y aprende cada dia.

aca la tabla esta mal creada, puedes volver a revisar la grabacion o los slices para que  veas bien como se hacen, basicamente no cerraste la segunda columna con |  en donde va la sescripcion por eso al poner la vista previa no sale el texto de la descipcion, y seria bueno tambien que le colocaras el encabezado correspondiente  algo asi como 
| Comandos    | Descripcion |
| -------------- | -------------|
y aca el contendio cerrando al final siempre con |

2023-04-14 09:34 UTC, BlueDiamond2022 reviewed
Diganme si no me he liado mucho.

2023-06-03 02:35 UTC, closed without merging