Archivos semana 1
undefined-academy/semana-1 pull request #539
Opened 2023-03-23 15:24 UTC by angelormz

Integración de mis archivos README.md e index.html

2023-03-23 15:50 UTC, darioernesto-roca requested changes
Hola Angelo, me gusta como quedó el markdown e hiciste una buena adaptación al HTML. Solo falta agregarle estilos CSS y te recomiendo mirar la indentación del h1 de tu archivo index.html. Saludos

2023-03-23 16:02 UTC, angelormz commented
> Hola Angelo, me gusta como quedó el markdown e hiciste una buena adaptación al HTML. Solo falta agregarle estilos CSS y te recomiendo mirar la indentación del h1 de tu archivo index.html. Saludos

Muchas gracias Dario por tus comentarios, si comienzo con la clase de CSS para hacer los cambios a mi archivo HTML y realizo la corrección comentada, muchas gracias por la observación, saludos!

2023-03-23 16:57 UTC, Lunisa202 commented on github-profiles/angeloramirez-5010/README.md
> +[Twittter] (https://twitter.com/AngeloRmz)
Hola, en el archivo markdown para tener enlaces guardados en un texto, deberías no dejar ningún espacio entre los corchetes y los paréntesis del enlace, así se verá en la presentación solo el texto. y se esconderá el enlace.

2023-03-23 16:59 UTC, Lunisa202 commented on github-profiles/angeloramirez-5010/index.html
> +    <h1>Hi there ✌️ I´m Angelo Ramírez</h1>
Me gustó mucho tu trabajo, sigue avanzando el ultimo ejercicio en css y se verá todo mejor.

2023-03-23 17:00 UTC, Lunisa202 commented on github-profiles/angeloramirez-5010/index.html
> +<ul>
Creo que podría usar tablas con el elemento 'table', así se vería más parecido al archivo markdown original, en el cual habían tablas.

2023-03-23 17:13 UTC, angelormz commented on github-profiles/angeloramirez-5010/README.md
> +[Twittter] (https://twitter.com/AngeloRmz)
Hola cierto no lo había descubierto ya hice el cambio en mi VSC y efectivamente quedan como enlaces muchas gracias por el comentario!. En un momento hago los commits para la actualización de mis archivos 👍🏻

2023-03-23 17:14 UTC, angelormz commented on github-profiles/angeloramirez-5010/index.html
> +    <h1>Hi there ✌️ I´m Angelo Ramírez</h1>
Súper muchas gracias por tu retroalimentación y los puntos de mejora agradezco tu tiempo, saludos!

2023-03-23 17:16 UTC, angelormz commented on github-profiles/angeloramirez-5010/index.html
> +<ul>
Perfecto quería ver si eso lo usaba en el HTML semántico pero buena idea usar el tag de <table> para que se vea parecido a mi archivo de markdown, gracias por la recomendación!

2023-03-23 17:16 UTC, angelormz commented
> Hola, te dejé comentarios para que puedas mejorar tu archivo HTML y markdown. Espero puedas revisarlos. Estuvo bastante bueno tu trabajo hasta el momento.

Si ya los vi muchísimas gracias por la retro y tu tiempo, en un momento realizo los cambios comentarios. Saludos!

2023-03-29 23:04 UTC, 4ngelo12 approved these changes

2023-03-31 02:42 UTC, Lunisa202 approved these changes
Aun creo que debes agregarle las tablas, pero lo veo todo bien por otro lado.

2023-05-31 02:43 UTC, closed without merging