ejercicio semana 1 clase 2
undefined-academy/semana-1 pull request #545
Opened 2023-03-24 04:41 UTC by SantiSua18

Me toco investigar un poco pero poco a poco voy aprendiendo algunas cosas no las entendía pero gracias a un compañero y a que investigue pude lograr los ejercicios

2023-03-24 18:47 UTC, augaldecr requested changes

2023-03-24 18:47 UTC, augaldecr commented on github-profiles/santsuaza-9920/MARKDOWN.md
> +|Commands| Desccription|
Lo ideal es que el markdown se pueda leer ("entender") tanto en el editor de código, como en el navegador.

| encabezado1                    | encabezado 2                  |
|-----------------------------|----------------------------|
| Contenido de columna 1 | Contenido de columna 2 |

2023-03-24 18:47 UTC, augaldecr commented on github-profiles/santsuaza-9920/MARKDOWN.md
> +##who am i?
Para que funcionen los Encabezados, el título debe ir separado de los "#". Ejemplo: 
## Who am I?

2023-03-25 03:02 UTC, augaldecr approved these changes
Listo

2023-03-25 18:25 UTC, Ender96 approved these changes

2023-03-29 01:07 UTC, snayder1900 approved these changes
Buen trabajo master, falta  agregar  los estilos css  de  la ultima  clase de la semana  y listo

2023-04-01 03:28 UTC, snayder1900 approved these changes

2023-05-28 02:31 UTC, closed without merging