Mi perfil de GitHub
undefined-academy/semana-1 pull request #552
Opened 2023-03-25 23:24 UTC by HeynerSalvador

TODO: El proceso de como hice este PR

2023-03-27 01:14 UTC, Sorx4s commented
> TODO: El proceso de como hice este PR

Te falto agregar el proceso para resolver el ejercicio.

2023-03-27 01:48 UTC, Sorx4s commented on github-profiles/HeynerSalvador-6132.md
> +https://github.com/HeynerSalvador
Podrías cambiarlo de esta otra manera: `[Mi perfil de Github](https://github.com/HeynerSalvador)` para que se vea de esta forma: [Mi perfil de Github](https://github.com/HeynerSalvador)

2023-03-27 18:19 UTC, Sorx4s requested changes

2023-03-27 18:19 UTC, Sorx4s commented on github-profiles/HeynerSalvador-6132.md
> +
> TODO: El proceso de como hice este PR

Te falto agregar el proceso para resolver el ejercicio.

2023-03-27 18:20 UTC, Sorx4s commented on github-profiles/HeynerSalvador-6132.md
> +https://github.com/HeynerSalvador
Podrías cambiarlo de esta otra manera: `[Mi perfil de Github](https://github.com/HeynerSalvador)` para que se vea de esta forma: [Mi perfil de Github](https://github.com/HeynerSalvador)
```suggestion
[Mi perfil de Github](https://github.com/HeynerSalvador)
```

2023-03-29 21:35 UTC, HeynerSalvador commented on github-profiles/HeynerSalvador-6132.md
> +https://github.com/HeynerSalvador
Gracias por la sugerencia, no me había percatado de ello.

2023-03-29 21:39 UTC, HeynerSalvador commented on github-profiles/HeynerSalvador-6132.md
> +
Bueno no sabia que había que añadir eso, gracias por el dato.

2023-03-29 22:44 UTC, HeynerSalvador commented
Actualizando cambios

2023-03-30 15:44 UTC, closed without merging

2023-03-31 20:48 UTC, Diegu32 commented
Me gustó la explicación de los pasos, bastante claro