Mi Perfil de GitHub areynel
undefined-academy/semana-1 pull request #555
Opened 2023-03-27 18:01 UTC by areynel

Finalmente pude hacer el ejercicio, muy chevere Guillermo.

2023-03-28 01:44 UTC, snayder1900 requested changes
Cordial saludo,  faltaria agregar el comando  del alias faltante

2023-03-28 01:44 UTC, snayder1900 commented on github-profiles/areynel-9123/areynel-9123.md
> +| 1.  | alias cl='clear' |
Cordial saludo, faltaría agregar otro alias y quedaría listo

2023-03-28 15:02 UTC, areynel commented on github-profiles/areynel-9123/areynel-9123.md
> +| 1.  | alias cl='clear' |
Arreglado.

2023-03-28 15:10 UTC, areynel commented
Actualizado.

2023-03-28 15:10 UTC, closed without merging

2023-03-29 00:51 UTC, snayder1900 commented
Listo Areynel, ya quedo correcto

2023-03-29 00:52 UTC, snayder1900 reviewed
listo Areynel ya quedo el alias faltante  bien