Primer commit de mi perfil
undefined-academy/semana-1 pull request #558
Opened 2023-03-28 00:29 UTC by 4ngelo12

Para realizar este ejercicio realicé los siguientes pasos:
1.  Realizar un **fork** al repositorio.
2.  Clonar el repositorio hacia mi dispositivo
3.  Crear una carpeta con mi nombre de usuario en **discord** y agregar un archivo **Markdown** sobre mi perfil.
4.  Luego realicé un **commit** del archivo para posteriormente realizar un **merge**.
5.  Finalmente cree un **pull request** para agregar completar el ejercicio propuesto.

2023-03-28 01:43 UTC, kiltro-dev requested changes
Bien, falta el html. Saludos

2023-03-29 09:05 UTC, pacorroX requested changes
En este primer commit, se pide que hagas solamente un archivo Markdown con tu nombre y tag de Discord en la ruta `github-profiles/`, en los siguientes ya se crea la carpeta con todo lo demás y se mueve el archivo a dentro.

Por lo demás, lo veo todo correcto.

2023-03-29 18:48 UTC, 4ngelo12 commented
Agregando index.html y style.css

2023-04-14 21:00 UTC, JoeOsG approved these changes
### Bien

2023-06-07 02:43 UTC, closed without merging