Adding WaSeidel-9727 readme
undefined-academy/semana-1 pull request #579
Opened 2023-03-31 01:48 UTC by waseidel

# Just added the readme with my contact info

2023-03-31 02:57 UTC, waseidel commented
Este pull Request Si agregarlo, voy a ver como elimino el otro que cree para que solo quede este

2023-03-31 15:43 UTC, 4ngelo12 commented on github-profiles/waseidel-9727/index.html
> +                code: {"Javascript": "", "Python": "", "php": ""},
Tu trabajo se ve bien, sin embargo, hay parte donde se ve esto "" en caso de ser un error deberías corregirlo sino simplemente ignora esto

2023-03-31 15:46 UTC, waseidel commented on github-profiles/waseidel-9727/index.html
> +                code: {"Javascript": "", "Python": "", "php": ""},
Ahhh esos son iconos que se verían con nerdfonts, esta noche reviso si puedo cambiarlos por emojis, o si definitivamente los elimino

2023-03-31 17:03 UTC, Gaston095 requested changes

2023-03-31 17:03 UTC, Gaston095 commented on github-profiles/waseidel-9727/index.html
> +<html lang="es">
Hola! Si el contenido de la pagina esta en ingles deberias el lang por "en" ..

2023-04-01 13:18 UTC, waseidel commented on github-profiles/waseidel-9727/index.html
> +<html lang="es">
Sí, tienes razón, ya lo acabo de corregir, tanto los iconos cómo el idioma, muchas gracias por las observaciones

2023-05-18 02:19 UTC, closed without merging