Proceso de mi primer Pull Request
undefined-academy/semana-1 pull request #587
Opened 2023-04-02 18:26 UTC by mariagzq

1.- Hice un fork del repositorio de la semana-1 de Undefined Academy. 2.- Cloné en mi repositorio local.
3.- Agregué mi archivo readme.md + link a mi perfil de GitHub bajo mi nombre de usuario de Discord. 4.- Hice el Pull Request en el repositorio.

2023-04-02 18:50 UTC, yulsdev requested changes
Todo Ok, solo el detalle de las tablas.

2023-04-02 18:50 UTC, yulsdev commented on github-profiles/mariagzq-6165
> +| Comando | Función |
Hola, esta bien, pero te recomiendo alinear las tablas (columnas). Aunque esto no se note (en el visualizador), es preferible que el documento fuente tambien se encuentre bien formateado y ordenado.

2023-04-03 06:24 UTC, zucerkia approved these changes

2023-04-03 06:24 UTC, zucerkia commented on github-profiles/mariagzq-6165
> +
Hola 👋. todo muy bien. Para la próxima te recomiendo no usar tantos saltos de línea (Enters) para que el archivo no se llene de líneas vacías y se mas corto y manejable

2023-04-03 17:28 UTC, JoeOsG requested changes
Continua con las clases, para que tengas el html tambien.

2023-05-16 02:21 UTC, closed without merging