Mi perfil de github
undefined-academy/semana-1 pull request #602
Opened 2023-04-04 18:25 UTC by CamachoDaniela

-fork es llevarse un repositorio remoto a nuestro github, eso se clona en la carpeta Code

si enlisto ya tengo en Code la carpeta semana-1, ingresa a la carpeta github-profiles

crea un archivo  markdown nuevo con el nombre de su usuario de discord 

Ingreso a la carpeta de Code “el mundo del markdown” y veo su contenido

copio y pego eso en el md de semana-1 y guardo.

añado mi cambio a la carpeta git profiles

hago un commit

hago push en mi repositorio

me voy al fork de mi repositorio

[https://github.com/CamachoDaniela/semana-1](https://github.com/CamachoDaniela/semana-1)

aparece 

This branch is [[1 commit ahead](https://github.com/CamachoDaniela/semana-1/compare/undefined-academy:semana-1:main...main)](https://github.com/CamachoDaniela/semana-1/compare/undefined-academy:semana-1:main...main)
 of undefined-academy:main.

entro y añado este pull request

2023-04-04 19:40 UTC, fredyMX requested changes
En general un comentario solo faltaría cambiar el nombre del archivo de Markdown, por lo demás lo veo bien.

2023-04-04 19:40 UTC, fredyMX commented on github-profiles/denisse-9285/denisse-9285.md
> +# Denisse Antonella Safi
hola, el archivo debería tener el nombre de `README.md`, en lugar de tu nombre de usuario de discord.
Saludos.

2023-04-05 02:26 UTC, CamachoDaniela commented on github-profiles/denisse-9285/denisse-9285.md
> +# Denisse Antonella Safi
Ya realice el cambio. Muchas gracias

2023-04-18 20:24 UTC, CamachoDaniela commented
Me falta un aprove

2023-05-20 02:13 UTC, closed without merging