First Pull Request
undefined-academy/semana-1 pull request #605
Opened 2023-04-05 00:49 UTC by Snahoj

Hacemos fork del repositorio semana-1 
Clonamos el repositorio forked en la carpeta Home o el nombre que le tengas puesto 
Navegamos hasta ~/BootCamp/semana-1/github-profiles$  entramos <
git init 
Mkdir  nueva carpeta
Touch archivo.md
git add 
Hacemos Comit 
Push desde la consola al main origin 
Y creamos el primer pull request

2023-04-10 23:42 UTC, alesalazard requested changes
Hola @Snahoj El código de tu perfil se ve muy acorde al ejercicio propuesto, aunque te falta practicar las tablas en Markdown. También te recomiendo es que cambies el nombre del archivo css, por convención usualmente se le llama: styles.css o style.css a secas, no es usual utilizar camelCase en css. Píllate el contenido del enlace recomendado para la clase, que te va a ayudar montones para "enchular" tu html. Me encantó que lo hicieras en inglés!

2023-04-11 23:06 UTC, Snahoj commented
> Hola @Snahoj El código de tu perfil se ve muy acorde al ejercicio propuesto, aunque te falta practicar las tablas en Markdown. También te recomiendo es que cambies el nombre del archivo css, por convención usualmente se le llama: styles.css o style.css a secas, no es usual utilizar camelCase en css. Píllate el contenido del enlace recomendado para la clase, que te va a ayudar montones para "enchular" tu html. Me encantó que lo hicieras en inglés!

Hola muchisimas gracias por la review , hare caso de lo que me dices y tengo que practicar bastante css y markdown jeje

2023-04-25 07:14 UTC, delospp requested changes
Vi que tienes dos archivos README y dos CSS, alguna razon? Se supone que solo debe ir uno de cada uno

Quedó  pendiente a tus comentarios 


Te agradezco si puedes ir a mis PRs 
Semana 1
https://github.com/undefined-academy/semana-1/pull/632

Semana 2
https://github.com/undefined-academy/semana-2/pull/185

2023-04-25 07:14 UTC, delospp commented on github-profiles/Johans-2787/.README.md
Se supone que solo debes tener un archivo README.md, alguna razon para tener un .README.md?

2023-04-25 07:14 UTC, delospp commented on github-profiles/Johans-2787/README.md
Tengo entendido que los alias deben ir en una sección así:
```bash
Comandos alias que me parezcan utiles
1. Alias1
2. Alias2
```

2023-04-25 14:16 UTC, Snahoj commented
> Hola @Snahoj El código de tu perfil se ve muy acorde al ejercicio propuesto, aunque te falta practicar las tablas en Markdown. También te recomiendo es que cambies el nombre del archivo css, por convención usualmente se le llama: styles.css o style.css a secas, no es usual utilizar camelCase en css. Píllate el contenido del enlace recomendado para la clase, que te va a ayudar montones para "enchular" tu html. Me encantó que lo hicieras en inglés!

nombre de los estilos cambiado a styles.css o style.css para no generar confusiones echale un ojo a todo he mejorado un poco todo espero que ahora este mejor

2023-04-25 14:21 UTC, alesalazard approved these changes
El Markdown te quedó súper. Para este ejercicio creo que sólo se revisaba ese, pero con los avances que has tenido en html y css, los de la próxima semana te van a quedar chulis :)

2023-04-25 14:28 UTC, Snahoj commented
> El Markdown te quedó súper. Para este ejercicio creo que sólo se revisaba ese, pero con los avances que has tenido en html y css, los de la próxima semana te van a quedar chulis :)

Podrias echarme una mano para quitar la etiqueta stale?

2023-04-26 05:42 UTC, delospp approved these changes
Ya puedes pasar el PR a merge en discord, no hay una forma de quitar la etiqueta stale, quizá con el merge

2023-04-26 13:12 UTC, merged