Incluir mi carpeta a los ejercicios de la semana 1
undefined-academy/semana-1 pull request #611
Opened 2023-04-06 17:22 UTC by MrRedu

# ¿Cómo me fue haciendo este ejercicio?
**TOTALMENTE** ~**TORTUOSO**~ *disfrutable*, ni siquiera estoy seguro de haberlo hecho correctamente.
Espero Git no sea tan complicado para siempre.
> La terminal se hace la difícil 😥

2023-04-06 17:50 UTC, MrRedu commented
¡Buenas!

He hecho 4 commits, básicamente por pura "prueba y error" inconscientemente, espero que esto no afecte de manera perjudicial al reposotorio.

El primero, es porque agregué mi archivo .md, sin carpeta alguna.
El segundo, agregué la carpeta con mi @DiscordUsername y creo haber duplicado el archivo .md, entonces estaba el de la carpeta, y el anterior que estaba fuera de la carpeta.
El tercero, edité el archivo para des-comentar el URL de mi perfil de GitHub
El cuarto, no estoy seguro de lo que he hecho, pero según entiendo; eliminé mi archivo, por ende, la carpeta desapareció. Luego restauré el archivo, y quedó sin carpeta, por ende, agregué una carpeta y moví el archivo hacia ella.
De este último cuarto paso, hice commit y push, pero no estoy seguro si sale reflejado en el pull-request.

Sinceramente, muchas disculpas si volví todo un desastre. Me costó un montón llegar hasta este punto.

2023-04-12 16:05 UTC, Pancratzia requested changes
Hola! Me ha gustado mucho los efectos que has colocado al proyecto en la parte del titulo y los textos al hacer hover. También me ha gustado el formato en que muestras tus datos personales. Sin embargo, creo que para cumplir con la asignación debes agregar la tabla de comandos y alias de linux, ya que veo que los tienes en el archivo .md pero no los incluyes en tu html.

![image](https://user-images.githubusercontent.com/54899954/231516582-f6f746a1-366c-4fdb-9825-49c5873186b9.png)

Como otra sugerencia, pero sin necesidad de que la realices, podrías colocarle a tu link de github una imagen en lugar de una gran cantidad de texto. Así podría verse mejor en contraste con la estética de tu sitio web.

![image](https://user-images.githubusercontent.com/54899954/231515833-e62bc3d6-f6fb-4ab1-a337-99fe0ce8c6e8.png)

2023-04-13 01:48 UTC, MrRedu commented
### ¡Saludos! 🤗 
*Hola @Pancratzia,* creo que pude aplicar las observaciones que me has hecho, cuéntame ¿qué tal lo ves ahora?

Pienso que el footer no es tan intuitivo como querría que fuese, pero no sabía de qué otra forma ponerlo 😟 ¿qué me dices?

2023-04-13 23:32 UTC, zucerkia approved these changes
Todo lo veo OK 👍🏼 , como recomendación para el futuro, si el código comentado no es necesario mejor es eliminarlo antes de hacer el PR

2023-04-14 19:48 UTC, JoeOsG approved these changes
### Dale.

2023-04-14 20:28 UTC, merged