classes 1 and 2
undefined-academy/semana-1 pull request #617
Opened 2023-04-07 21:48 UTC by alesalazard

Siguiendo las instrucciones de los ejercicios propuestos, agrego mi perfil en un archivo Markdown, con dos tablas exponiendo algunos recursos de la terminal, e incluyendo un link a mi repo de GitHub al final.

2023-04-08 17:12 UTC, JohnMendoza182 commented on github-profiles/alexandretta-6987/alexandretta-6987.md
> +# **ALEXANDRA SALAZAR D**
Hola Este Archivo debe llamarse `README.md` debes cambiar el nombre

2023-04-08 18:27 UTC, alesalazard commented on github-profiles/alexandretta-6987/alexandretta-6987.md
> +# **ALEXANDRA SALAZAR D**
Gracias @JohnMendoza182 Voy a cambiarlo.

2023-04-08 18:33 UTC, alesalazard commented
@JohnMendoza182  Nombre del archivo modificado a README.md

2023-04-12 20:56 UTC, edwintorres1605 approved these changes
Está bien nombrado el archivo y se han usado correctamente la marcación de textos en markdown

2023-04-12 20:56 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/alexandretta-6987.md
> +# **ALEXANDRA SALAZAR D**
Realmente se debe llamar README.md es para la segunda práctica, en la primera está bien así como lo escribiste.

2023-04-12 21:21 UTC, edwintorres1605 requested changes

2023-04-12 21:21 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/index.html
> +    Come and watch my projects by clicking the next<a href="https://github.com/alesalazard/"> link</a>
Este párrafo está sin etiqueta que lo envuelva. El navegador le pondrá automáticamente <p> pero es mejor dejarlo con la etiqueta desde el código.

2023-04-12 21:21 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/index.html
> +      I have knowledge in <strong>frontend development</strong> with <strong>React.js</strong>, acquired at <Laboratoria>, an intensive programming bootcamp where I not only gained basic knowledge bu
Te recomiendo si vas a poner &lt;Laboratoria&gt; y quieres que aparezcan los paréntesis angulares, escribelos así:
`&lt;Laboratoria&gt;`
ya que de lo contrario lo asumirá como un elemento HTML que no existe

2023-04-12 21:30 UTC, edwintorres1605 requested changes

2023-04-12 21:30 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/index.html
> +      <h3 class="header-quote"><em>{ Kniting code and coding therapy }</em></h3>
Para estos corchetes te hago la misma recomendación de los paréntesis angulares de antes, mejor escribirlos así:
`&#123; Kniting code and coding therapy &#125;`

2023-04-12 21:30 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/index.html
> +      <table border='1'>
Esto solo es una recomendación, ya que igual te va a funcionar sin problemas, pero según la MDN los atributos de estilos para las tablas ya están obsoletos y se recomienda, por ejemplo en este caso, poner los bordes con estilos CSS

2023-04-12 21:30 UTC, edwintorres1605 commented on github-profiles/alexandretta-6987/style.css
Están bien los estilos, veo que hasta usaste flex. 👏🤓

2023-04-14 18:13 UTC, JoeOsG approved these changes
### Bien el MD y la pgina knitting code.

2023-04-15 00:16 UTC, alesalazard commented on github-profiles/alexandretta-6987/style.css
Súper las recomendaciones @edwintorres1605  muchas gracias 🥇 Haré los cambios para los de la semana 2.

2023-05-13 02:12 UTC, closed without merging