Mi perfil de Github
undefined-academy/semana-1 pull request #622
Opened 2023-04-09 01:32 UTC by MrAlizarinCrimson

Asignación de Semana 1 - Readme

2023-04-12 02:21 UTC, NathalyStudio requested changes
Como buena práctica, se recomienda que para la fuente utilizes medidas relativas (Como rem o em). 

También pudieras aplicar un _shorthand_ en el background. Referencia https://www.webfx.com/blog/web-design/background-css-shorthand/

2023-04-12 02:56 UTC, NathalyStudio approved these changes
Excellent! PR Approved!

2023-04-13 15:59 UTC, Pancratzia requested changes
Hola! A tu HTML debes agregarle una tabla con dos alias de la terminal, tal como lo indica la asignación. Lo demás lo veo bastante bien y veo que cumple con lo asignado

2023-04-15 02:26 UTC, NathalyStudio requested changes

2023-04-15 02:26 UTC, NathalyStudio commented on github-profiles/Mac-9025/index.html
> +	<table class=table1>
Las clases que uses deben ir entre comillas dobles, asi como lo hiciste en el div anterior, donde la class container esta entre comillas

2023-04-19 21:27 UTC, MrRedu requested changes
El _paso número 4 del ejercicio de la semana-1_, pide una sección con al menos dos comandos alias

Por lo demás, lo veo bastante bien ✌🏽 ahí estoy al pendiente de los cambios

2023-04-19 21:27 UTC, MrRedu commented on github-profiles/Mac-9025/Readme.md
> +##I'm a project management engineer##
Si la idea de los **##**, es que sean un título de segundo nivel, debes darle un espacio entre el signo y la letra, lo

2023-04-19 21:33 UTC, MrRedu requested changes

2023-04-19 21:33 UTC, MrRedu commented on github-profiles/Mac-9025/index.html
> +        </tbody>
Si no estoy mal, la etiqueta de cierra del <tbody>, está colocada en un lugar equivocado, dos etiquetas más arriba y listo 👍🏽

2023-04-19 21:42 UTC, NathalyStudio requested changes

2023-04-19 21:42 UTC, NathalyStudio commented on github-profiles/Mac-9025/index.html
> +    </div>
Este  div no se si esta de mas, pero si tienes un pequeño error, pues primero cierras la etiqueta tabla y luego la body y debería ser al revés.

2023-04-20 19:15 UTC, MrAlizarinCrimson commented on github-profiles/Mac-9025/index.html
> +        </tbody>
Muchas gracias, tienes razón, tuve lío con la indentación y no me había percatado vava Voy!! :)

2023-04-20 21:53 UTC, MrRedu approved these changes
¡Muy buen trabajo! 💯

2023-04-22 02:57 UTC, NathalyStudio approved these changes
Excelente trabajo!! Sigue así!✨

2023-04-22 20:02 UTC, merged