Mi perfil de GitHub Actividad 2
undefined-academy/semana-1 pull request #629
Opened 2023-04-10 22:15 UTC by JorgeJhan

Como se realizo:
1. Realice el Fork en Github
2. clone con el comando Git clone Link-del-repo 
3. git status para ver el estado
5. se agregan los archivos y cambios
5. Git add . para agregar los cambios
6. Git commit -m “comentario del commit” para realizar el commit
7. git status para verificar 
8. Git push para subirlo

2023-04-13 23:16 UTC, zucerkia requested changes
Todo lo veo Correcto 👍🏼 aunque en la parte del markdown, según el ejercicio te falta las tablas con los comandos y alias que usas

![image](https://user-images.githubusercontent.com/32274355/231902421-8af95425-d393-411e-b839-d0cfbc791635.png)

2023-04-14 12:15 UTC, Lmendev requested changes
Hola! 

La misma observación, faltan las tablas. Todo lo demás veo que está según lo requerido para la semana. 👍

2023-04-14 22:39 UTC, JorgeJhan commented
Gracias por los comentarios Lmendev y zucerkia,  ya realice los cambios 😀

2023-04-17 23:21 UTC, Lmendev approved these changes
Muy bueno @JorgeJhan! Lo dejo aprobado por mi parte ✔️

2023-05-04 02:12 UTC, closed without merging