Primer Pull Request
undefined-academy/semana-1 pull request #63
Opened 2023-03-04 21:13 UTC by nbarbettim

# Pasos  iniciales
Forkear el repositorio de un tercero bajarlo a local,  actualizarlo con los commits  y resubirlo a mi github para realizar el pull  request

# Desarrollo

1. *se forkea el  repositorio del tercero.*
2. *se clona en local por medio de la terminal*
3. *se crea el  documento markdown y  se ejecuta en  vsc para complementarlo*
4. *se realiza el pull para  actualizarlo con respecto al original*
5. *se realiza el commit  y posteriormente se realiza el push*
6. *por ultimo se solicita el pull request*

2023-03-09 18:34 UTC, kendar9 requested changes

2023-03-09 18:34 UTC, kendar9 commented on Nbarbetti-6907
> +# _Hi There, I am Nicolas Barbetti👋_
este archivo debe llamarse README.md y estar  en una carpeta con tu usario de discord

2023-03-20 21:33 UTC, Skydeer94 commented on Nbarbetti-6907/README.md
> +| ls | Lista los archivos de la carpeta actual |
Hola Nicolás, me gusto tu trabajo, te recomiendo manejar todo el archivo en inglés o todo en español para evitar conflictos para la persona que vea.

Gran trabajo.

2023-03-20 21:34 UTC, Skydeer94 reviewed
Hola Nicolás, me gusto tu trabajo, te recomiendo manejar todo el archivo en inglés o todo en español para evitar conflictos para la persona que vea.

Gran trabajo.

2023-03-20 21:44 UTC, Skydeer94 approved these changes

2023-03-26 20:24 UTC, ManuCastrillonM commented on Nbarbetti-6907/README.md
> +- 🌱 I’m currently learning **Full-stack Javascrip developer**
```suggestion
- 🌱 I’m currently learning **Full-stack JavaScript developer**

```

2023-03-26 20:25 UTC, ManuCastrillonM commented on Nbarbetti-6907/README.md
Hola Nicolas!
Por cohesion en la información, te recomendaría tener todo el texto en un mismo idioma sea ingles o español ya que leerlo en 'spanglish' puede resultar un poco confuso.

2023-03-27 01:26 UTC, nbarbettim commented on Nbarbetti-6907/README.md
Gracias por tu comentario!

Queda atendida la observacion

2023-03-27 01:26 UTC, nbarbettim commented on Nbarbetti-6907/README.md
> +| ls | Lista los archivos de la carpeta actual |
Gracias por tu comentario

Queda atendido

2023-03-27 11:09 UTC, merged