Mi perfil de GitHub
undefined-academy/semana-1 pull request #635
Opened 2023-04-11 21:52 UTC by camora28

¡Trate de seguir las indicaciones del profe, se cometieron algún par de errores infantiles! 
pero se logró
gracias, totales!!!

2023-04-16 04:22 UTC, maguz727 commented on github-profiles/cmora28-9243/README.md
> +| comando | Descripción |
Hola, te recomiendo que alinées la tabla para que se vea un poco más legible

2023-04-16 04:23 UTC, maguz727 commented on github-profiles/cmora28-9243/README.md
> +## Estos son mis alias más usados
Hola, la actividad es agregar 2 alias y describir que hace cada uno.

2023-04-22 02:08 UTC, delospp requested changes

2023-04-22 02:08 UTC, delospp commented on github-profiles/cmora28-9243/README.md
> +## Estos son mis alias más usados
te faltan los dos alias, por favor completa la actividad para aprovar el PR

2023-05-10 02:14 UTC, closed without merging