Ultimos cambios de la primer semana
undefined-academy/semana-1 pull request #648
Opened 2023-04-14 03:59 UTC by Diegu32

# Algo atrasado pero tratando de agarrarle la mano a GIT. 

## Ultimo pull request de la semana 1.

2023-04-14 04:17 UTC, zucerkia approved these changes
todo Ok 👍🏼 
Como recomendación en el CSS para que no tengas que repetir una propiedad que se comparte para varios selectores los puedes poner de esta manera:

```css
p, h1, h2, strong {
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
```

2023-04-14 15:36 UTC, Seujumon requested changes
Bárbaro, los archivos cumplen con las consignas. 
Solo faltó en la descripción del pull request que menciones cómo fue tu proceso para hacer el ejercicio. Hubo quienes optaron por describir cada paso, como si se tratara de una receta de cocina, y también quienes se enfocaron en si conocían o no del tema, qué dificultades tuvieron y cómo las pudieron resolver. Específicamente el punto decía lo siguiente y está en la clase 2 para que realices tu interpretación: 

> 7.- No dejes la descripción del Pull Request vacia, escribe cómo fue el proceso de resolver este ejercicio, usar Markdown. 
En cuanto agregues eso me va a saltar la notificación, y paso a dar approve.

2023-04-14 17:58 UTC, Diegu32 commented
> Bárbaro, los archivos cumplen con las consignas. 
> Solo faltó en la descripción del pull request que menciones cómo fue tu proceso para hacer el ejercicio. Hubo quienes optaron por describir cada paso, como si se tratara de una receta de cocina, y también quienes se enfocaron en si conocían o no del tema, qué dificultades tuvieron y cómo las pudieron resolver. Específicamente el punto decía lo siguiente y está en la clase 2 para que realices tu interpretación: 
> 
> > 7.- No dejes la descripción del Pull Request vacia, escribe cómo fue el proceso de resolver este ejercicio, usar Markdown. 
> 
> 
> En cuanto agregues eso me va a saltar la notificación, y paso a dar approve. 
> 

Hola! Muchas gracias por tu review, con respecto a lo que me marcas, si lo hice en el primer pull request que hice, aca pense que no lo tenia que volver a repetir pero lo voy hacer asi queda mas completo.

2023-04-14 18:22 UTC, Seujumon commented
> Hola! Muchas gracias por tu review, con respecto a lo que me marcas, si lo hice en el primer pull request que hice, aca pense que no lo tenia que volver a repetir pero lo voy hacer asi queda mas completo.

En el primer commit del 31 de marzo no me aparece. Tal vez sea otro PullRequest diferente. Quizás ya lo sabías, pero en caso de que no te comento que no es necesario hacer un pullreques nuevo cada vez que hagas un cambio. Cuando actualices tu repositorio personal, o sea la copia de este repositorio a la que hiciste fork, automáticamente se ven los cambios acá. Así que solo necesitás hacer el add de los cambios, commit y el push. Incluso cada tarea, en las siguientes semanas la idea es hacerlas en commits diferentes pero en un solo pullrequest.

2023-04-14 18:25 UTC, Diegu32 commented
> > Hola! Muchas gracias por tu review, con respecto a lo que me marcas, si lo hice en el primer pull request que hice, aca pense que no lo tenia que volver a repetir pero lo voy hacer asi queda mas completo.
> 
> En el primer commit del 31 de marzo no me aparece. Tal vez sea otro PullRequest diferente. Quizás ya lo sabías, pero en caso de que no te comento que no es necesario hacer un pullreques nuevo cada vez que hagas un cambio. Cuando actualices tu repositorio personal, o sea la copia de este repositorio a la que hiciste fork, automáticamente se ven los cambios acá. Así que solo necesitás hacer el add de los cambios, commit y el push. Incluso cada tarea, en las siguientes semanas la idea es hacerlas en commits diferentes pero en un solo pullrequest. 
> 
> 

Ahhh, bueno eso es otra de las tantas dudas que he tenido este tiempo, de todas formas gracias por la ayuda, la necesitaba, ahora lo tendre en cuenta para los proximos trabjos de las siguientes semanas

2023-04-14 18:32 UTC, Diegu32 commented
> > Hola! Muchas gracias por tu review, con respecto a lo que me marcas, si lo hice en el primer pull request que hice, aca pense que no lo tenia que volver a repetir pero lo voy hacer asi queda mas completo.
> 
> En el primer commit del 31 de marzo no me aparece. Tal vez sea otro PullRequest diferente. Quizás ya lo sabías, pero en caso de que no te comento que no es necesario hacer un pullreques nuevo cada vez que hagas un cambio. Cuando actualices tu repositorio personal, o sea la copia de este repositorio a la que hiciste fork, automáticamente se ven los cambios acá. Así que solo necesitás hacer el add de los cambios, commit y el push. Incluso cada tarea, en las siguientes semanas la idea es hacerlas en commits diferentes pero en un solo pullrequest. 
> 
> 

Con respecto a los commits si, he tenido algunas confusiones, y el commit que te digo al parecer lo hice en otro repositorio que forkee y clone, hmm.. Con respecto al push tengo una pregunta, porque cuando hago git push origin main me pide una cuenta y contraseña de git?

2023-04-14 18:46 UTC, Seujumon commented
> Con respecto a los commits si, he tenido algunas confusiones, y el commit que te digo al parecer lo hice en otro repositorio que forkee y clone, hmm.. Con respecto al push tengo una pregunta, porque cuando hago git push origin main me pide una cuenta y contraseña de git?

No estoy seguro, porque habría que ver el proceso que hiciste porque hay varias formas de clonar. Pero si hiciste los pasos de la llave ssh que nos pidieron en el prework y aún así te pide la contraseña, es probable que sea porque hiciste la clonación con https y no con ssh. Para poder clonar con ssh, abris el repo que querés clonar, vas al botón verde que dice  **<>Code** y en la pestaña local donde dice Clone por defecto viene marcado HTTPS y abajo te da ese link. Pero si querés clonar con ssh, tenés que marcar SSH y copiar ese link. El resto es igual. Vas en la terminal a la carpeta donde querés clonar, y  escribis ` git clone link_SSH_que_copiaste `

2023-04-14 20:17 UTC, 4ngelo12 approved these changes
Tu trabajo se ve muy bien felicidades.

2023-04-15 15:21 UTC, Diegu32 commented
> Tu trabajo se ve muy bien felicidades.

Gracias!

2023-04-16 03:15 UTC, merged