Agrego mi archivo
undefined-academy/semana-1 pull request #650
Opened 2023-04-14 17:21 UTC by pedrodinella

Dejo de mi perfil

2023-04-15 03:28 UTC, NathalyStudio approved these changes

2023-04-17 04:54 UTC, Luisdgamaya commented on github-profiles/Pedrito-2171/readme.md
> +## Alias que he usado hasta el momento
Seria bueno agregar la descripcion de los comandos en tu tabla

2023-04-20 07:17 UTC, Matiascba27 requested changes

2023-04-20 07:17 UTC, Matiascba27 commented on github-profiles/Pedrito-2171/index.html
> +        <link rel="stylesheet" href="/styles.css" />
esto tienes que agregarlo dentro del head antes del body

2023-05-09 02:20 UTC, closed without merging