Mi readme profile
undefined-academy/semana-1 pull request #660
Opened 2023-04-18 14:35 UTC by j7programador

#310 
Este es mi primer readme para mi profile de github.

2023-04-19 02:46 UTC, j7programador commented
Este es mi primer pull request en github.

2023-04-20 10:05 UTC, Lmendev requested changes
Super Jorge 👍 

Solo faltaron las tablas

2023-04-25 06:47 UTC, delospp commented on github-profiles/jorge.lopezy-2091/README.md
Te falta en markdown:
- una tabla de 5 comandos que tenga dos columnas, nombre de comando y descripción
- una sección con 2 alias que tenga dos columnas, nombre de alias y descripción

Quedó atento a los cambios para darte el approved

2023-04-25 06:47 UTC, delospp requested changes

2023-04-25 06:47 UTC, delospp commented on github-profiles/jorge.lopezy-2091/README.md
Te falta en markdown:
- una tabla de 5 comandos que tenga dos columnas, nombre de comando y descripción
- una sección con 2 alias que tenga dos columnas, nombre de alias y descripción

Quedó atento a los cambios para darte el approved

2023-04-26 05:38 UTC, delospp approved these changes

2023-04-26 05:38 UTC, delospp commented on github-profiles/jorge.lopezy-2091/README.md
> +|ALIAS|DESCRIPCION                                                 |
Tengo entendido que los alias deben ir en una sección así:
```bash
Comandos alias que me parezcan utiles
1. Alias1
2. Alias2
```

2023-04-26 10:40 UTC, Lmendev approved these changes
Por mi parte estoy ✅

⭐

2023-05-13 02:12 UTC, closed without merging