Mi perfil de GitHub
undefined-academy/semana-1 pull request #669
Opened 2023-04-21 00:20 UTC by Alepsss

# Pasos que hice para mi Pull-Request
1.-Investigué en la web como realizar un **FORK** de un repositorio.
2.-Realice mi fork.
3.-Abrí la terminal y clone mi fork.
4.-Use el comando *ls* para ver los archivos del repositorio.
5.- Use *code .* para abrirlo en VS Code.
6.-Desde **VS Code** creé mi archivo en la carpeta *github-profiles*.
7.-Agregué el link de mi perfil y mi Markdown.
8.-Realice el *commit* de archivo con apoyo de la Clase 2 diferida.
9.-Investigué cómo hacer un Pull-Request
Empecé a aplicar lo aprendido en la Clase 2, aunque me seguí apoyando de esa misma clase diferida, creé el archivo desde VS Code y agregué los datos necesarios que pedía el ejercicio, aunque me fue un tanto complicado realizar éste ejercicio,

2023-04-25 06:37 UTC, delospp requested changes

2023-04-25 06:37 UTC, delospp commented on github-profiles/Aleps-5699.md
Este archivo sobra, el contenido ya lo tienes en el README.md dentro de la carpeta con tu nombre de discord, porfa elimina el archivo para darte el approved 

Adicional si puedes ayudarme con la revision de mis PRs te agradezco

Semana 1
https://github.com/undefined-academy/semana-1/pull/632

Semana 2
https://github.com/undefined-academy/semana-2/pull/185

2023-04-27 02:54 UTC, Alepsss commented on github-profiles/Aleps-5699.md
Listo! 
Muchas gracias por la revisión, ya quedó solucionado, si pudieras ayudarme con tu approved, te lo agradecería.

Ahorita me doy el tiempo de revisar tus PR's.

2023-04-28 10:15 UTC, Lmendev approved these changes
🚀

2023-04-28 11:19 UTC, delospp approved these changes

2023-04-29 23:23 UTC, merged