Tareas semana 1
undefined-academy/semana-1 pull request #67
Opened 2023-03-04 22:58 UTC by gurrutia15

## Proceso
- Hice fork de la carpeta señalada
- Bajé la carpeta desde mi repositorio a una carpeta creada en el computador
- Creé un archivo <b>.md </b> nuevo en VSC usando el comando <b>code </b>
- Agregué el contenido al documento
- Utilicé los comandos <b>add </b> y <b>commit</b> para guardar el archivo con sus cambios
- Subí el archivo al repositorio "forkeado"
- Realicé la solicitud para el <b> pull request </b>

2023-03-10 05:10 UTC, nobody-redhawk commented on github-profiles/giub-7914/Readme.md
> +
Alinear los separadores de la tabla para que se vea mas presentable como la tabla anterior.

2023-03-10 05:11 UTC, nobody-redhawk approved these changes

2023-03-10 17:58 UTC, nobody-redhawk commented on github-profiles/giub-7914/Readme.md
> +
Genial, quedó mejor

2023-03-14 07:37 UTC, NoaSalgado approved these changes
Buen trabajo!!

2023-03-14 12:34 UTC, NicolasSebastianEstigarribia approved these changes
Buen trabajo te tomaste el trabajo de hacerlo como detalle: el readme.md esta empezando con mayúscula generalmente los archivos se escriben en formato CamelCase.

2023-03-24 08:25 UTC, glrodasz requested changes
El gitignore no se debería modificar pues es el archivo de la raíz del los proyectos.

2023-03-25 05:33 UTC, merged