Mi perfil en github hecho con markdown
undefined-academy/semana-1 pull request #679
Opened 2023-04-26 02:51 UTC by ciberelu

# COMO RESOLVI ESTE EJERCICIO

## 1. APRENDI QUE ES UN FORK Y COMO HACERLO

Lo primero fue que busque en internet que es un fork y aprendí que es hacer una copia de una repositorio a mi perfil de github para tener una copia y a partir de allí poder hacer modificaciones. 

No sabia cual era el comando para crear archivos desde la terminal con ubuntu así que busque y encontré que se hace con touch así que hice el archivo ciberelu-9310.md desde la terminal.

## 2. PULL REQUEST 

Un Pull Request es mandar nuevo código al repositorio del cual se hizo fork, para hacerlo se va al repositorio forkeado y desde alli se manda el pull request desde github al repositorio desde donde se le hizo el fork. **se añade descripción**

**GRACIAS GUILLE POR TODO LO QUE NOS ENSEÑAS**

2023-05-11 00:58 UTC, Pedro-Alp requested changes

2023-05-11 00:58 UTC, Pedro-Alp commented on github-profiles/ciberelu-9310/README.md
> +### Comando que puedo utilizar en la terminal de ubuntu
En el README solo falta que la tabla de comandos tenga al menos 5 comandos (te faltan dos) y hay que añadir una sección con 2 comandos alias y su respectiva descripción

2023-05-13 00:50 UTC, ciberelu commented on github-profiles/ciberelu-9310/README.md
> +### Comando que puedo utilizar en la terminal de ubuntu
Hola, podría por favor revisar nuevamente, espero obtener su aprove

2023-05-13 01:42 UTC, Pedro-Alp approved these changes
Olvidando la eliminación del README todo esta correcto.

2023-05-13 01:42 UTC, Pedro-Alp commented on README.md
Creo que eliminaste el archivo README.md de la raíz del proyecto(del main) en el que se encontraba la información de la Semana 1 y la explicación de los ejercicios, debes de recuperarlo sino no te van a dejar hacer merge.

2023-05-13 01:48 UTC, byRokii approved these changes
Vi todo bien, el compañero pedro ya comento lo que te hacia falta y quedo nice!

2023-05-28 02:31 UTC, closed without merging