Mi perfil de Github
undefined-academy/semana-1 pull request #706
Opened 2023-05-19 01:49 UTC by Karomogo26

# ✍ Semana 1 Ejercicio 2
## Usando mi terminal de Ubuntu realicé lo siguiente:
- Hice un **FORK** del repositorio https://github.com/undefined-academy/semana-1
Haciendo esto descubrí que un fork es hacer una copia de un repositorio en mi cuenta de GitHub y que este repositorio copiado será igual al repositorio desde el que se realiza el fork en Git.
- Cloné el repositorio **FORKED** en mi carpeta de HOME.
- Agregue dentro de la carpeta github-profiles un archivo Markdown de mi perfil de GitHub (el cual ya había hecho con en el ejercicio anterior) el cual incluye un link que los lleva directamente a mi perfil de GitHub, y el nombre de archivo es _Karo26-9917.md_
- Hice commit de dicho archivo.

### Desde la pagina de Github 
- Como último paso del ejercicio vine a dejar mi primer Pull Request.

----

Apenas estoy empezando los ejercicios, ya que me quede sin pc hasta ahora, pero intento ponerme al día.🙏

2023-05-20 03:48 UTC, michaelfdz requested changes
He sugerido que podrías usar  la sintaxis de **hyperlink** para el texto con el perfil de **Github**, y te hace falta 2 puntos del ejercicio.

2023-05-20 03:48 UTC, michaelfdz commented on github-profiles/karo26-9917/README.MD
> +https://github.com/Karomogo26
Podrías haber usado la sintaxis para hyperlinks `[Texto tu Perfil de Github](https://github.com/Karomogo26)`

2023-05-20 03:48 UTC, michaelfdz commented on github-profiles/karo26-9917/README.MD
> +----
Hace falta los 2 puntos del ejercicio en el cual se pedían:
1.  Añadir una tabla en Markdown  con al menos **5 comandos** de la Terminal con nombre del comando y descripción en columnas separadas.
2. Añade una sección con al menos 2 comandos **alias** que te parezcan útiles incluyendo columna de descripción.

2023-05-20 03:54 UTC, Karomogo26 commented on github-profiles/karo26-9917/README.MD
> +https://github.com/Karomogo26
Si está muy buena tu sugerencia lo hare, muchas gracias.

2023-05-20 03:57 UTC, Karomogo26 commented on github-profiles/karo26-9917/README.MD
> +----
Hola, eso lo hice en el primer ejercicio puedes verlo en mi perfil, este es el segundo el de mi primer pull request, como en la grabación guillermo dijo que podiamos modificarlo, pues coloque solo mi perfil.
Gracias por tu comentario 😊

2023-05-20 15:28 UTC, Manulopsan reviewed
Te faltaría añadir alguna tabla, en el ejercicio se pedían dos tablas, yo creo que sería necesario al menos hacer una tanto en markdown como después en html para practicarlo.

2023-05-30 02:57 UTC, Karomogo26 commented on github-profiles/karo26-9917/README.MD
> +https://github.com/Karomogo26
> Podrías haber usado la sintaxis para hipervínculos`[Texto tu Perfil de Github](https://github.com/Karomogo26)`

listo compañero, ya segui tu consejo.

2023-05-30 02:58 UTC, Karomogo26 commented
> Te faltaría añadir alguna tabla, en el ejercicio se pedían dos tablas, yo creo que sería necesario al menos hacer una tanto en markdown como después en html para practicarlo.

Listo compañero ya lo hice, Gracias

2023-05-30 03:20 UTC, Karomogo26 commented
Compañeros listo ya hice todas las correcciones, les agradezco si me vuelven a revisar quedo atenta a sus comentarios o sugerencias, gracias ✍

2023-05-30 03:28 UTC, Karomogo26 commented on github-profiles/karo26-9917/README.MD
> +----
> Hace falta los 2 puntos del ejercicio en el cual se pedían:
> 
> 1. Agregue una tabla en Markdown con al menos **5 comandos** de la Terminal con nombre del comando y descripción en columnas separadas.
> 2. Añade una sección con al menos 2 comandos **alias** que te parezcan útiles, incluida la columna de descripción.

Compañero listo ya agregué lo que faltaba, agradezco su revisión y comentario, gracias.

2023-06-16 03:45 UTC, merged