my profile git hub
undefined-academy/semana-1 pull request #724
Opened 2023-06-01 02:46 UTC by alejox

TODO: Proceso de PR

2023-06-16 05:45 UTC, alejox commented
#Profile GitHub 

Project made with a lot of love for the Bootcamp, and happy with the results. I already had some knowledge, but we never stop learning new things. 😎

2023-06-23 17:06 UTC, MrRedu requested changes
### ¡Hola!

Tengo unas pequeñas correcciones, comenzando con que tienes un archivo fuera de tu carpeta: 
![image](https://github.com/undefined-academy/semana-1/assets/73679190/337890a2-693b-415d-af7d-fb3c1faf48e6)

Como recomendación, el archivo de readme `.md` *(Markdown)*, debería terminar con la extensión en minúscula

Otra cosa que puedo observar, es que no está la tabla de comandos en el README

Y por último, si te soy sincero, no recuerdo con exactitud, pero si no estoy mal, el último ejercicio de la semana, sería agregarle CSS al HTML, y no veo por ningún lado ese archivo

Te recomiendo ver los ejercicios en el README del repositorio *(https://github.com/undefined-academy/semana-1),* para que se escapen las menores cosas posibles

2023-06-24 01:35 UTC, alejox commented
@MrRedu , agradezco tus observaciones, realice las correcciones, lo del css esta en la semana 2 , si te puedes pasar por alla te agradezco infinitamente, buen día

2023-06-24 01:45 UTC, MrRedu approved these changes
### ¡Buen trabajo! 💪🏼

2023-06-25 15:03 UTC, Gaston095 approved these changes
Buen trabajo!! Sigue asi! Vas muy bien..

2023-07-12 02:45 UTC, closed without merging