Ejercicio-Semana-1
undefined-academy/semana-1 pull request #73
Opened 2023-03-05 01:01 UTC by fmanzano26

# Pasos para resolver el **Ejercicio** :
* Fork en el [Repositorio](https://github.com/undefined-academy/semana-1)
* Se clono el repositorio mediante el _comando_ **git clone**
* He agregado el archivo Markdown y el [Link](https://github.com/fmanzano26) de mi perfil de **GitHub**
* _Commit_ y por ultimo  _Pull requests_

2023-03-09 23:32 UTC, lllariogonzalez requested changes
El markdown no se tenía que eliminar, debía renombrarse a README.md y guardarlo en la carpeta nueva creada con tu nombre de usuario en Discord.

2023-03-09 23:48 UTC, nobody-redhawk approved these changes

2023-03-09 23:54 UTC, nobody-redhawk commented
se cumplió con todas las actividades requeridas en los ejercicios, éxitos.

2023-03-14 12:22 UTC, lllariogonzalez approved these changes
Se cumple con los objetivos :octocat: , detalle: se filtra archivo .DS_Store

2023-03-24 00:20 UTC, merged