Adding luanarmo-7586 Profile
undefined-academy/semana-1 pull request #76
Opened 2023-03-05 01:12 UTC by luanarmo

# Pasos para resolver el ejercicio
- Forkear reporitorio 
- Clonar repositorio forkeado
- Crear archivo/ mover el archivo markdown en la carpeta github-profiles
- Hacer git add y git commit
- Hacer git push al repositorio Forkeado en el perfil personal
- Crear PR

2023-03-09 23:32 UTC, adrian-gg requested changes

2023-03-09 23:32 UTC, adrian-gg commented on github-profiles/luanarmo-7586.md
> +| Command 	| Description                               |
Estaría bien que la tabla estuviera alineada, como la de abajo.

2023-03-09 23:32 UTC, adrian-gg commented on github-profiles/luanarmo-7586.md
> +|   Command             |    Description                                                                                                               |
**Minireto!!** Añade el alias del cafe: `alias cafe="cat /dev/urandom | hexdump | grep "ca fe""` sin que la tabla se rompa.
Digo que es un reto porque el comando utiliza --> | que es con lo que se compone la tabla.

2023-03-11 06:07 UTC, luanarmo commented on github-profiles/luanarmo-7586.md
> +| Command 	| Description                               |
Listo, alineado ✅

2023-03-11 06:08 UTC, luanarmo commented on github-profiles/luanarmo-7586.md
> +|   Command             |    Description                                                                                                               |
Listo, reto completado ✅

2023-03-11 13:34 UTC, mookie34 reviewed
Good Job Bro!

2023-03-11 15:49 UTC, nobody-redhawk approved these changes

2023-03-11 15:50 UTC, nobody-redhawk commented
Está toda las actividades rqueridas en los ejercicios

2023-03-11 19:50 UTC, adrian-gg approved these changes

2023-03-14 09:53 UTC, merged