Semana 1: Actividad 2
undefined-academy/semana-1 pull request #82
Opened 2023-03-05 02:54 UTC by adrian-gg

# Semana-1: Actividad 2

#### Pasos que he realizados para completar la práctica:
  * _Me he preparado un colacao calentito._
1. Le he dado al botón Fork del repositorio https://github.com/undefined-academy/semana-1 para hacer una copia en mi perfil de github (me pregunto si se podrá hacer desde la terminal 🤔)
2. He dudado si la carpeta "HOME" a la que se refería el ejercicio era la carpeta home (``/home``) o la de mi nombre (``/home/garicarandai``) puesto que en la terminal aparece esta última ruta por defecto. Puede que la duda pareciese tonta, pero resulta que tenía razón. Viva yo.
  * _Sorbito al colacao._
3. Con el comando ``git clone`` he clonado el repositorio en mi computer. Chupate esa oveja Dolly.
4. Aprovechando los comandos ``cp`` y ``mv`` he copiado y renombrado el archivo markdown que ya tenía creado sobre mi perfil de la práctica anterior.
  * _Se ha enfriado el colacao, he ido a calentarlo._
5. He comiteado el archivo con el comando ``git commit`` y no ha explotado nada. Parece que voy bien.
  * _Otro sorbito al... AUH! Como quema._
6. Por último, he seguido un tutorial que han pasado por Discord de cómo hacer un pull request (me pregunto si también se podrá hacer desde la terminal 🤔)

2023-03-10 17:54 UTC, Romeo-Zulu commented
Hola, buen trabajo!
Veo que te han quedado los archivos dentro de la carpeta img (quizas los has puesto por que asi lo querias) pero el ejercicio pedia que esten dentro de la carpeta github-profiles/"usuario Discord sin el #" y que hagas mv (mover / renombrar) al archivo "usuario Discord".md a dicha carpeta renombrandolo como "README.md" y que contenga el link de tu profile de github.
Espero haber sido de ayuda.
Saludos.

2023-03-10 17:56 UTC, Romeo-Zulu requested changes
Hola, buen trabajo!
Veo que te han quedado los archivos dentro de la carpeta img (quizas los has puesto por que asi lo querias) pero el ejercicio pedia que esten dentro de la carpeta github-profiles/"usuario Discord sin el #" y que hagas mv (mover / renombrar) al archivo "usuario Discord".md a dicha carpeta renombrandolo como "README.md" y que contenga el link de tu profile de github.
Era por aqui la review.
Saludos

2023-03-14 17:10 UTC, Alexis033 approved these changes
Hola, está genial tu trabajo, y estuve viendo tu portafolio :O me encanta el diseño, lo único que te diría es que sería más comodo que le menú no estuviera siempre escondido en resoluciones de pantalla grandes (que fuera opcional esconderlo o no), se hace un poco incomodo estar abriendo y cerrando el menú cada vez que quiero ir a alguna parte. Pero son muy geniales tus diseños

2023-03-14 19:16 UTC, adrian-gg commented
> Hola, buen trabajo! Veo que te han quedado los archivos dentro de la carpeta img (quizas los has puesto por que asi lo querias) pero el ejercicio pedia que esten dentro de la carpeta github-profiles/"usuario Discord sin el #" y que hagas mv (mover / renombrar) al archivo "usuario Discord".md a dicha carpeta renombrandolo como "README.md" y que contenga el link de tu profile de github. Era por aqui la review. Saludos

Lo he estado viendo y el único archivo que hay dentro de la carpeta **img** es la imagen _header.img_ Si te fijas en la ruta de los archivos, todos están dentro de la carpeta **garicarandai-2859** También puedes comprobarlo al contraer la carpeta **img** y ver que el único archivo que se oculta es la imagen. 
Muchas gracias por tu feedbak y tiempo :)

2023-03-14 19:19 UTC, adrian-gg commented
> Hola, está genial tu trabajo, y estuve viendo tu portafolio :O me encanta el diseño, lo único que te diría es que sería más comodo que le menú no estuviera siempre escondido en resoluciones de pantalla grandes (que fuera opcional esconderlo o no), se hace un poco incomodo estar abriendo y cerrando el menú cada vez que quiero ir a alguna parte. Pero son muy geniales tus diseños

Muchas gracias. Sí es algo a lo que tuve que renunciar a cambio de que el menu fuera a la vez el scroll 😅

2023-03-20 19:27 UTC, Hernan4280 approved these changes
Esta perfecto. Cumple con todas las consignas.

2023-03-21 02:05 UTC, Romeo-Zulu approved these changes
Buenas. Ya vi que esta todo Ok la estructura.
buen trabajo

2023-03-21 19:29 UTC, dfm555 requested changes

2023-03-21 19:32 UTC, dfm555 requested changes

2023-03-21 19:32 UTC, dfm555 commented on github-profiles/GariCarandai-2859/style.css
> +  /*border: 2px solid #c9c9c9;*/
Remover código comentado

2023-03-22 13:04 UTC, dfm555 approved these changes

2023-03-22 13:06 UTC, merged