Ejercicio Semana 1 Git
undefined-academy/semana-1 pull request #84
Opened 2023-03-05 05:11 UTC by INGCapaDev

# Ejercicio Semana 1 Git 

## Pasos a seguir para realizar el ejercicio

Los pasos que segui para realizar este _ejercicio_ fueron los siguientes.

### Realizar un fork del repositorio del ejercicio

Primero entre a **GitHub** con el link del repositorio que nos proporciono el profesor Guillermo y realize un ```fork``` para clonar el repositorio en mi perfil de **GitHub** y me permitiera realizar cambios.

### Clonar el repositorio

Realize una copia del repositorio con el comando ```git clone``` en mi entorno de desarrollo con **WSL**.

### Agregar el archivo de mi perfil de GitHub

Seguido de esto añadi el archivo markdown de mi perfil de **GitHub** en la carpeta ```github-profiles``` que se encontraba dentro de los archivos del repositorio.

### Realizar un commit de los cambios

Una vez terminado el archivo utilize el comando ```git add .```para mandar mis cambios a la staging area y posteriormente realizar su respectivo commit con el comando ```git commit -m 'nombre del commit'```

### Realizar la pull request

Actualmente me encuentro realizando la **pull request** espero mis cambios sean aceptados por el profesor y haber cumplido con lo que se pedia en el ejercicio.

2023-04-09 20:41 UTC, Diegu32 commented
Se ve bastante bien el código, el tema es que no se si puede pero te pregunto, puedo ver tu archivo index en un navegador?

2023-04-11 19:39 UTC, INGCapaDev commented
@Diegu32 si clonas el repositorio en tu maquina deberias de poder verlo

2023-04-11 19:46 UTC, Diegu32 commented
> @Diegu32 si clonas el repositorio en tu maquina deberias de poder verlo
> 

En ese caso si me aparece pero porque cuando entro a la repo de undefined-academy aparecen varios Github profiles pero el mío no aparece, y la otra duda es, en qué caso se hace git merge? Eso tiene algo que ver con que mi perfil aparezca en ese repo?

2023-04-13 23:57 UTC, Diegu32 approved these changes
Cuando te deje un comentario el otro dia olvide que tenia que revisar tu ejercicio asi que ahora que entendi aun un poco mejor a github te cuento que la verdad lo veo muy bien al  ejercicio que hiciste, asi que te felicito!

2023-04-15 11:13 UTC, Lmendev requested changes
Hola @INGCapaDev ! Se ve bien, solo faltaron [las tablas](https://github.com/undefined-academy/semana-1/blob/main/README.md#clase-1-ejercicio)

2023-04-16 00:17 UTC, jorge9372 requested changes
Hola, te faltan las tablas con los 5 comandos y la lista con los alias solicitados en el ejercicio.

De resto todo bien. Saludos

2023-04-16 00:17 UTC, jorge9372 commented on github-profiles/FTACapa-8510/README.md
Saludos, te faltan las tablas con los comandos, y los alias solicitados en el ejercicio.

De resto se ve bien.

2023-04-16 17:32 UTC, Enmanuelt2 approved these changes
Muy buen trabajo @INGCapaDev!

2023-04-17 21:31 UTC, INGCapaDev commented
@Lmendev , @jorge9372  ya agregue los cambios solicitados, les agradeceria si pudieran regalarme su approve.

2023-04-17 21:50 UTC, jorge9372 approved these changes
Saludos, en el html también puedes incluir las tablas

2023-04-17 23:08 UTC, Lmendev approved these changes

2023-04-18 09:51 UTC, merged