Update README.md
undefined-academy/semana-1 pull request #91
Opened 2023-03-05 13:24 UTC by DevOld112

2023-03-09 19:20 UTC, DevOld112 commented
_Me costo mucho entender el paso final para hacer pull request pero ahi va lo que hice:_

## Ejercicio 2

1)   Hice **Fork** del repositorio
2)   Clone el repositorio en mi carpeta **HOME**
3)   A través de la terminal cree una carpeta llamada Semana-1 y copie el  **MARKDOWN.md** de mi Github a un archivo local
4)   Hice commit pero se me olvido agregar un mensaje en el commit xD
5)  Por alguna razón los primeros 2 intentos no me dejaba hacer **Pull-Reques**t pero al final pude lograrlo en este intento.

2023-03-11 00:41 UTC, DevOld112 commented
## Ejercicio 3: HTML (Paso a paso):

La verdad la parte fácil del ejercicio **(para mi, obviamente)** fue armar el archivo index.html, pero en serio me cuesta un mundo entender el funcionamiento de git y github, cada vez que hacia los _Push_ sentía que enviaba al Github cambios que no quería hacer, pero después de mucha practica creo que le he código el truco.

1) Cree un archivo index.html con lo explicado en la clase 3.
2) Intente hacerlo lo mas amigable posible a la vista.
3) Hice _git commit -m " "_ y _push_

Gracias por tu tiempo en revisar mi ejercicio (No tarea XD)

2023-03-11 00:48 UTC, DevOld112 commented
## Ejercicio 4: CSS (Paso a Paso):

Siento que ya he entendido como funciona un poco el git y hacer esto me tomo menos de 5 minutos, que felicidad :smile:

1) Enlazar en mi archivo _index.html_ el archivo _style.css_ para llevar separada la hoja de estilos **(CSS)** con el maquetado **(HTML)**
2) Cree unos **Globales** para hacer un poco mas atractivo el proyecto.
3) Revisar como lo hizo Jeremy Thomas en su pagina web en 4 minutos
4) Hice _commit_ y _Push_

Pueden creer que estuve a punto de tirar la toalla con git? jajajaja

2023-03-11 01:35 UTC, isuligoy requested changes
Hola buenas, lo único que deberías entrar es lo que esta en la carpeta **Wilder-8071** el resto no es necesario.
Como por ejemplo lo que tenes en **github-profile** como tampoco el archivo **semana-1** no hace falta, los pasos de los commite ya los tenes en el pull request con eso es mas que suficiente.
Como te digo no es necesario tenerlo los archivos **github-profile** / **semana-1** como archivos.
Te adjunto una foto para que veas de que hablo
![foto](https://user-images.githubusercontent.com/87563299/224457755-b620cd09-7927-4500-b571-3d0cc914afc4.png)
De todos modos te quedo muy bueno!!!

2023-03-11 01:35 UTC, isuligoy commented on README.md
> -# semana-1
Me parece que se te traspapelo este archivo.

2023-03-11 01:35 UTC, isuligoy commented on github-profiles/Wilmer-8071.md
> +# DevOld112
Estos archivos no son necesarios para el ejercicio

2023-03-11 02:06 UTC, nobody-redhawk requested changes
# Recomendaciones
1. Realizar la descripicion paso a paso de las actividades requeridas en los ejercicios de las clases de la semana 1.
2. Mover la carpeta `Wilmer-8071` a la carpeta `github-profiles`
3. eliminar el archivo `Wilmer-8071.md` de la carpeta `github-profiles`
4. Hacer deployin con vercel y compartir el link en la descripcion para ver el resultado.

Ver mi pull request: [pulsa aquí](https://github.com/undefined-academy/semana-1/pull/281) dejar tu recomendación.

2023-03-11 10:40 UTC, DevOld112 commented
> # Recomendaciones
> 1. Realizar la descripicion paso a paso de las actividades requeridas en los ejercicios de las clases de la semana 1.
> 2. Mover la carpeta `Wilmer-8071` a la carpeta `github-profiles`
> 3. eliminar el archivo `Wilmer-8071.md` de la carpeta `github-profiles`
> 4. Hacer deployin con vercel y compartir el link en la descripcion para ver el resultado.
> 
> Ver mi pull request: [pulsa aquí](https://github.com/undefined-academy/semana-1/pull/281) dejar tu recomendación.
> 
> 

Perfectoooo, hoy mismo aplicaré los cambios. Gracias por tu revisión y la recomendación. Más tarde lo haré 🙂

2023-03-11 18:13 UTC, DevOld112 commented on github-profiles/Wilmer-8071.md
> +# DevOld112
Realizare las modificaciones en este momento, gracias por todo el feedback que me has dado.

2023-03-11 20:59 UTC, DevOld112 commented
> # Recomendaciones
> 1. Realizar la descripicion paso a paso de las actividades requeridas en los ejercicios de las clases de la semana 1.
> 2. Mover la carpeta `Wilmer-8071` a la carpeta `github-profiles`
> 3. eliminar el archivo `Wilmer-8071.md` de la carpeta `github-profiles`
> 4. Hacer deployin con vercel y compartir el link en la descripcion para ver el resultado.
> 
> Ver mi pull request: [pulsa aquí](https://github.com/undefined-academy/semana-1/pull/281) dejar tu recomendación.

Hice las modificaciones, y me cree una cuenta en Vercel pero cuando deploying de mi proyecto solo se envia el archivo HTML

2023-03-11 22:06 UTC, nobody-redhawk commented
Lo hice el deploying, el detalle está en la ruta del archivo css, debes modificarlo `<link rel="stylesheet" href="./style.css">` Este es el resultado [Mirar aquí](https://wilmer-8071-nobody-redhawk.vercel.app/)

2023-03-11 22:09 UTC, nobody-redhawk commented on github-profiles/Wilmer-8071/index.html
> +    <link rel="stylesheet" href="../Wilmer-8071/style.css">
Modificar la ruta del archivo css: `<link rel="stylesheet" href="./style.css">` o de esta forma `<link rel="stylesheet" href="style.css">`

2023-03-12 17:09 UTC, nobody-redhawk approved these changes
Está toda la informacion requerida de los ejercicios.

2023-03-12 20:49 UTC, isuligoy approved these changes
Está todo lo que se pide para el ejercicio!, te quedo excelente, felicitaciones! 🎉

2023-03-13 03:24 UTC, DevOld112 commented
> Está todo lo que se pide para el ejercicio!, te quedo excelente, felicitaciones! 🎉

Gracias por tomarte el tiempo de revisar todo. Lo aprecio mucho amigo.

2023-03-14 09:37 UTC, merged